// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };


//////////
// source: types.go

/** MCPSettings describes the service MCP endpoint Android can use for tools and resources. */
export interface MCPSettings {
  endpoint: string;
  protocolVersion: string;
  authRequired: boolean;
}

/** VoiceGatewaySettings describes the preferred voice gateway for this service. */
export interface VoiceGatewaySettings {
  required: boolean;
  url?: string;
  authRequired?: boolean;
  tokenEndpoint?: string;
}

/** WebShellSettings describes the hosted frontend's native-shell contract. */
export interface WebShellSettings {
  bridgeVersion: number /* int */;
  mcp: MCPSettings;
  voiceGateway: VoiceGatewaySettings;
}

/** Settings is the service compatibility document consumed by Go Mode Android. */
export interface Settings {
  service: string;
  serviceVersion?: string;
  apiVersion: number /* int */;
  webShell: WebShellSettings;
}

/** ErrorBody describes a Go Mode API error. */
export interface ErrorBody {
  code: string;
  message: string;
}

/** ErrorResponse is the standard JSON error envelope for Go Mode SDK clients. */
export interface ErrorResponse {
  error: ErrorBody;
  details?: { [key: string]: any /* json.RawMessage */};
}

