// Code generated by gen-api-sdk. DO NOT EDIT.
import type { CloseSessionResp, Compatibility, ErrorResponse, HealthResp, OfferReq, OfferResp } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

function makeRequester(fetchFn: FetchFn) {
  return async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const init: RequestInit = { method, headers: { "Content-Type": "application/json" }, signal: AbortSignal.timeout(60_000) };
    if (body !== undefined) init.body = JSON.stringify(body);
    const res = await fetchFn(path, init);
    if (!res.ok) {
      const err = (await res.json()) as ErrorResponse;
      const e = new APIError(res.status, err.error.code, err.details);
      e.message = err.error.message;
      throw e;
    }
    return res.json() as Promise<T>;
  };
}

// createApiClient returns an API client bound to the given fetch function.
// When fetchFn is omitted, globalThis.fetch is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createApiClient(fetchFn: FetchFn = (globalThis as any).fetch.bind(globalThis)) {
  const request = makeRequester(fetchFn);
  return {
    /** Returns gateway health status. */
    health: (): Promise<HealthResp> => request<HealthResp>("GET", "/health"),
    /** Returns gateway compatibility metadata. */
    compat: (): Promise<Compatibility> => request<Compatibility>("GET", "/compat"),
    /** Creates a WebRTC voice session from an SDP offer. */
    offer: (req: OfferReq): Promise<OfferResp> => request<OfferResp>("POST", "/offer", req),
    /** Closes an active voice gateway session. */
    closeSession: (sessionID: string): Promise<CloseSessionResp> => request<CloseSessionResp>("POST", `/sessions/${sessionID}`),
  };
}
