// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };


//////////
// source: types.go

/** HealthResp is returned by GET /health. */
export interface HealthResp {
  status: string;
}

/** Compatibility is returned by GET /compat on the standalone voice gateway. */
export interface Compatibility {
  service: string;
  gatewayProtocol: number /* int */;
  serviceKinds: string[];
  capabilities: string[];
}

/** ServiceAuthorization authorizes one service-bound voice session. */
export interface ServiceAuthorization {
  kind: string;
  instanceID: string;
  baseURL: string;
  token: string;
}

/** OfferReq starts a voice gateway WebRTC signaling session. */
export interface OfferReq {
  protocolVersion: number /* int */;
  sdp: string;
  service: ServiceAuthorization;
}

/** OfferResp returns the WebRTC SDP answer and gateway session ID. */
export interface OfferResp {
  sdp: string;
  sessionID: string;
}

/** CloseSessionResp is returned after closing a voice gateway session. */
export interface CloseSessionResp {
  protocolVersion: number /* int */;
  status: string;
}

/** ErrorDetails holds the code and message within an error response. */
export interface ErrorDetails {
  code: string;
  message: string;
}

/** ErrorResponse is the JSON envelope for voice gateway error responses. */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any /* json.RawMessage */};
}

