// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };


//////////
// source: types.go

/** VoiceTokenResp is the response for GET /api/v1/voice/token. */
export interface VoiceTokenResp {
  token: string;
  expiresAt: string;
  ephemeral: boolean;
}

/** VoiceRTCOfferReq is the request body for POST /api/v1/voice/rtc/offer. */
export interface VoiceRTCOfferReq {
  sdp: string;
}

/** VoiceRTCAnswerResp is the response for POST /api/v1/voice/rtc/offer. */
export interface VoiceRTCAnswerResp {
  sdp: string;
  sessionID: string;
}

/** StatusResp is a common response for mutation endpoints. */
export interface StatusResp {
  status: string;
}

export interface ErrorDetails {
  code: string;
  message: string;
}

export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any /* json.RawMessage */};
}

