// Code generated by gen-api-sdk. DO NOT EDIT.

// Runtime schema validators for SSE payloads.
// Each validator checks structural correctness at runtime and throws
// TypeError on mismatch. Unknown kinds pass through for forward compat.

import type { ISOTimestamp } from "./types.gen";

// ---- helpers ----

function asObject(v: unknown, path: string): Record<string, unknown> {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    throw new TypeError(path + ": expected object");
  }
  return v as Record<string, unknown>;
}

function asString(v: unknown, path: string): string {
  if (typeof v !== "string") {
    throw new TypeError(path + ": expected string, got " + typeof v);
  }
  return v;
}

function asNumber(v: unknown, path: string): number {
  if (typeof v !== "number" || Number.isNaN(v)) {
    throw new TypeError(path + ": expected number, got " + typeof v);
  }
  return v;
}

function asBoolean(v: unknown, path: string): boolean {
  if (typeof v !== "boolean") {
    throw new TypeError(path + ": expected boolean, got " + typeof v);
  }
  return v;
}

function validateArray(v: unknown, path: string, elemValidator: (v: unknown) => unknown): unknown[] {
  if (!Array.isArray(v)) {
    throw new TypeError(path + ": expected array, got " + (v === null ? "null" : typeof v));
  }
  return v.map((e, i) => elemValidator(e));
}

function validateRecord(v: unknown, path: string, valValidator: (v: unknown) => unknown): Record<string, unknown> {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    throw new TypeError(path + ": expected object, got " + (v === null ? "null" : Array.isArray(v) ? "array" : typeof v));
  }
  const result: Record<string, unknown> = {};
  for (const k of Object.keys(v as Record<string, unknown>)) {
    result[k] = valValidator((v as Record<string, unknown>)[k]);
  }
  return result;
}

