// Golden-file tests for ExportDiscussion using the Codex parser.
//
// Golden files are generated by record-trace (go generate). To regenerate:
//
//	go generate ./backend/internal/agent/codex/...

package codex_test

import (
	"testing"

	"github.com/caic-xyz/caic/backend/internal/agent"
	"github.com/caic-xyz/caic/backend/internal/agent/agenttest"
	"github.com/caic-xyz/caic/backend/internal/agent/codex"
	"github.com/caic-xyz/caic/backend/internal/taskslog"
)

func TestExportDiscussionGolden(t *testing.T) {
	t.Parallel()
	agenttest.RunExportDiscussionGolden(t, func(path string, backends agent.Backends) (string, error) {
		return taskslog.ExportDiscussion(path, backends)
	}, codex.New("", nil))
}
