// Executes tasks by orchestrating agent runs and recording their results.

package task

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/trace"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/caic-xyz/caic/backend/internal/agent"
	"github.com/caic-xyz/caic/backend/internal/agent/claudecode"
	"github.com/caic-xyz/caic/backend/internal/agent/codex"
	"github.com/caic-xyz/caic/backend/internal/agent/opencode"
	"github.com/caic-xyz/caic/backend/internal/agent/pi"
	"github.com/caic-xyz/md"
	"github.com/caic-xyz/md/gitutil"
	"golang.org/x/sync/errgroup"
)

// StartOptions holds optional flags for container startup.
type StartOptions struct {
	DockerImage string
	Harness     agent.Harness
	Tailscale   bool
	USB         bool
	Display     bool
	Sudo        bool
	// MaxCPUs limits the number of CPU cores the container may use.
	// Zero means use [md.DefaultMaxCPUs].
	MaxCPUs int
	// GitHubToken is the resolved GitHub token to inject into the container's
	// environment. Empty means no token is injected.
	GitHubToken string
	// LogWriter receives provisioning log lines from the container backend.
	// Must not be nil.
	LogWriter io.Writer
}

// ContainerBackend abstracts md container lifecycle operations for testability.
type ContainerBackend interface {
	// Launch starts the container (image check/build + docker run) and
	// writes SSH config. Does NOT wait for SSH. Repos must have branches set.
	// Returns the container name assigned during launch.
	Launch(ctx context.Context, repos []md.Repo, labels []string, opts *StartOptions) (name string, err error)
	// Connect waits for SSH and pushes repos into the container identified
	// by name (returned by Launch). Returns the optional Tailscale FQDN and
	// browser auth URL (when no pre-auth key was available).
	Connect(ctx context.Context, name string, repos []md.Repo, opts *StartOptions) (tailscaleFQDN string, tailscaleAuthURL string, err error)
	Diff(ctx context.Context, repo *md.Repo, args ...string) (string, error)
	Fetch(ctx context.Context, repos []md.Repo) error
	// Stop gracefully stops the container without removing it. The container
	// can be restarted later with Revive.
	Stop(ctx context.Context, name string) error
	// Purge stops and removes the container identified by name, cleaning up
	// SSH config and git remotes for the given repos.
	Purge(ctx context.Context, name string, repos []md.Repo) error
	// Revive restarts a stopped (exited) container, re-establishes SSH, and
	// waits for connectivity. The container's filesystem is preserved.
	Revive(ctx context.Context, name string, repos []md.Repo) error
	// Fork snapshots a running container and creates a new one where each
	// mapped repo is checked out on a new branch derived from the current
	// state. Branch names are generated by the container backend.
	// repos are the source container's repos (used to reconstruct the container handle).
	// Returns the forked container name and new repos (with branches set).
	Fork(ctx context.Context, name string, repos []md.Repo, opts *ForkOptions) (forkName string, forkRepos []md.Repo, err error)
	// VNCPort returns the Docker host port mapped to the container's VNC
	// port (5901). Returns 0 when the container has no display.
	VNCPort(ctx context.Context, containerName string) int

	// Processes returns the list of running processes inside the container.
	Processes(ctx context.Context, containerName string) ([]ProcessInfo, error)
	// Signal sends a signal (e.g. SIGTERM, SIGKILL) to a process inside the container.
	Signal(ctx context.Context, containerName string, pid int, sig string) error
}

// ForkOptions holds parameters for forking a container.
type ForkOptions struct {
	ExtraRepos []md.Repo // Additional repos to map into the fork beyond the source's repos.
	Display    bool      // Inherit or enable X11/VNC.
	Tailscale  bool      // Inherit or enable Tailscale.
	USB        bool      // Inherit or enable USB.
	Sudo       bool      // Inherit or enable root access (password-based sudo).
	Labels     []string
	Harness    agent.Harness
	ExtraEnv   []string  // KEY=VALUE pairs for ~/.env.
	MaxCPUs    int       // Max CPU cores; 0 means use the default.
	LogWriter  io.Writer // Provisioning log output.
}

// Result holds the outcome of a completed task.
type Result struct {
	State       State
	DiffStat    agent.DiffStat
	CostUSD     float64
	Duration    time.Duration
	NumTurns    int
	Usage       agent.Usage
	AgentResult string
	Err         error
}

// Runner manages the serialization of setup and push operations.
type Runner struct {
	BaseBranch            string
	Dir                   string              // Absolute path to the git repository.
	RepoName              string              // Relative repo path (e.g. "github/caic"); empty for no-repo runners.
	GitTimeout            time.Duration       // Timeout for git/container ops; defaults to 1 minute.
	ContainerStartTimeout time.Duration       // Timeout for container start (image pull); defaults to 1 hour.
	LogDir                string              // Directory for raw JSONL session logs (required).
	CacheDir              string              // Cache directory (e.g. ~/.cache/caic) for harness model lists.
	HarnessEnv            map[string][]string // Per-harness KEY=VALUE env vars for containers.

	// Container provides md container lifecycle operations. Must be set before
	// calling Start.
	Container ContainerBackend
	// Backends maps harness names to their Backend implementations. The runner
	// selects the backend matching Task.Harness.
	Backends map[agent.Harness]agent.Backend

	log      *slog.Logger
	initOnce sync.Once
	branchMu sync.Mutex // Serializes branch creation (nextID + git branch) to avoid duplicate names.
	nextID   int        // Next branch sequence number (protected by branchMu).
}

// provisioningWriter is an io.Writer that converts line-by-line output from the
// container backend into LogMessage events stored on the task for SSE streaming.
type provisioningWriter struct {
	ctx context.Context
	t   *Task
	buf []byte
}

func (w *provisioningWriter) Write(p []byte) (int, error) {
	w.buf = append(w.buf, p...)
	for {
		i := bytes.IndexByte(w.buf, '\n')
		if i < 0 {
			break
		}
		line := strings.TrimSpace(string(w.buf[:i]))
		w.buf = w.buf[i+1:]
		if line != "" {
			w.t.addMessage(w.ctx, &agent.LogMessage{Line: line}, false)
		}
	}
	return len(p), nil
}

// writeLogTrailer appends a MetaResultMessage to the log file.
func writeLogTrailer(w io.Writer, title string, res *Result) {
	if w == nil {
		return
	}
	mr := agent.MetaResultMessage{
		MessageType:              "caic_result",
		State:                    res.State.String(),
		Title:                    title,
		CostUSD:                  res.CostUSD,
		Duration:                 res.Duration.Seconds(),
		NumTurns:                 res.NumTurns,
		InputTokens:              res.Usage.InputTokens,
		OutputTokens:             res.Usage.OutputTokens,
		CacheCreationInputTokens: res.Usage.CacheCreationInputTokens,
		CacheReadInputTokens:     res.Usage.CacheReadInputTokens,
		DiffStat:                 res.DiffStat,
		AgentResult:              res.AgentResult,
	}
	if res.Err != nil {
		mr.Error = res.Err.Error()
	}
	if data, err := json.Marshal(mr); err == nil {
		_, _ = w.Write(append(data, '\n'))
	}
}

// writeContextCleared appends a context_cleared system message to the log.
// Called before closing the old log writer in RestartSession so that
// RestoreMessages can reset plan state on server restart.
func writeContextCleared(w io.Writer) {
	msg := syntheticContextCleared()
	if data, err := json.Marshal(msg); err == nil {
		_, _ = w.Write(append(data, '\n'))
	}
}

// maxBranchSeqNum finds the highest sequence number N among all branches
// (local and remote) matching "caic-N". Returns -1 if no matching branches
// exist. Checking both local and remote is necessary because stopped tasks
// leave local branches that may never be pushed.
func maxBranchSeqNum(ctx context.Context, dir string) (int, error) {
	cmd := exec.CommandContext(ctx, "git", "branch", "-a", "--format=%(refname:short)")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return -1, fmt.Errorf("git branch -a: %w", err)
	}
	highest := -1
	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		// Match "caic-N" (local) or "<remote>/caic-N" (remote).
		// Use strings.Cut on "/caic-" for remote refs and
		// strings.HasPrefix for local refs to avoid matching unrelated
		// branch names that happen to contain "caic-".
		var numStr string
		if strings.HasPrefix(line, "caic-") {
			numStr = line[len("caic-"):]
		} else if _, after, ok := strings.Cut(line, "/caic-"); ok {
			numStr = after
		} else {
			continue
		}
		n, err := strconv.Atoi(numStr)
		if err != nil {
			continue
		}
		if n > highest {
			highest = n
		}
	}
	return highest, nil
}

// Init sets nextID past any existing caic-* branches so that restarts don't
// waste attempts on branches that already exist. No-op for no-repo runners.
func (r *Runner) Init(ctx context.Context) error {
	r.initDefaults()
	if r.Dir == "" {
		return nil
	}
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer cancel()
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	highest, err := maxBranchSeqNum(ctx, r.Dir)
	if err != nil {
		return err
	}
	if highest >= r.nextID {
		r.nextID = highest + 1
	}
	return nil
}

// Reconnect reattaches to a running relay, or starts a new agent session
// resuming the previous conversation if no relay is available. Returns the
// SessionHandle so the caller can start a session watcher.
//
// Strategy:
//  1. Check if the relay daemon is alive (Unix socket exists in container).
//  2. If alive, attach to the relay. This is the preferred path because it
//     reconnects to the still-running agent process with zero message loss.
//  3. If attaching fails (relay died between check and attach), fall back to
//     starting a new agent session with --resume to continue the conversation.
//  4. If both fail, revert to StateWaiting so the user can retry or purge.
//
// State transitions:
//   - Relay attach: keeps StateWaiting/StateAsking if agent already finished its
//     turn; transitions to StateRunning only if the agent was mid-output.
//   - --resume fallback: always transitions to StateRunning since a new agent
//     process is started.
//   - All-fail: reverts to StateWaiting.
func (r *Runner) Reconnect(ctx context.Context, t *Task, skipSideEffects bool) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.reconnect:"+t.ID.String())
	defer task.End()

	if t.HasSession() {
		return nil, errors.New("session already active")
	}
	if t.Container == "" {
		return nil, errors.New("no container to reconnect to")
	}
	// Remember the state inferred from restored messages so we don't
	// blindly override it to StateRunning for an idle relay.
	prevState := t.GetState()

	msgCh, dispatchDone := r.startMessageDispatch(ctx, t, skipSideEffects)

	// Reconnect resumes an existing session, so append to its log without
	// writing a new caic_meta header — otherwise every server restart that
	// re-adopts a running container would append a duplicate header. Fall
	// back to openLog (which writes the header) only if the log is missing.
	logW, err := r.reopenLog(t)
	if errors.Is(err, os.ErrNotExist) {
		logW, err = r.openLog(t)
	}
	if err != nil {
		close(msgCh)
		<-dispatchDone
		return nil, err
	}

	// Attach to the live relay. If the relay is dead, the session is lost.
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	// Only transition to StateRunning if the restored messages indicate
	// the agent was still producing output (no trailing ResultMessage).
	// If the agent had already completed its turn, keep the inferred
	// StateWaiting/StateAsking so the UI shows the correct status.
	if prevState != StateWaiting && prevState != StateAsking {
		t.SetState(StateRunning)
	}
	session, err := r.backend(t.Harness).AttachRelay(ctx, &agent.Options{
		Container:       t.Container,
		RelayOffset:     t.RelayOffset,
		ResumeSessionID: t.GetSessionID(),
		Effort:          t.Effort,
		MsgCh:           msgCh,
		LogW:            logW,
	})
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		t.SetState(StateWaiting)
		r.log.Error("attach relay failed", "br", primaryBranch, "ctr", t.Container, "err", err)
		return nil, fmt.Errorf("reconnect: %w", err)
	}

	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)
	return h, nil
}

// Start performs branch/container setup, starts the agent session, and sends
// the initial prompt. Returns the SessionHandle so the caller can start a
// session watcher.
//
// Sequence:
//  1. Create a new git branch from origin/<BaseBranch> (or the local branch if not on origin).
//  2. Start an md container on that branch.
//  3. Deploy the relay script and launch the agent (claude/gemini) via the
//     relay daemon. The relay owns the agent's stdin/stdout and persists
//     across SSH disconnects.
//  4. Send the initial prompt to the agent.
//
// The session is left open for follow-up messages via SendInput.
func (r *Runner) Start(ctx context.Context, t *Task, resolvedGitHubToken string) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.start:"+t.ID.String())
	defer task.End()

	if r.Container == nil {
		return nil, errors.New("runner has no container backend configured")
	}
	if r.Dir != "" {
		t.SetState(StateBranching)
	}

	tStart := time.Now()
	// 1. Create branch (serialized) + start container (concurrent).
	r.log.Info("setup task")
	region := trace.StartRegion(ctx, "setup")
	sr, err := r.setup(ctx, t, MakeLabels(t), resolvedGitHubToken)
	region.End()
	if err != nil {
		t.SetState(StateFailed)
		return nil, err
	}
	t.Container = sr.Container
	t.TailscaleFQDN = sr.TailscaleFQDN
	t.TailscaleAuthURL = sr.TailscaleAuthURL
	t.VNCPort = r.Container.VNCPort(ctx, sr.Container)
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	r.log.Info("runner", "msg", "ready", "br", primaryBranch, "ctr", t.Container, "dur", time.Since(tStart))

	// 2. Start the agent session.
	t.SetState(StateStarting)
	var msgCh chan agent.Message
	var dispatchDone <-chan struct{}
	var logW io.WriteCloser
	{
		region := trace.StartRegion(ctx, "dispatch-init")
		msgCh, dispatchDone = r.startMessageDispatch(ctx, t, false)
		logW, err = r.openLog(t)
		region.End()
	}
	if err != nil {
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		return nil, err
	}

	tSession := time.Now()
	tlog := r.log.With("br", primaryBranch, "ctr", t.Container)
	tlog.Info("starting session", "hns", t.Harness)
	region = trace.StartRegion(ctx, "agent-session")
	session, err := r.backend(t.Harness).Start(ctx, &agent.Options{
		Container:     t.Container,
		Dir:           r.containerDir(t),
		Model:         t.Model,
		Effort:        t.Effort,
		InitialPrompt: t.InitialPrompt,
		MsgCh:         msgCh,
		LogW:          logW,
	})
	region.End()
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		tlog.Error("session start failed", "err", err)
		return nil, err
	}

	// Store handle so SendInput can reach it.
	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)

	t.addMessage(ctx, syntheticUserInput(t.InitialPrompt), false)
	// Use SetStateIf so that a fast agent subprocess that already
	// produced a result (and was processed by the dispatch goroutine
	// via addMessage) isn't overwritten back to Running.
	t.SetStateIf(StateStarting, StateRunning)
	tlog.Info("agent running", "session_dur", time.Since(tSession), "total_startup_dur", time.Since(tStart))
	return h, nil
}

// Cleanup is the single shutdown path for a task (Flow 1 in the relay
// shutdown protocol — see package agent). It sends the null-byte sentinel
// to trigger graceful agent exit, then purges the container.
//
// This is only called for intentional purge (user action or container
// death), never during backend restart. On restart, the relay daemon stays
// alive and the server reconnects via adoptOne → Reconnect.
//
// Steps:
//  1. Detach the session handle from the task.
//  2. If a session exists: Stop (sends \x00, waits up to 20s), then Close.
//  3. Set task state to reason (StatePurged or StateFailed).
//  4. Purge the container (stop + remove + cleanup git remotes/SSH config).
//  5. If graceful wait timed out, drain session now (container dead, SSH severed).
//  6. Close msgCh and logW, write log trailer.
//  7. Build and return Result.
func (r *Runner) Cleanup(ctx context.Context, t *Task, reason State) Result {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.cleanup:"+t.ID.String())
	defer task.End()

	start := time.Now()
	name := t.Container
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	tlog := r.log.With("br", primaryBranch, "ctr", name)
	tlog.InfoContext(ctx, "cleanup starting", "reason", reason, "state", t.GetState(), "has_session", t.HasSession())

	h := t.DetachSession()

	// Graceful shutdown: send stop sentinel so the relay sends SIGINT.
	// Stats come from live accumulators updated by startMessageDispatch.
	if h != nil {
		tlog.DebugContext(ctx, "cleanup: sending graceful stop")
		gStart := time.Now()
		if err := h.GracefulStop(ctx, 20*time.Second); err != nil {
			tlog.WarnContext(ctx, "graceful stop timed out", "err", err, "dur", time.Since(gStart).Round(time.Millisecond))
			r.logRelayDiag(ctx, tlog, name)
		} else {
			tlog.DebugContext(ctx, "cleanup: graceful stop succeeded", "dur", time.Since(gStart).Round(time.Millisecond))
		}
	}

	t.SetState(reason)

	if name != "" && r.Container != nil {
		tlog.InfoContext(ctx, "cleanup: purging container")
		pStart := time.Now()
		if err := r.PurgeContainer(ctx, name, primaryBranch, t.ExtraMDRepos()); err != nil {
			tlog.WarnContext(ctx, "purge container failed", "err", err, "dur", time.Since(pStart).Round(time.Millisecond))
		} else {
			tlog.DebugContext(ctx, "cleanup: container purged", "dur", time.Since(pStart).Round(time.Millisecond))
		}
	} else {
		tlog.DebugContext(ctx, "cleanup: no container to purge", "name", name, "has_backend", r.Container != nil)
	}

	// Drain the session: if graceful stop timed out, the container purge
	// above severed SSH so this unblocks.
	if h != nil {
		dStart := time.Now()
		h.Drain()
		tlog.DebugContext(ctx, "cleanup: session drained", "dur", time.Since(dStart).Round(time.Millisecond))
	}

	res := Result{
		State:       reason,
		AgentResult: t.LastAgentResult(),
	}
	if liveCost, liveTurns, liveDur, liveUsage, _ := t.LiveStats(); liveCost > 0 {
		res.CostUSD = liveCost
		res.NumTurns = liveTurns
		res.Duration = liveDur
		res.Usage = liveUsage
	}
	if ds := t.LiveDiffStat(); len(ds) > 0 {
		res.DiffStat = ds
	}
	var logW io.WriteCloser
	if h != nil {
		logW = h.LogW
	} else {
		// Task was stopped before purge: the session handle (and its LogW) was
		// released by StopTask. Reopen the log for appending so we can write
		// the caic_result trailer; without it the task would load as "failed"
		// on the next server restart instead of "purged".
		tlog.DebugContext(ctx, "cleanup: no session handle, reopening log for trailer")
		var reopenErr error
		logW, reopenErr = r.reopenLog(t)
		if reopenErr != nil {
			tlog.WarnContext(ctx, "reopen log for trailer failed", "err", reopenErr)
		}
	}
	writeLogTrailer(logW, t.Title(), &res)
	if logW != nil {
		_ = logW.Close()
		tlog.DebugContext(ctx, "cleanup: log trailer written and closed")
	}
	tlog.InfoContext(ctx, "cleanup done", "dur", time.Since(start).Round(time.Millisecond),
		"cost", res.CostUSD, "turns", res.NumTurns, "reason", reason)
	return res
}

// StopTask gracefully shuts down the agent session and stops the container
// without removing it. The container can be revived later. Unlike Cleanup,
// this preserves git remotes and SSH config.
func (r *Runner) StopTask(ctx context.Context, t *Task) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.stop:"+t.ID.String())
	defer task.End()

	start := time.Now()
	name := t.Container
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	tlog := r.log.With("br", primaryBranch, "ctr", name)
	tlog.InfoContext(ctx, "stop starting", "state", t.GetState())

	h := t.DetachSession()

	// Graceful shutdown: send stop sentinel so the relay sends SIGINT.
	if h != nil {
		tlog.DebugContext(ctx, "stop: sending graceful stop")
		gStart := time.Now()
		if err := h.GracefulStop(ctx, 20*time.Second); err != nil {
			tlog.WarnContext(ctx, "graceful stop timed out", "err", err, "dur", time.Since(gStart).Round(time.Millisecond))
			r.logRelayDiag(ctx, tlog, name)
		} else {
			tlog.DebugContext(ctx, "stop: graceful stop succeeded", "dur", time.Since(gStart).Round(time.Millisecond))
		}
	}

	t.SetState(StateStopping)

	tlog.InfoContext(ctx, "stop: stopping container")
	if name != "" && r.Container != nil {
		cStart := time.Now()
		if err := r.Container.Stop(ctx, name); err != nil {
			tlog.WarnContext(ctx, "stop: container Stop failed", "err", err, "dur", time.Since(cStart).Round(time.Millisecond))
		} else {
			tlog.DebugContext(ctx, "stop: container Stop succeeded", "dur", time.Since(cStart).Round(time.Millisecond))
		}
	} else {
		tlog.DebugContext(ctx, "stop: no container to stop", "name", name, "has_backend", r.Container != nil)
	}

	// Drain session after container is stopped, then wait for the dispatch
	// goroutine to finish processing all buffered messages so that t.msgs
	// is complete before the state transitions to StateStopped.
	if h != nil {
		dStart := time.Now()
		h.Drain()
		tlog.DebugContext(ctx, "stop: session drained", "dur", time.Since(dStart).Round(time.Millisecond))
	}

	t.SetState(StateStopped)

	// Write log trailer so the task reloads as "stopped" (not "failed")
	// after a server restart, preserving live stats for the UI.
	res := Result{State: StateStopped, AgentResult: t.LastAgentResult()}
	if liveCost, liveTurns, liveDur, liveUsage, _ := t.LiveStats(); liveCost > 0 {
		res.CostUSD = liveCost
		res.NumTurns = liveTurns
		res.Duration = liveDur
		res.Usage = liveUsage
	}
	if ds := t.LiveDiffStat(); len(ds) > 0 {
		res.DiffStat = ds
	}
	var logW io.WriteCloser
	if h != nil {
		logW = h.LogW
	}
	writeLogTrailer(logW, t.Title(), &res)
	if logW != nil {
		_ = logW.Close()
	}
	tlog.InfoContext(ctx, "stop done", "dur", time.Since(start).Round(time.Millisecond),
		"cost", res.CostUSD, "turns", res.NumTurns)
}

// ReviveTask restarts a stopped container and resumes the agent session.
// The container's filesystem is preserved from the previous run. After
// docker-start + SSH, a new relay is started with --resume to continue
// the previous session.
func (r *Runner) ReviveTask(ctx context.Context, t *Task) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.revive:"+t.ID.String())
	defer task.End()

	if r.Container == nil {
		return nil, errors.New("runner has no container backend configured")
	}
	if t.Container == "" {
		return nil, errors.New("no container to revive")
	}
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	tlog := r.log.With("br", primaryBranch, "ctr", t.Container)

	// 1. Revive the container (docker start + SSH).
	t.SetState(StateProvisioning)
	repos := t.MDRepos()
	tlog.Info("reviving container")
	tlog.Debug("runner", "msg", "calling container.Revive", "repos_count", len(repos))
	if err := r.Container.Revive(ctx, t.Container, repos); err != nil {
		tlog.Error("runner", "msg", "Revive failed", "err", err)
		t.SetState(StateFailed)
		return nil, fmt.Errorf("revive container: %w", err)
	}
	tlog.Debug("runner", "msg", "Revive succeeded", "container", t.Container)
	t.VNCPort = r.Container.VNCPort(ctx, t.Container)

	// 2. Start a new relay with --resume to continue the previous session.
	// skipSideEffects=true: --resume replays all historical messages and
	// each would trigger fetch+diff+title if side effects were enabled.
	// Instead we do a single BranchDiffStat at the end.
	t.SetState(StateStarting)
	tlog.Info("resuming session after revive", "sess", t.GetSessionID())

	msgCh, dispatchDone := r.startMessageDispatch(ctx, t, true)
	logW, err := r.openLog(t)
	if err != nil {
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		return nil, fmt.Errorf("open log: %w", err)
	}

	t.SetState(StateRunning)
	session, err := r.backend(t.Harness).Start(ctx, &agent.Options{
		Container:       t.Container,
		Dir:             r.containerDir(t),
		Model:           t.Model,
		Effort:          t.Effort,
		ResumeSessionID: t.GetSessionID(),
		MsgCh:           msgCh,
		LogW:            logW,
	})
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		return nil, fmt.Errorf("resume session after revive: %w", err)
	}

	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)

	// 3. If --resume exits immediately (previous session was complete),
	// start a fresh idle relay so the task can accept new prompts.
	h, err = r.EnsureSession(ctx, t, h, tlog)
	if err != nil {
		t.SetState(StateFailed)
		return nil, err
	}

	// 4. Compute host-side diff stat once.
	if ds := r.BranchDiffStat(ctx, t.MDRepos()); len(ds) > 0 {
		t.SetLiveDiffStat(ds)
	}
	tlog.Info("agent ready after revive", "state", t.GetState())
	return h, nil
}

// EnsureSession waits briefly for h to confirm it's alive. If the session
// exits within 10 seconds (agent had already finished), it detaches and
// starts a fresh idle relay so the task can accept new prompts.
func (r *Runner) EnsureSession(ctx context.Context, t *Task, h *SessionHandle, tlog *slog.Logger) (*SessionHandle, error) {
	select {
	case <-h.Session.Done():
		// Session exited immediately (agent was already done).
		t.DetachSession()
		err := h.Session.Wait()
		h.CloseMsgCh()
		<-h.DispatchDone
		_ = h.LogW.Close()
		tlog.Info("attached session exited, starting idle relay", "err", err)
		if s := t.GetState(); s == StateStopping || s == StateStopped || s == StatePurged {
			return nil, fmt.Errorf("task is %s", s)
		}
		t.SetState(StateWaiting)
		return r.StartSession(ctx, t, agent.Prompt{})
	case <-time.After(10 * time.Second):
		// Session is alive — all good.
		return h, nil
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// StartSession starts a fresh relay+agent session on an existing container.
// If prompt is non-empty, it is sent as the initial input and the task
// transitions to StateRunning. If prompt is empty, the agent starts idle
// and the task stays in its current state (typically StateWaiting).
func (r *Runner) StartSession(ctx context.Context, t *Task, prompt agent.Prompt) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.start-session:"+t.ID.String())
	defer task.End()

	if t.Container == "" {
		return nil, errors.New("no container")
	}
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	tlog := r.log.With("br", primaryBranch, "ctr", t.Container)

	msgCh, dispatchDone := r.startMessageDispatch(ctx, t, false)
	logW, err := r.openLog(t)
	if err != nil {
		close(msgCh)
		<-dispatchDone
		return nil, err
	}

	tlog.Info("starting session", "hns", t.Harness)
	session, err := r.backend(t.Harness).Start(ctx, &agent.Options{
		Container:     t.Container,
		Dir:           r.containerDir(t),
		Model:         t.Model,
		Effort:        t.Effort,
		InitialPrompt: prompt,
		MsgCh:         msgCh,
		LogW:          logW,
	})
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		tlog.Error("session start failed", "err", err)
		return nil, err
	}

	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)
	if prompt.Text != "" || len(prompt.Images) > 0 {
		t.addMessage(ctx, syntheticUserInput(prompt), false)
		t.SetState(StateRunning)
	}
	return h, nil
}

// ForkTask snapshots the source task's container and starts an idle agent
// session in the forked container. The new task must already have its ID,
// Harness, Model, and other immutable fields set. The method fills in
// Container, Repos[*].Branch, and starts the session.
func (r *Runner) ForkTask(ctx context.Context, source, fork *Task, forkOpts *ForkOptions, resolvedGitHubToken string) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.fork:"+source.ID.String()+"->"+fork.ID.String())
	defer task.End()

	if r.Container == nil {
		return nil, errors.New("runner has no container backend configured")
	}
	if source.Container == "" {
		return nil, errors.New("source task has no container")
	}

	var sourcePrimaryBranch string
	if p := source.Primary(); p != nil {
		sourcePrimaryBranch = p.Branch
	}
	tlog := r.log.With("src_br", sourcePrimaryBranch, "src_ctr", source.Container)

	// 1. Fork the container. Branch names are generated by md.
	fork.SetState(StateProvisioning)
	tlog.Info("forking container")
	tlog.Debug("runner", "msg", "calling container.Fork", "source", source.Container, "harness", forkOpts.Harness, "tailscale", forkOpts.Tailscale, "usb", forkOpts.USB, "display", forkOpts.Display, "sudo", forkOpts.Sudo, "gitHubToken", fork.GitHubToken)
	forkOpts.LogWriter = &provisioningWriter{ctx: ctx, t: fork}
	forkName, forkRepos, err := r.Container.Fork(ctx, source.Container, source.MDRepos(), forkOpts)
	if err != nil {
		tlog.Error("runner", "msg", "container.Fork failed", "source", source.Container, "err", err)
		fork.SetState(StateFailed)
		return nil, fmt.Errorf("fork container: %w", err)
	}
	tlog.Debug("runner", "msg", "container.Fork succeeded", "source", source.Container, "fork", forkName)
	fork.Container = forkName
	fork.VNCPort = r.Container.VNCPort(ctx, forkName)
	for i := range fork.Repos {
		if i < len(forkRepos) {
			fork.Repos[i].Branch = forkRepos[i].Branch
		}
	}
	tlog.Info("fork container ready", "ctr", forkName)

	// 2. Clean relay state from the source container's snapshot so the
	// forked task starts with an empty output.jsonl.
	if err := agent.CleanRelayState(ctx, forkName); err != nil {
		tlog.Warn("clean relay state failed (non-fatal)", "err", err)
	}

	// 3. Start a fresh agent session with the fork prompt.
	// No --resume: the fork gets its own session ID and clean message history.
	fork.SetState(StateStarting)
	h, err := r.StartSession(ctx, fork, fork.InitialPrompt)
	if err != nil {
		fork.SetState(StateFailed)
		return nil, fmt.Errorf("start session on fork: %w", err)
	}
	tlog.Info("fork session running", "ctr", forkName)
	return h, nil
}

// setupResult holds the outputs of setup: the container name and optional Tailscale FQDN.
// The primary branch is written directly into t.Repos[0].Branch during setup.
type setupResult struct {
	Container        string
	TailscaleFQDN    string
	TailscaleAuthURL string
}

// AllocateBranch allocates a caic-N branch for this runner's repo using the
// runner's base branch. Used by the server to allocate branches for extra repos
// before starting a container.
func (r *Runner) AllocateBranch(ctx context.Context) (string, error) {
	r.initDefaults()
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	return r.allocateBranchLocked(ctx, &Task{})
}

// SyncToOrigin pushes each repo's task branch to origin and returns the
// combined diff stat across all repos and any safety issues found. Safety is
// checked per-repo; when force is false, issues in any repo block the push.
func (r *Runner) SyncToOrigin(ctx context.Context, repos []md.Repo, container string, force bool) (agent.DiffStat, []SafetyIssue, error) {
	r.initDefaults()
	if r.Dir == "" {
		return nil, nil, errors.New("sync is not supported for no-repo tasks")
	}
	region := trace.StartRegion(ctx, "sync-fetch")
	fetchCtx, fetchCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer fetchCancel()
	r.branchMu.Lock()
	r.log.Info("fetch", "repos", len(repos))
	if err := r.Container.Fetch(fetchCtx, repos); err != nil {
		r.branchMu.Unlock()
		region.End()
		return nil, nil, err
	}
	ds := r.diffStat(fetchCtx, repos)
	r.branchMu.Unlock()
	region.End()

	// Phase 1: safety check each repo, collect all issues.
	multi := len(repos) > 1
	var allIssues []SafetyIssue
	for _, repo := range repos {
		branch := repo.Branch
		ref := "refs/remotes/" + container + "/" + branch
		repoDS := extractRepoDS(ds, repo.MountedPath, multi)
		safetyCtx, safetyCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
		issues, err := CheckSafety(safetyCtx, repo.GitRoot, ref, r.BaseBranch, repoDS)
		safetyCancel()
		if err != nil {
			return ds, allIssues, fmt.Errorf("safety check %s: %w", repo.MountedPath, err)
		}
		allIssues = append(allIssues, issues...)
	}
	if len(allIssues) > 0 && !force {
		return ds, allIssues, nil
	}

	// Phase 2: push each repo.
	for _, repo := range repos {
		branch := repo.Branch
		ref := "refs/remotes/" + container + "/" + branch
		pushCtx, pushCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
		if err := gitutil.PushRef(pushCtx, repo.GitRoot, ref, branch, true); err != nil {
			pushCancel()
			return ds, allIssues, fmt.Errorf("push %s to origin: %w", repo.MountedPath, err)
		}
		pushCancel()
	}
	return ds, allIssues, nil
}

// extractRepoDS filters the combined diff stat to entries belonging to repoName,
// stripping the name prefix. When multi is false (single repo), ds is returned
// unchanged since no prefix was applied.
func extractRepoDS(ds agent.DiffStat, repoName string, multi bool) agent.DiffStat {
	if !multi {
		return ds
	}
	prefix := repoName + "/"
	var result agent.DiffStat
	for _, f := range ds {
		if path, ok := strings.CutPrefix(f.Path, prefix); ok {
			f.Path = path
			result = append(result, f)
		}
	}
	return result
}

// SyncToDefault fetches changes from the container, runs safety checks per repo,
// and squash-pushes each repo's task branch onto its default branch. Safety
// issues always block (no force override). The commit message is built from the
// task title.
func (r *Runner) SyncToDefault(ctx context.Context, repos []md.Repo, container, message string) (agent.DiffStat, []SafetyIssue, error) {
	r.initDefaults()
	if r.Dir == "" {
		return nil, nil, errors.New("sync is not supported for no-repo tasks")
	}
	region := trace.StartRegion(ctx, "sync-default-fetch")
	fetchCtx, fetchCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer fetchCancel()
	r.branchMu.Lock()
	r.log.Info("fetch for default sync", "repos", len(repos))
	if err := r.Container.Fetch(fetchCtx, repos); err != nil {
		r.branchMu.Unlock()
		region.End()
		return nil, nil, err
	}
	ds := r.diffStat(fetchCtx, repos)
	r.branchMu.Unlock()
	region.End()

	// Phase 1: safety check each repo, collect all issues.
	multi := len(repos) > 1
	var allIssues []SafetyIssue
	for _, repo := range repos {
		branch := repo.Branch
		ref := "refs/remotes/" + container + "/" + branch
		repoDS := extractRepoDS(ds, repo.MountedPath, multi)
		safetyCtx, safetyCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
		issues, err := CheckSafety(safetyCtx, repo.GitRoot, ref, r.BaseBranch, repoDS)
		safetyCancel()
		if err != nil {
			return ds, allIssues, fmt.Errorf("safety check %s: %w", repo.MountedPath, err)
		}
		allIssues = append(allIssues, issues...)
	}
	if len(allIssues) > 0 {
		return ds, allIssues, nil
	}

	// Phase 2: squash each repo onto its default branch.
	for _, repo := range repos {
		branch := repo.Branch
		ref := "refs/remotes/" + container + "/" + branch
		squashCtx, squashCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
		if err := gitutil.SquashOnto(squashCtx, repo.GitRoot, ref, r.BaseBranch, message); err != nil {
			squashCancel()
			return ds, allIssues, fmt.Errorf("squash %s onto %s: %w", repo.MountedPath, r.BaseBranch, err)
		}
		squashCancel()
	}
	return ds, allIssues, nil
}

// RestartSession closes the current agent session and starts a fresh one in
// the same container with a new prompt. Returns the new SessionHandle so the
// caller can start a session watcher.
func (r *Runner) RestartSession(ctx context.Context, t *Task, prompt agent.Prompt) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.restart:"+t.ID.String())
	defer task.End()

	state := t.GetState()
	if state != StateWaiting && state != StateAsking && state != StateHasPlan {
		return nil, fmt.Errorf("cannot restart in state %s", state)
	}

	// 1. Close current session gracefully and persist a context_cleared
	// marker to the log so that RestoreMessages can reset plan state on
	// server restart. The marker must be written before closing the log.
	oldH := t.CloseAndDetachSession(ctx)
	if oldH != nil {
		oldH.CloseMsgCh()
		<-oldH.DispatchDone
		if oldH.LogW != nil {
			writeContextCleared(oldH.LogW)
			_ = oldH.LogW.Close()
		}
	}

	// 2. Clear in-memory messages (sends context_cleared to subscribers).
	t.ClearMessages(ctx)

	// 3. Open new log segment.
	logW, err := r.openLog(t)
	if err != nil {
		t.SetState(StateFailed)
		return nil, fmt.Errorf("open log: %w", err)
	}

	// 4. Start new session.
	t.SetState(StateStarting)

	msgCh, dispatchDone := r.startMessageDispatch(ctx, t, false)

	var restartBranch string
	if p := t.Primary(); p != nil {
		restartBranch = p.Branch
	}
	tlog := r.log.With("br", restartBranch, "ctr", t.Container)
	tlog.Info("restarting session", "hns", t.Harness)
	session, err := r.backend(t.Harness).Start(ctx, &agent.Options{
		Container:     t.Container,
		Dir:           r.containerDir(t),
		Model:         t.Model,
		Effort:        t.Effort,
		InitialPrompt: prompt,
		MsgCh:         msgCh,
		LogW:          logW,
	})
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		return nil, fmt.Errorf("start session: %w", err)
	}

	// 5. Store new handle.
	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)

	t.addMessage(ctx, syntheticUserInput(prompt), false)

	t.SetState(StateRunning)
	tlog.Info("session restarted")
	return h, nil
}

// ClearContextSession closes the current agent session and starts a fresh one
// in the same container without a prompt. The task transitions to StateWaiting
// so the user can send a new message when ready.
func (r *Runner) ClearContextSession(ctx context.Context, t *Task) (*SessionHandle, error) {
	r.initDefaults()
	ctx, task := trace.NewTask(ctx, "task.clear-context:"+t.ID.String())
	defer task.End()

	state := t.GetState()
	if state != StateWaiting && state != StateAsking && state != StateHasPlan {
		return nil, fmt.Errorf("cannot clear context in state %s", state)
	}

	// 1. Close current session and persist context_cleared marker.
	oldH := t.CloseAndDetachSession(ctx)
	if oldH != nil {
		oldH.CloseMsgCh()
		<-oldH.DispatchDone
		if oldH.LogW != nil {
			writeContextCleared(oldH.LogW)
			_ = oldH.LogW.Close()
		}
	}

	// 2. Clear in-memory messages.
	t.ClearMessages(ctx)

	// 3. Open new log segment.
	logW, err := r.openLog(t)
	if err != nil {
		t.SetState(StateFailed)
		return nil, fmt.Errorf("open log: %w", err)
	}

	// 4. Start new session with no initial prompt.
	t.SetState(StateStarting)

	msgCh, dispatchDone := r.startMessageDispatch(ctx, t, false)

	var clearBranch string
	if p := t.Primary(); p != nil {
		clearBranch = p.Branch
	}
	tlog := r.log.With("br", clearBranch, "ctr", t.Container)
	tlog.Info("clearing context", "hns", t.Harness)
	session, err := r.backend(t.Harness).Start(ctx, &agent.Options{
		Container: t.Container,
		Dir:       r.containerDir(t),
		Model:     t.Model,
		Effort:    t.Effort,
		MsgCh:     msgCh,
		LogW:      logW,
	})
	if err != nil {
		_ = logW.Close()
		close(msgCh)
		<-dispatchDone
		t.SetState(StateFailed)
		return nil, fmt.Errorf("start session: %w", err)
	}

	// 5. Store new handle. Task goes to Waiting (no prompt to run).
	h := &SessionHandle{Session: session, MsgCh: msgCh, DispatchDone: dispatchDone, LogW: logW}
	t.AttachSession(h)
	t.SetState(StateWaiting)
	tlog.Info("context cleared")
	return h, nil
}

// DiffContent returns the unified diff for the given repos, optionally filtered
// to a single file path. When there are multiple repos, file paths are prefixed
// with `<repoName>/` so the frontend can distinguish changes from different
// repos. Holds branchMu during fetch+diff.
func (r *Runner) DiffContent(ctx context.Context, repos []md.Repo, path string) (string, error) {
	r.initDefaults()
	if r.Dir == "" {
		return "", errors.New("diff is not supported for no-repo tasks")
	}
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer cancel()
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	var buf strings.Builder
	for i := range repos {
		repo := &repos[i]
		args := []string{}
		if path != "" {
			args = append(args, "--", path)
		}
		diff, err := r.Container.Diff(ctx, repo, args...)
		if err != nil {
			r.log.Warn("diff failed", "repo", repo.MountedPath, "br", repo.Branch, "err", err)
			continue
		}
		if diff == "" {
			continue
		}
		if len(repos) > 1 {
			diff = prependRepoToDiff(diff, repo.MountedPath)
		}
		buf.WriteString(diff)
	}
	return buf.String(), nil
}

// prependRepoToDiff prepends `<repoName>/` to file paths in a unified diff so
// that files from different repos are distinguishable when concatenated.
func prependRepoToDiff(diff, repoName string) string {
	lines := strings.Split(diff, "\n")
	for i, line := range lines {
		switch {
		case strings.HasPrefix(line, "diff --git "):
			line = strings.Replace(line, " a/", " a/"+repoName+"/", 1)
			line = strings.Replace(line, " b/", " b/"+repoName+"/", 1)
			lines[i] = line
		case strings.HasPrefix(line, "--- ") && !strings.HasPrefix(line, "--- /dev/null"):
			idx := strings.IndexByte(line, ' ') + 1
			lines[i] = line[:idx] + repoName + "/" + line[idx:]
		case strings.HasPrefix(line, "+++ ") && !strings.HasPrefix(line, "+++ /dev/null"):
			idx := strings.IndexByte(line, ' ') + 1
			lines[i] = line[:idx] + repoName + "/" + line[idx:]
		case strings.HasPrefix(line, "rename from "):
			lines[i] = "rename from " + repoName + "/" + line[12:]
		case strings.HasPrefix(line, "rename to "):
			lines[i] = "rename to " + repoName + "/" + line[10:]
		}
	}
	return strings.Join(lines, "\n")
}

// PurgeContainer stops and removes the md container identified by containerName,
// cleaning up any git remotes for repos associated with this runner.
func (r *Runner) PurgeContainer(ctx context.Context, containerName, branch string, extraRepos []md.Repo) error {
	r.initDefaults()
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer cancel()
	var repos []md.Repo
	if r.Dir != "" {
		rr := md.Repo{GitRoot: r.Dir, Branch: branch}
		if r.RepoName != "" {
			rr.MountedPath = "~/src/" + r.RepoName
		}
		repos = append([]md.Repo{rr}, extraRepos...)
	}
	return r.Container.Purge(ctx, containerName, repos)
}

// mutatingTools lists tool names whose execution may change files in the
// container, warranting a diff stat refresh after their result arrives.
var mutatingTools = map[string]struct{}{
	"Bash":         {},
	"Edit":         {},
	"Write":        {},
	"NotebookEdit": {},
}

// BranchDiffStat fetches from the container and returns the per-repo branch diff
// stat (md diff --numstat). Unlike the relay's diff_watcher which only tracks
// uncommitted changes, this captures the full branch diff relative to the base.
// Used by adoptOne to restore the diff stat after server restart.
func (r *Runner) BranchDiffStat(ctx context.Context, repos []md.Repo) agent.DiffStat {
	r.initDefaults()
	if r.Container == nil || r.Dir == "" {
		return nil
	}
	fetchCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer cancel()
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	if err := r.Container.Fetch(fetchCtx, repos); err != nil {
		r.log.Warn("fetch for branch diff stat failed", "err", err)
		return nil
	}
	return r.diffStat(fetchCtx, repos)
}

// initDefaults populates default Backends, timeout values, and the logger.
// Safe to call multiple times (sync.Once).
func (r *Runner) initDefaults() {
	r.initOnce.Do(func() {
		if r.Backends == nil {
			r.Backends = map[agent.Harness]agent.Backend{
				agent.Claude:   claudecode.New(),
				agent.Codex:    codex.New(),
				agent.OpenCode: opencode.New(r.CacheDir, r.HarnessEnv[string(agent.OpenCode)]),
				agent.Pi:       pi.New(r.CacheDir, r.HarnessEnv[string(agent.Pi)]),
			}
		}
		if r.GitTimeout == 0 {
			r.GitTimeout = time.Minute
		}
		if r.ContainerStartTimeout == 0 {
			r.ContainerStartTimeout = time.Hour
		}
		repoName := filepath.Base(r.Dir)
		if r.Dir == "" {
			repoName = "(none)"
		}
		r.log = slog.With("repo", repoName)
	})
}

// backend returns the Backend for the given agent name.
func (r *Runner) backend(name agent.Harness) agent.Backend {
	return r.Backends[name]
}

// containerDir returns the working directory path inside an md container.
// Uses the task's primary repo MountedPath when available; otherwise falls back
// to computing it from the runner's Dir basename (legacy). Returns /home/user
// for no-repo runners.
//
// TODO(2026-07-01): remove the filepath.Base fallback once all pre-MountedPath
// containers have cycled out.
func (r *Runner) containerDir(t *Task) string {
	if p := t.Primary(); p != nil && p.MountedPath != "" {
		return strings.Replace(p.MountedPath, "~/", "/home/user/", 1)
	}
	if r.Dir == "" {
		return "/home/user"
	}
	return "/home/user/src/" + filepath.Base(r.Dir)
}

// allocateBranchLocked fetches origin, resolves the start point, and creates
// the task branch. Must be called under branchMu.
func (r *Runner) allocateBranchLocked(ctx context.Context, t *Task) (string, error) {
	detached := context.WithoutCancel(ctx)
	gitCtx, gitCancel := context.WithTimeout(detached, r.GitTimeout)
	defer gitCancel()
	// Fetch so that origin/<base> is up to date.
	if err := gitutil.Fetch(gitCtx, r.Dir); err != nil {
		return "", fmt.Errorf("fetch: %w", err)
	}
	// Resolve effective base branch: use task override if provided.
	effectiveBase := r.BaseBranch
	if p := t.Primary(); p != nil && p.BaseBranch != "" {
		effectiveBase = p.BaseBranch
	}
	// Prefer the remote tracking ref, but fall back to the local branch when
	// the base branch only exists locally (not yet pushed to origin).
	startPoint := "origin/" + effectiveBase
	if _, err := gitutil.RevParse(gitCtx, r.Dir, startPoint); err != nil {
		startPoint = effectiveBase
	}
	// Assign a sequential branch name, skipping existing ones.
	var branch string
	var err error
	for range 100 {
		if gitCtx.Err() != nil {
			return "", gitCtx.Err()
		}
		branch = fmt.Sprintf("caic-%d", r.nextID)
		r.nextID++
		r.log.Info("creating branch", "br", branch, "base", effectiveBase)
		err = gitutil.CreateBranch(gitCtx, r.Dir, branch, startPoint)
		if err == nil {
			break
		}
	}
	if err != nil {
		return "", fmt.Errorf("create branch: %w", err)
	}
	return branch, nil
}

// fetchAndCreateBranch fetches origin and creates the given branch from the
// resolved base. Acquires branchMu to serialize git operations across concurrent
// task setups on the same repo.
func (r *Runner) fetchAndCreateBranch(ctx context.Context, t *Task, branch string) error {
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	gitCtx, gitCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer gitCancel()
	if err := gitutil.Fetch(gitCtx, r.Dir); err != nil {
		return fmt.Errorf("fetch: %w", err)
	}
	effectiveBase := r.BaseBranch
	if p := t.Primary(); p != nil && p.BaseBranch != "" {
		effectiveBase = p.BaseBranch
	}
	startPoint := "origin/" + effectiveBase
	if _, err := gitutil.RevParse(gitCtx, r.Dir, startPoint); err != nil {
		startPoint = effectiveBase
	}
	r.log.Info("creating branch", "br", branch, "base", effectiveBase)
	if err := gitutil.CreateBranch(gitCtx, r.Dir, branch, startPoint); err != nil {
		return fmt.Errorf("create branch: %w", err)
	}
	return nil
}

// MakeLabels builds Docker labels for a task's container.
// The plain "caic" label is kept alongside "caic.id" for backward
// compatibility with the Docker event watcher (watchContainerEvents
// filters on label=caic). Once all old containers have cycled out,
// both WatchEvents and the adoption fallback can be updated to use
// "caic.id" exclusively, and this duplicate label can be removed.
// TODO(2026-07-01): remove the plain "caic" label and update WatchEvents to filter on caic.id.
func MakeLabels(t *Task) []string {
	labels := []string{
		"caic.id=" + t.ID.String(),
		"caic=" + t.ID.String(), // backward compat with WatchEvents
		"caic.harness=" + string(t.Harness),
	}
	if t.GitHubToken {
		labels = append(labels, "caic.githubToken=true")
	}
	return labels
}

// setup reserves a branch name, starts the container (Phase A) and creates the
// git branch concurrently, then completes container startup (Phase B).
// Phase A (docker run) and git fetch+branch-create overlap, cutting the
// branch-allocation time off the critical path.
func (r *Runner) setup(ctx context.Context, t *Task, labels []string, resolvedGitHubToken string) (setupResult, error) {
	// Reserve the branch ID instantly (under lock, ~µs). The branch itself is
	// created concurrently with docker run in Phase A.
	if r.Dir != "" {
		r.branchMu.Lock()
		t.Repos[0].Branch = fmt.Sprintf("caic-%d", r.nextID)
		r.nextID++
		r.branchMu.Unlock()
	}

	t.SetState(StateProvisioning)
	detached := context.WithoutCancel(ctx)
	var primaryBranch string
	if p := t.Primary(); p != nil {
		primaryBranch = p.Branch
	}
	r.log.Info("starting container", "br", primaryBranch, "img", t.DockerImage, "hns", t.Harness, "ts", t.Tailscale, "usb", t.USB, "dpy", t.Display, "sudo", t.Sudo, "gitHubToken", t.GitHubToken)
	tContainer := time.Now()
	startCtx, startCancel := context.WithTimeout(detached, r.ContainerStartTimeout)
	defer startCancel()

	opts := &StartOptions{
		DockerImage: t.DockerImage, Harness: t.Harness, Tailscale: t.Tailscale, USB: t.USB, Display: t.Display, Sudo: t.Sudo,
		MaxCPUs:     t.MaxCPUs,
		GitHubToken: resolvedGitHubToken,
		LogWriter:   &provisioningWriter{ctx: ctx, t: t},
	}

	// Phase A: docker run + SSH config. Branch creation runs concurrently so
	// git fetch overlaps with the container SSH boot time (~500 ms–3 s).
	var repos []md.Repo
	if r.Dir != "" {
		repos = t.MDRepos()
	}
	var containerName string
	r.log.Debug("runner", "msg", "provisioning phase A: launching container and creating branch", "harness", opts.Harness, "tailscale", opts.Tailscale, "usb", opts.USB, "display", opts.Display, "sudo", opts.Sudo, "repos_count", len(repos))
	eg, egCtx := errgroup.WithContext(startCtx)
	eg.Go(func() error {
		defer trace.StartRegion(egCtx, "container-launch").End()
		r.log.Debug("runner", "msg", "calling container.Launch", "branch", primaryBranch)
		name, err := r.Container.Launch(egCtx, repos, labels, opts)
		if err != nil {
			r.log.Error("runner", "msg", "container.Launch failed", "branch", primaryBranch, "err", err)
			return err
		}
		r.log.Debug("runner", "msg", "container.Launch succeeded", "container", name)
		containerName = name
		return nil
	})
	if r.Dir != "" {
		eg.Go(func() error {
			defer trace.StartRegion(egCtx, "branch-create").End()
			r.log.Debug("runner", "msg", "fetching and creating branch", "branch", primaryBranch)
			err := r.fetchAndCreateBranch(egCtx, t, primaryBranch)
			if err != nil {
				r.log.Error("runner", "msg", "fetchAndCreateBranch failed", "branch", primaryBranch, "err", err)
			} else {
				r.log.Debug("runner", "msg", "fetchAndCreateBranch succeeded", "branch", primaryBranch)
			}
			return err
		})
	}
	r.log.Debug("runner", "msg", "waiting for phase A errgroup")
	if err := eg.Wait(); err != nil {
		return setupResult{}, err
	}
	r.log.Debug("runner", "msg", "phase A complete", "container", containerName)

	// Phase B: wait for SSH + push (branch now exists locally).
	r.log.Debug("runner", "msg", "provisioning phase B: connecting via SSH", "container", containerName, "repos_count", len(repos))
	tailscaleFQDN, tailscaleAuthURL, err := r.Container.Connect(startCtx, containerName, repos, opts)
	if err != nil {
		r.log.Error("runner", "msg", "container.Connect failed", "container", containerName, "err", err)
		return setupResult{}, fmt.Errorf("start container: %w", err)
	}
	r.log.Info("runner", "msg", "started", "br", primaryBranch, "dur", time.Since(tContainer), "container", containerName, "fqdn", tailscaleFQDN)
	return setupResult{Container: containerName, TailscaleFQDN: tailscaleFQDN, TailscaleAuthURL: tailscaleAuthURL}, nil
}

// logRelayDiag reads the relay daemon's relay.log from the container and logs
// its tail. Called when GracefulStop times out to capture relay-side diagnostics.
func (r *Runner) logRelayDiag(ctx context.Context, tlog *slog.Logger, container string) {
	if r.Container == nil || container == "" {
		return
	}
	tail := agent.ReadRelayLog(ctx, container, 4096)
	if tail == "" {
		tlog.Warn("relay.log empty or unreadable")
		return
	}
	tlog.Warn("relay.log tail on shutdown timeout", "log", tail)
}

// startMessageDispatch starts a goroutine that reads from msgCh and dispatches
// to t.addMessage. For ResultMessages, it fetches from the container first and
// attaches the diff stat. For tool results following a mutating tool (Edit,
// Bash, Write, NotebookEdit), it also fetches and emits a DiffStatMessage.
// When skipSideEffects is true, fetch+diff and title generation are suppressed
// (used during adoption where these are handled once at the end).
// Returns the message channel and a done channel that closes when the
// goroutine exits (after msgCh is fully drained).
func (r *Runner) startMessageDispatch(ctx context.Context, t *Task, skipSideEffects bool) (msgCh chan agent.Message, dispatchDone <-chan struct{}) {
	// Capture all repos outside the goroutine to avoid races.
	allRepos := t.MDRepos()
	msgCh = make(chan agent.Message, 256)
	done := make(chan struct{})
	dispatchDone = done
	go func() {
		defer close(done)
		// Track tool_use IDs from ToolUseMessage that may mutate files.
		pendingMutating := make(map[string]struct{})
		for m := range msgCh {
			switch msg := m.(type) {
			case *agent.ToolUseMessage:
				if _, ok := mutatingTools[msg.Name]; ok {
					pendingMutating[msg.ToolUseID] = struct{}{}
				}
			case *agent.ToolResultMessage:
				if !skipSideEffects && r.Container != nil && r.Dir != "" {
					if _, ok := pendingMutating[msg.ToolUseID]; ok {
						delete(pendingMutating, msg.ToolUseID)
						r.fetchDiffStatBranch(ctx, t, allRepos)
					}
				}
			case *agent.ResultMessage:
				if !skipSideEffects && r.Container != nil && r.Dir != "" {
					fetchCtx, fetchCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
					r.branchMu.Lock()
					if err := r.Container.Fetch(fetchCtx, allRepos); err != nil {
						r.log.Warn("fetch on result failed", "err", err)
					}
					msg.DiffStat = r.diffStat(fetchCtx, allRepos)
					r.branchMu.Unlock()
					fetchCancel()
				}
			}
			t.addMessage(ctx, m, skipSideEffects)
		}
	}()
	return msgCh, dispatchDone
}

// fetchDiffStatBranch fetches from the container and emits a DiffStatMessage
// into the task's message stream. Used after mutating tool results to keep the
// live diff stat up to date across all repos.
func (r *Runner) fetchDiffStatBranch(ctx context.Context, t *Task, repos []md.Repo) {
	fetchCtx, fetchCancel := context.WithTimeout(context.WithoutCancel(ctx), r.GitTimeout)
	defer fetchCancel()
	r.branchMu.Lock()
	defer r.branchMu.Unlock()
	if err := r.Container.Fetch(fetchCtx, repos); err != nil {
		r.log.Warn("fetch on tool result failed", "err", err)
		return
	}
	ds := r.diffStat(fetchCtx, repos)
	if len(ds) == 0 {
		return
	}
	t.addMessage(ctx, &agent.DiffStatMessage{
		MessageType: "caic_diff_stat",
		DiffStat:    ds,
	}, false)
}

// diffStat runs Diff("--numstat") on each repo and returns the combined diff
// stat. File paths are prefixed with `<repoName>/` when there are multiple repos
// so the frontend can distinguish changes per repo.
func (r *Runner) diffStat(ctx context.Context, repos []md.Repo) agent.DiffStat {
	if r.Dir == "" {
		return nil
	}
	var result agent.DiffStat
	for i := range repos {
		repo := &repos[i]
		numstat, err := r.Container.Diff(ctx, repo, "--numstat")
		if err != nil {
			r.log.Warn("diff numstat failed", "repo", repo.MountedPath, "br", repo.Branch, "err", err)
			continue
		}
		ds := ParseDiffNumstat(numstat)
		if len(repos) > 1 {
			for i := range ds {
				ds[i].Path = repo.MountedPath + "/" + ds[i].Path
			}
		}
		result = append(result, ds...)
	}
	return result
}

// openLog creates a JSONL log file in LogDir and writes a metadata header as
// the first line.
func (r *Runner) openLog(t *Task) (io.WriteCloser, error) {
	if err := os.MkdirAll(r.LogDir, 0o750); err != nil {
		return nil, fmt.Errorf("create log dir: %w", err)
	}
	safeRepo := ""
	safeBranch := ""
	if p := t.Primary(); p != nil {
		safeRepo = strings.ReplaceAll(p.Name, "/", "-")
		safeBranch = strings.ReplaceAll(p.Branch, "/", "-")
	}
	name := t.ID.String() + "-" + safeRepo + "-" + safeBranch + ".jsonl"
	f, err := os.OpenFile(filepath.Join(r.LogDir, name), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600) //nolint:gosec // name is derived from ksid, not arbitrary user input.
	if err != nil {
		return nil, fmt.Errorf("create log file: %w", err)
	}
	// Write metadata header as the first line.
	metaRepos := make([]agent.MetaRepo, len(t.Repos))
	for i, r := range t.Repos {
		metaRepos[i] = agent.MetaRepo{Name: r.Name, BaseBranch: r.BaseBranch, Branch: r.Branch, MountedPath: r.MountedPath}
	}
	meta := agent.MetaMessage{
		MessageType: "caic_meta",
		Version:     1,
		Prompt:      t.InitialPrompt.Text,
		Title:       t.Title(),
		Repos:       metaRepos,
		Harness:     t.Harness,
		Model:       t.Model,
		Effort:      t.Effort,
		StartedAt:   t.StartedAt,
		ForgeIssue:  t.ForgeIssue,
		Tailscale:   t.Tailscale,
		USB:         t.USB,
		Display:     t.Display,
		Sudo:        t.Sudo,
		GitHubToken: t.GitHubToken,
	}
	if data, err := json.Marshal(meta); err == nil {
		_, _ = f.Write(append(data, '\n'))
	}
	return f, nil
}

// reopenLog opens an existing log file for appending without writing a new
// metadata header. Used by Cleanup to write the caic_result trailer for
// stopped tasks whose session handle has already been released.
func (r *Runner) reopenLog(t *Task) (io.WriteCloser, error) {
	if r.LogDir == "" {
		return nil, errors.New("no log dir")
	}
	safeRepo := ""
	safeBranch := ""
	if p := t.Primary(); p != nil {
		safeRepo = strings.ReplaceAll(p.Name, "/", "-")
		safeBranch = strings.ReplaceAll(p.Branch, "/", "-")
	}
	name := t.ID.String() + "-" + safeRepo + "-" + safeBranch + ".jsonl"
	return os.OpenFile(filepath.Join(r.LogDir, name), os.O_WRONLY|os.O_APPEND, 0o600) //nolint:gosec // name is derived from ksid, not arbitrary user input.
}

// writeLogTrailer appends a MetaResultMessage to the log file.
