// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };

//////////
// source: events.go
/*
SSE event types sent to the frontend for task event streams.
*/

export type EventKind =
  | "init"
  | "text"
  | "textDelta"
  | "toolUse"
  | "toolResult"
  | "ask"
  | "usage"
  | "result"
  | "system"
  | "userInput"
  | "todo"
  | "diffStat"
  | "error"
  | "thinking"
  | "thinkingDelta"
  | "subagentStart"
  | "subagentEnd"
  | "log"
  | "toolOutputDelta"
  | "widget"
  | "widgetDelta"
  | "rateLimit"
  | "stats";
/**
 * Supported values.
 */
export const EventKindInit: EventKind = "init";
export const EventKindText: EventKind = "text";
export const EventKindTextDelta: EventKind = "textDelta";
export const EventKindToolUse: EventKind = "toolUse";
export const EventKindToolResult: EventKind = "toolResult";
export const EventKindAsk: EventKind = "ask";
export const EventKindUsage: EventKind = "usage";
export const EventKindResult: EventKind = "result";
export const EventKindSystem: EventKind = "system";
export const EventKindUserInput: EventKind = "userInput";
export const EventKindTodo: EventKind = "todo";
export const EventKindDiffStat: EventKind = "diffStat";
export const EventKindError: EventKind = "error";
export const EventKindThinking: EventKind = "thinking";
export const EventKindThinkingDelta: EventKind = "thinkingDelta";
export const EventKindSubagentStart: EventKind = "subagentStart";
export const EventKindSubagentEnd: EventKind = "subagentEnd";
export const EventKindLog: EventKind = "log";
export const EventKindToolOutputDelta: EventKind = "toolOutputDelta";
export const EventKindWidget: EventKind = "widget";
export const EventKindWidgetDelta: EventKind = "widgetDelta";
export const EventKindRateLimit: EventKind = "rateLimit";
export const EventKindStats: EventKind = "stats";

export type ToolOutputContentType =
  | "text"
  | "json"
  | "markdown";
/**
 * Supported values.
 */
export const ToolOutputText: ToolOutputContentType = "text";
export const ToolOutputJSON: ToolOutputContentType = "json";
export const ToolOutputMarkdown: ToolOutputContentType = "markdown";

/**
 * EventInit is emitted once at the start of a session. It includes a Harness
 * field so the client knows which backend produced the stream.
 */
export interface EventInit {
  model: string;
  /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty when not supported. */
  effort?: string;
  agentVersion: string;
  sessionID: string;
  tools?: string[];
  cwd: string;
  harness: string;
}

/** EventText is an assistant text block. */
export interface EventText {
  text: string;
}

/** EventTextDelta is a streaming text fragment from --include-partial-messages. */
export interface EventTextDelta {
  text: string;
}

/** EventToolUse is emitted when the assistant invokes a tool. */
export interface EventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
  /** Snapshot of plan content for ExitPlanMode events. */
  planContent?: string;
  /** True when Input was omitted due to size; fetch via GET /api/v1/tasks/{id}/tool/{toolUseID}. */
  inputTruncated?: boolean;
  /** True when the tool runs in the background (Bash/Agent run_in_background). */
  background?: boolean;
}

/** EventToolResult is emitted when a tool call completes. */
export interface EventToolResult {
  toolUseID: string;
  /** Seconds; server-computed; 0 if unknown. */
  duration: number /* float64 */;
  error?: string;
}

/** AskOption is a single option in an AskUserQuestion. */
export interface AskOption {
  label: string;
  description?: string;
}

/** AskQuestion is a single question from AskUserQuestion. */
export interface AskQuestion {
  question: string;
  header?: string;
  options: AskOption[];
  multiSelect?: boolean;
}

/** EventAsk is emitted when the agent asks the user a question. */
export interface EventAsk {
  toolUseID: string;
  questions: AskQuestion[];
}

/**
 * EventUsage reports per-turn token usage.
 * ReasoningOutputTokens is a subset of OutputTokens for extended thinking (Claude)
 * or reasoning summaries (Codex). Zero when the harness does not report it.
 */
export interface EventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  reasoningOutputTokens?: number /* int */;
  model: string;
}

/** EventResult is emitted when the task reaches a terminal state. */
export interface EventResult {
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  /** Seconds. */
  duration: number /* float64 */;
  /** Seconds. */
  durationAPI: number /* float64 */;
  numTurns: number /* int */;
  usage: EventUsage;
}

/** EventSystem is a system event (status, compact_boundary, etc.). */
export interface EventSystem {
  subtype: string;
  /** Optional human-readable detail (e.g. model names for model_rerouted). */
  detail?: string;
}

/** EventUserInput is emitted when a user sends a text message to the agent. */
export interface EventUserInput {
  text: string;
  images?: ImageData[];
}

/** TodoItem is a single todo entry from a TodoWrite tool call. */
export interface TodoItem {
  content: string;
  /** "pending", "in_progress", "completed". */
  status: string;
  activeForm?: string;
}

/** EventTodo is emitted when the agent writes/updates its todo list. */
export interface EventTodo {
  toolUseID: string;
  todos: TodoItem[];
}

/** EventDiffStat is emitted when the relay reports updated diff statistics. */
export interface EventDiffStat {
  diffStat?: DiffStat;
}

/** EventError is emitted when the backend fails to parse an agent output line. */
export interface EventError {
  err: string;
  line: string;
}

/** EventThinking is an assistant thinking block. */
export interface EventThinking {
  text: string;
}

/** EventThinkingDelta is a streaming thinking fragment. */
export interface EventThinkingDelta {
  text: string;
}

/** EventSubagentStart is emitted when a subagent task begins. */
export interface EventSubagentStart {
  taskID: string;
  description: string;
}

/** EventSubagentEnd is emitted when a subagent task completes, fails, or stops. */
export interface EventSubagentEnd {
  taskID: string;
  /** "completed", "failed", "stopped" */
  status: string;
}

/** EventLog is a provisioning/startup log line from the runtime backend. */
export interface EventLog {
  line: string;
}

/**
 * EventToolOutputDelta is a streaming output fragment from a running tool.
 * Codex only: emitted for Bash stdout (item/commandExecution/outputDelta) and
 * MCP tool progress messages (item/mcpToolCall/progress).
 */
export interface EventToolOutputDelta {
  toolUseID: string;
  delta: string;
  contentType?: ToolOutputContentType;
  /** Pretty-printed JSON or other transformation. */
  formatted?: string;
}

/** EventWidget is emitted when the agent produces a complete HTML widget. */
export interface EventWidget {
  toolUseID: string;
  title: string;
  html: string;
}

/** EventWidgetDelta is a streaming HTML fragment for progressive widget rendering. */
export interface EventWidgetDelta {
  toolUseID: string;
  delta: string;
}

/** EventRateLimit is emitted when the agent's rate limit status changes. */
export interface EventRateLimit {
  /** "allowed", "allowed_warning", "rejected". */
  status: string;
  /** When the limit resets; zero if unknown. */
  resetsAt?: ISOTimestamp;
  /** "five_hour", "seven_day", etc. */
  rateLimitType: string;
  /** 0.0–1.0. */
  utilization: number /* float64 */;
  /** True when extra/overage usage is active. */
  isUsingOverage?: boolean;
  /** When overage resets; zero if not using overage. */
  overageResetsAt?: ISOTimestamp;
}

/** EventStats is a runtime resource usage snapshot emitted periodically. */
export interface EventStats {
  ts: number /* int64 */;
  cpuPerc: number /* float64 */;
  memUsed: number /* uint64 */;
  memLimit: number /* uint64 */;
  memPerc: number /* float64 */;
  netRx: number /* uint64 */;
  netTx: number /* uint64 */;
  blockRead: number /* uint64 */;
  blockWrite: number /* uint64 */;
  diskUsed: number /* int64 */;
}

/**
 * EventMessage is a single SSE event in the backend-neutral stream
 * (/api/v1/tasks/{id}/events). All backends produce these events.
 */
export interface EventMessage {
  kind: EventKind;
  ts: number /* int64 */;
  init?: EventInit;
  text?: EventText;
  textDelta?: EventTextDelta;
  toolUse?: EventToolUse;
  toolResult?: EventToolResult;
  ask?: EventAsk;
  usage?: EventUsage;
  result?: EventResult;
  system?: EventSystem;
  userInput?: EventUserInput;
  todo?: EventTodo;
  diffStat?: EventDiffStat;
  error?: EventError;
  thinking?: EventThinking;
  thinkingDelta?: EventThinkingDelta;
  subagentStart?: EventSubagentStart;
  subagentEnd?: EventSubagentEnd;
  log?: EventLog;
  toolOutputDelta?: EventToolOutputDelta;
  widget?: EventWidget;
  widgetDelta?: EventWidgetDelta;
  rateLimit?: EventRateLimit;
  stats?: EventStats;
}


//////////
// source: types.go

export type CIStatus =
  | "pending"
  | "success"
  | "failure";
/**
 * Supported values.
 */
export const CIStatusPending: CIStatus = "pending";
export const CIStatusSuccess: CIStatus = "success";
export const CIStatusFailure: CIStatus = "failure";

export type CheckConclusion =
  | "success"
  | "failure"
  | "neutral"
  | "skipped"
  | "cancelled"
  | "timed_out"
  | "action_required"
  | "stale";
/**
 * Supported values.
 */
export const CheckConclusionSuccess: CheckConclusion = "success";
export const CheckConclusionFailure: CheckConclusion = "failure";
export const CheckConclusionNeutral: CheckConclusion = "neutral";
export const CheckConclusionSkipped: CheckConclusion = "skipped";
export const CheckConclusionCancelled: CheckConclusion = "cancelled";
export const CheckConclusionTimedOut: CheckConclusion = "timed_out";
export const CheckConclusionActionRequired: CheckConclusion = "action_required";
export const CheckConclusionStale: CheckConclusion = "stale";

export type CheckStatus =
  | "queued"
  | "in_progress"
  | "completed";
/**
 * Supported values.
 */
export const CheckStatusQueued: CheckStatus = "queued";
export const CheckStatusInProgress: CheckStatus = "in_progress";
export const CheckStatusCompleted: CheckStatus = "completed";

export type Forge =
  | "github"
  | "gitlab";
/**
 * Supported values.
 */
export const ForgeGitHub: Forge = "github";
export const ForgeGitLab: Forge = "gitlab";

export type ForgePRState =
  | "open"
  | "closed"
  | "merged";
/**
 * Supported values.
 */
export const ForgePRStateOpen: ForgePRState = "open";
export const ForgePRStateClosed: ForgePRState = "closed";
export const ForgePRStateMerged: ForgePRState = "merged";

export type Harness =
  | "claude"
  | "codex"
  | "gemini"
  | "kilo"
  | "opencode"
  | "pi";
/**
 * Supported values.
 */
export const HarnessClaude: Harness = "claude";
export const HarnessCodex: Harness = "codex";
export const HarnessGemini: Harness = "gemini";
export const HarnessKilo: Harness = "kilo";
export const HarnessOpenCode: Harness = "opencode";
export const HarnessPi: Harness = "pi";

export type SyncTarget =
  | "branch"
  | "default";
/**
 * Supported values.
 */
export const SyncTargetBranch: SyncTarget = "branch";
export const SyncTargetDefault: SyncTarget = "default";

export type TaskState =
  | "pending"
  | "branching"
  | "provisioning"
  | "starting"
  | "running"
  | "waiting"
  | "asking"
  | "has_plan"
  | "pulling"
  | "pushing"
  | "stopping"
  | "stopped"
  | "purging"
  | "failed"
  | "purged";
/**
 * Supported values.
 */
export const TaskStatePending: TaskState = "pending";
export const TaskStateBranching: TaskState = "branching";
export const TaskStateProvisioning: TaskState = "provisioning";
export const TaskStateStarting: TaskState = "starting";
export const TaskStateRunning: TaskState = "running";
export const TaskStateWaiting: TaskState = "waiting";
export const TaskStateAsking: TaskState = "asking";
export const TaskStateHasPlan: TaskState = "has_plan";
export const TaskStatePulling: TaskState = "pulling";
export const TaskStatePushing: TaskState = "pushing";
export const TaskStateStopping: TaskState = "stopping";
export const TaskStateStopped: TaskState = "stopped";
export const TaskStatePurging: TaskState = "purging";
export const TaskStateFailed: TaskState = "failed";
export const TaskStatePurged: TaskState = "purged";

export type VoiceGatewayMode =
  | "disabled"
  | "embedded"
  | "external";
/**
 * Supported values.
 */
export const VoiceGatewayModeDisabled: VoiceGatewayMode = "disabled";
export const VoiceGatewayModeEmbedded: VoiceGatewayMode = "embedded";
export const VoiceGatewayModeExternal: VoiceGatewayMode = "external";

/** DiffStat summarises the changes in a branch relative to its base. */
export type DiffStat = DiffFileStat[];

/** VoiceGatewayMetadata reports structured voice gateway support. */
export interface VoiceGatewayMetadata {
  mode: VoiceGatewayMode;
  url?: string;
  minGatewayProtocol?: number /* int */;
  authRequired?: boolean;
  tokenEndpoint?: string;
  tokenAudience?: string;
  capabilities?: string[];
}

/** Config reports server capabilities to the frontend. */
export interface Config {
  version?: string;
  displayName: string;
  tailscaleAvailable: boolean;
  usbAvailable: boolean;
  displayAvailable: boolean;
  sudoAvailable: boolean;
  gitHubTokenAvailable: boolean;
  voiceGateway: VoiceGatewayMetadata;
  gitHubAppEnabled?: boolean;
  /** e.g. ["github","gitlab"] */
  authProviders?: string[];
}

/** VersionResp is the response for GET /api/v1/server/version. */
export interface VersionResp {
  current: string;
  /** empty when check failed */
  latest?: string;
  /** true when Latest > Current */
  updateAvailable: boolean;
  /** non-empty when the GitHub check failed */
  checkError?: string;
  /** true when autoupdate schedule is configured */
  autoUpdateEnabled: boolean;
}

/** UpdateResp is the response for POST /api/v1/server/update. */
export interface UpdateResp {
  /** "started" or "already_up_to_date" */
  status: string;
}

/** UserResp is returned by GET /api/v1/auth/me. */
export interface UserResp {
  id: string;
  provider: string;
  username: string;
  avatarURL?: string;
}

/** StatusResp is a common response for mutation endpoints. */
export interface StatusResp {
  status: string;
}

/** RepoPrefsResp holds per-repository preferences. */
export interface RepoPrefsResp {
  path: string;
  baseBranch?: string;
  harness?: string;
  model?: string;
}

/** CacheMappingResp represents a directory mapping for cache/state sharing. */
export interface CacheMappingResp {
  hostPath: string;
  containerPath: string;
}

/** MountMappingResp represents a general host-to-runtime directory mount. */
export interface MountMappingResp {
  hostPath: string;
  containerPath: string;
}

/** UserSettings holds user-configurable behavioral settings. */
export interface UserSettings {
  /**
   * AutoFixOnCIFailure automatically starts a new task to fix CI when a
   * task's PR CI fails and the original task can no longer receive input.
   * Only effective when the GitHub App is configured.
   */
  autoFixOnCIFailure: boolean;
  /**
   * AutoFixOnPROpen automatically creates a task to review and fix a pull
   * request when it is opened or reopened via a forge webhook.
   */
  autoFixOnPROpen: boolean;
  /**
   * BaseImage overrides the default runtime base image. Empty means use
   * the default.
   */
  baseImage?: string;
  /**
   * MaxCPUs limits the number of CPU cores the runtime instance may use.
   * Zero means use the system default (max(2, NumCPU-2)).
   */
  maxCPUs?: number /* int */;
  /**
   * UseDefaultCaches controls whether default harness caches are mounted.
   * When false, only custom cache mappings and custom mounts are used.
   */
  useDefaultCaches: boolean;
  /**
   * WellKnownCaches maps cache name to enabled state. nil means use default
   * (all true), true means explicitly enabled, false means explicitly disabled.
   */
  wellKnownCaches?: { [key: string]: boolean};
  /** CacheMappings are custom host-to-runtime directory mappings. */
  cacheMappings?: CacheMappingResp[];
  /** CustomMounts are custom non-cache host-to-runtime directory mappings. */
  customMounts?: MountMappingResp[];
}

/** PreferencesResp is the response for GET /api/v1/server/preferences. */
export interface PreferencesResp {
  repositories: RepoPrefsResp[];
  harness?: string;
  models?: { [key: string]: string};
  settings: UserSettings;
}

/** UpdatePreferencesReq is the request body for POST /api/v1/server/preferences. */
export interface UpdatePreferencesReq {
  settings: UserSettings;
}

/** HarnessInfo is the JSON representation of an available harness. */
export interface HarnessInfo {
  name: string;
  models: string[];
  supportsImages: boolean;
  supportsCompact: boolean;
}

/** WellKnownCache describes a single well-known cache. */
export interface WellKnownCache {
  name: string;
  description: string;
  /** List of runtime mount paths */
  mounts: string[];
}

/** WellKnownCachesResp is the response for GET /api/v1/server/caches. */
export interface WellKnownCachesResp {
  /** e.g. "~/.claude", "~/.codex" */
  harnessMounts: string[];
  wellKnown: WellKnownCache[];
}

/** BranchInfo describes a single branch with its origin. */
export interface BranchInfo {
  name: string;
  remote?: string;
}

/** ForgeCheck describes a CI check run with its status, conclusion, and timing. */
export interface ForgeCheck {
  name: string;
  owner: string;
  repo: string;
  /** Pipeline/workflow run ID. */
  runID: number /* int64 */;
  /** Check run / job ID. */
  jobID: number /* int64 */;
  /** queued, in_progress, completed. */
  status: CheckStatus;
  /** Empty when not completed. */
  conclusion: CheckConclusion;
  /** When the check was created/queued. */
  queuedAt?: ISOTimestamp;
  /** When execution began. */
  startedAt?: ISOTimestamp;
  /** When execution finished. */
  completedAt?: ISOTimestamp;
}

/** Repo is the JSON representation of a discovered repo. */
export interface Repo {
  path: string;
  branch: string;
  baseBranch: BranchInfo;
  remoteURL?: string;
  /** "github", "gitlab", or empty if unknown. */
  forge?: Forge;
  ci?: CIStatus;
  ciChecks?: ForgeCheck[];
  checksDate?: ISOTimestamp;
}

/** CloneRepoReq is the request body for POST /api/v1/server/repos. */
export interface CloneRepoReq {
  /** Git clone URL (HTTPS or SSH). */
  url: string;
  /** Target subdirectory under rootDir; defaults to repo basename. */
  path?: string;
  depth?: number /* int */;
}

/** RepoBranchesResp is the response for GET /api/v1/server/repos/branches. */
export interface RepoBranchesResp {
  branches: BranchInfo[];
}

/**
 * BotFixCIReq is the request body for POST /api/v1/bot/fix-ci.
 * The server fetches CI logs, builds a prompt, and creates a fix task.
 */
export interface BotFixCIReq {
  repo: string;
}

/** CreateTaskResp is the response for POST /api/v1/tasks. */
export interface CreateTaskResp {
  status: string;
  id: string;
}

/**
 * BotFixPRReq is the request body for POST /api/v1/bot/fix-pr.
 * The server fetches CI logs for the task's PR and injects a fix command.
 */
export interface BotFixPRReq {
  taskId: string;
}

/** TaskRepo describes a repository associated with a task in the API response. */
export interface TaskRepo {
  name: string;
  baseBranch?: string;
  branch: string;
  remoteURL?: string;
  /** "github", "gitlab", or empty if unknown. */
  forge?: Forge;
}

/** DiffFileStat describes changes to a single file. */
export interface DiffFileStat {
  path: string;
  added: number /* int */;
  deleted: number /* int */;
  binary?: boolean;
}

/** RuntimeInstance holds per-task runtime metadata. */
export interface RuntimeInstance {
  /** Runtime instance ID. */
  id: string;
  /** Tailscale URL (https://fqdn) or "true" if enabled but FQDN unknown. */
  tailscale?: string;
  usb?: boolean;
  display?: boolean;
  sudo?: boolean;
  /** SudoPassword is the random sudo password, only populated when Sudo is true. */
  sudoPassword?: string;
  vncPort?: number /* int */;
}

/** Task is the JSON representation sent to the frontend. */
export interface Task {
  id: string;
  initialPrompt: string;
  title: string;
  repos?: TaskRepo[];
  state: TaskState;
  /** When the task state last changed. */
  stateUpdatedAt: ISOTimestamp;
  diffStat?: DiffStat;
  costUSD: number /* float64 */;
  /** Seconds. */
  duration: number /* float64 */;
  numTurns: number /* int */;
  cumulativeInputTokens: number /* int */;
  cumulativeOutputTokens: number /* int */;
  cumulativeCacheCreationInputTokens: number /* int */;
  cumulativeCacheReadInputTokens: number /* int */;
  /** Last turn's non-cached input tokens (including cache creation). */
  activeInputTokens: number /* int */;
  /** Last turn's cache-read input tokens. */
  activeCacheReadTokens: number /* int */;
  /** Effective cache TTL from last API call (seconds); 0 = unknown. */
  cacheTTLSeconds?: number /* int */;
  /** When the prompt cache expires. */
  cacheExpiresAt?: ISOTimestamp;
  /** Model context window limit (tokens). */
  contextWindowLimit: number /* int */;
  error?: string;
  result?: string;
  forgeOwner?: string;
  forgeRepo?: string;
  forgePR?: number /* int */;
  forgePRState?: ForgePRState;
  forgeIssue?: number /* int */;
  ciStatus?: CIStatus;
  ciChecks?: ForgeCheck[];
  /** username of creator; omitted in no-auth mode */
  owner?: string;
  /** Per-task harness/agent metadata. */
  harness: Harness;
  model?: string;
  /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty = default. */
  effort?: string;
  agentVersion?: string;
  sessionID?: string;
  /** When the task was created. */
  startedAt?: ISOTimestamp;
  /** When the current turn started; zero when not running. */
  turnStartedAt?: ISOTimestamp;
  inPlanMode?: boolean;
  planContent?: string;
  runtime: RuntimeInstance;
  /** Per-task feature flags. */
  gitHubToken?: boolean;
}

/** ImageData carries a single base64-encoded image. */
export interface ImageData {
  /** e.g. "image/png", "image/jpeg" */
  mediaType: string;
  /** base64-encoded */
  data: string;
}

/** Prompt bundles user text with optional images. */
export interface Prompt {
  text: string;
  images?: ImageData[];
}

/** RepoSpec describes a repository to associate with a task at creation time. */
export interface RepoSpec {
  name: string;
  baseBranch?: string;
}

/** CreateTaskReq is the request body for POST /api/v1/tasks. */
export interface CreateTaskReq {
  initialPrompt: Prompt;
  repos?: RepoSpec[];
  model?: string;
  /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty = default. */
  effort?: string;
  harness: Harness;
  tailscale?: boolean;
  usb?: boolean;
  display?: boolean;
  sudo?: boolean;
  gitHubToken?: boolean;
}

/** InputReq is the request body for POST /api/v1/tasks/{id}/input. */
export interface InputReq {
  prompt: Prompt;
}

/** RestartReq is the request body for POST /api/v1/tasks/{id}/restart. */
export interface RestartReq {
  prompt: Prompt;
}

/** CompactReq is the request body for POST /api/v1/tasks/{id}/compact. */
export interface CompactReq {
  instructions?: string;
}

/**
 * CILogResp is the response for GET /api/v1/tasks/{id}/ci-log.
 * It contains the name of the first failed CI step and its log tail.
 */
export interface CILogResp {
  stepName: string;
  log: string;
}

/** SyncReq is the request body for POST /api/v1/tasks/{id}/sync. */
export interface SyncReq {
  force?: boolean;
  target?: SyncTarget;
}

/** SafetyIssue describes a potential problem detected before pushing to origin. */
export interface SafetyIssue {
  file: string;
  /** "large_binary" or "secret" */
  kind: string;
  /** Human-readable description. */
  detail: string;
}

/** SyncResp is the response for POST /api/v1/tasks/{id}/sync. */
export interface SyncResp {
  /** "synced", "blocked", or "empty" */
  status: string;
  branch?: string;
  diffStat?: DiffStat;
  safetyIssues?: SafetyIssue[];
  /** non-zero if a PR/MR was created */
  prNumber?: number /* int */;
}

/** ForkTaskReq is the request body for POST /api/v1/tasks/{id}/fork. */
export interface ForkTaskReq {
  /** Initial prompt for the forked task. */
  prompt: Prompt;
  /** Override harness; empty means inherit from source. */
  harness?: Harness;
  /** Override model; empty means inherit from source. */
  model?: string;
  /** Override thinking effort; empty means inherit from source. */
  effort?: string;
  /** Additional repos to map into the fork. */
  extraRepos?: RepoSpec[];
  /** Override Tailscale; nil means inherit from source. */
  tailscale?: boolean;
  /** Override USB; nil means inherit from source. */
  usb?: boolean;
  /** Override virtual display; nil means inherit from source. */
  display?: boolean;
  /** Override sudo; nil means inherit from source. */
  sudo?: boolean;
  /** Override gitHubToken; nil means inherit from source. */
  gitHubToken?: boolean;
}

/** DiffResp is the response for GET /api/v1/tasks/{id}/diff. */
export interface DiffResp {
  diff: string;
}

/** ProcessInfo describes a single process running inside a task runtime instance. */
export interface ProcessInfo {
  pid: number /* int */;
  ppid: number /* int */;
  user: string;
  /** Single-character state: R, S, D, Z, T, etc. */
  state: string;
  cpu: number /* float64 */;
  mem: number /* float64 */;
  /** Cumulative CPU time. */
  time: string;
  /** Full command line. */
  command: string;
}

/** ProcessListResp is the response for GET /api/v1/tasks/{id}/processes. */
export interface ProcessListResp {
  processes: ProcessInfo[];
}

/** SignalProcessReq is the request body for POST /api/v1/tasks/{id}/processes/{pid}/signal. */
export interface SignalProcessReq {
  /** "SIGTERM" or "SIGKILL" */
  signal: string;
}

/**
 * TaskToolInputResp is the response for GET /api/v1/tasks/{id}/tool/{toolUseID}.
 * It returns the full (untruncated) input for a tool call.
 */
export interface TaskToolInputResp {
  toolUseID: string;
  input: any /* json.RawMessage */;
}

/**
 * TaskListEvent is a discriminated-union event for the task list SSE stream.
 * kind=="snapshot": Tasks holds the full list on initial connect.
 * kind=="upsert":   Task holds a newly created task.
 * kind=="patch":    Patch holds only the changed fields (always includes "id") for an existing task.
 * kind=="delete":   ID holds the string ID of the removed task.
 * kind=="repos":    Repos holds the updated repo list (emitted when default-branch CI status changes).
 * kind=="warning":  Warning holds a transient server warning message for the user.
 */
export interface TaskListEvent {
  kind: string;
  snapshot?: Task[];
  upsert?: Task;
  patch?: { [key: string]: any /* json.RawMessage */};
  delete?: string;
  repos?: Repo[];
  warning?: string;
}

/** QuotaRateLimit is a single rate-limit window snapshot from any provider. */
export interface QuotaRateLimit {
  /** "5h", "7d", "primary", "secondary", "rpm", "tpd", … */
  window: string;
  /** 0–100 */
  usedPct: number /* float64 */;
  /** zero when unknown */
  resetsAt?: ISOTimestamp;
}

/** QuotaBalance is a balance/credit snapshot from any provider. */
export interface QuotaBalance {
  /** "USD", "CNY", "credits", … */
  currency: string;
  /** total available balance */
  total: number /* float64 */;
  /** unexpired promotional/grant balance */
  granted?: number /* float64 */;
  /** self-funded recharge balance */
  toppedUp?: number /* float64 */;
}

/** QuotaExtraUsage is pay-as-you-go usage info (Anthropic-style extra credits). */
export interface QuotaExtraUsage {
  /** "USD", "CNY", … */
  currency: string;
  isEnabled: boolean;
  usedCredits: number /* float64 */;
  monthlyLimit: number /* float64 */;
  usedPct: number /* float64 */;
}

/** ProviderQuota is the quota data for one provider. */
export interface ProviderQuota {
  /** "anthropic", "deepseek", "gemini", "openai", "codex", "openrouter", … */
  provider: string;
  /** human-readable: "Anthropic", "DeepSeek", … */
  label: string;
  /** absolute URL path to provider SVG, e.g. "/logos/anthropic.svg" */
  logoUrl: string;
  /** "oauth" or "apikey" */
  authKind: string;
  /** link to provider's usage/billing page */
  usageUrl: string;
  rateLimits?: QuotaRateLimit[];
  balance?: QuotaBalance;
  extraUsage?: QuotaExtraUsage;
}

/** LocalWindow is the aggregated local cost for a rolling time window. */
export interface LocalWindow {
  /** "1h", "6h", "24h" */
  duration: string;
  costUSD: number /* float64 */;
  inputTokens: number /* int */;
  outputTokens: number /* int */;
}

/** LocalUsage is the aggregated cost across all tasks within recent time windows. */
export interface LocalUsage {
  windows: LocalWindow[];
}

/** UsageResp is the response for GET /api/v1/usage. */
export interface UsageResp {
  providers?: ProviderQuota[];
  local: LocalUsage;
}

/** VoiceTokenResp is the response for GET /api/v1/voice/token. */
export interface VoiceTokenResp {
  token: string;
  expiresAt: string;
  ephemeral: boolean;
}

/** WebFetchReq is the request body for POST /api/v1/web/fetch. */
export interface WebFetchReq {
  url: string;
}

/** WebFetchResp is the response for POST /api/v1/web/fetch. */
export interface WebFetchResp {
  title: string;
  content: string;
}

/** VoiceRTCOfferReq is the request body for POST /api/v1/voice/rtc/offer. */
export interface VoiceRTCOfferReq {
  sdp: string;
}

/** VoiceRTCAnswerResp is the response for POST /api/v1/voice/rtc/offer. */
export interface VoiceRTCAnswerResp {
  sdp: string;
  sessionID: string;
}

export interface ErrorDetails {
  code: string;
  message: string;
}

export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any /* json.RawMessage */};
}

