// Code generated by gen-api-sdk. DO NOT EDIT.
import Foundation

/// ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z").
public typealias ISOTimestamp = String

/// A Codable representation of an arbitrary JSON value.
public enum JSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let v = try? c.decode(Bool.self) { self = .bool(v); return }
        if let v = try? c.decode(Double.self) { self = .number(v); return }
        if let v = try? c.decode(String.self) { self = .string(v); return }
        if let v = try? c.decode([String: JSONValue].self) { self = .object(v); return }
        if let v = try? c.decode([JSONValue].self) { self = .array(v); return }
        throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown JSON value"))
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        case .array(let v): try c.encode(v)
        case .null: try c.encodeNil()
        }
    }
}

public enum ErrorCodes {
    public static let badRequest = "BAD_REQUEST"
    public static let unauthorized = "UNAUTHORIZED"
    public static let internalError = "INTERNAL_ERROR"
}

/// HealthResp is returned by GET /health.
public struct HealthResp: Codable {
    public let status: String
}

/// Compatibility is returned by GET /compat on the standalone voice gateway.
public struct Compatibility: Codable {
    public let service: String
    public let gatewayProtocol: Int
    public let serviceKinds: [String]
    public let capabilities: [String]
}

/// ServiceAuthorization authorizes one service-bound voice session.
public struct ServiceAuthorization: Codable {
    public let kind: String
    public let instanceID: String
    public let baseURL: String
    public let token: String
}

/// OfferReq starts a voice gateway WebRTC signaling session.
public struct OfferReq: Codable {
    public let protocolVersion: Int
    public let sdp: String
    public let service: ServiceAuthorization
}

/// OfferResp returns the WebRTC SDP answer and gateway session ID.
public struct OfferResp: Codable {
    public let sdp: String
    public let sessionID: String
}

/// CloseSessionResp is returned after closing a voice gateway session.
public struct CloseSessionResp: Codable {
    public let protocolVersion: Int
    public let status: String
}

/// ErrorDetails holds the code and message within an error response.
public struct ErrorDetails: Codable {
    public let code: String
    public let message: String
}

/// ErrorResponse is the JSON envelope for voice gateway error responses.
public struct ErrorResponse: Codable {
    public let error: ErrorDetails
    public let details: [String: JSONValue]?
}

