// Code generated by gen-api-sdk. DO NOT EDIT.
@file:UseSerializers(InstantSerializer::class)

package com.fghbuild.mcp.sdk.v1

import java.time.Instant
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

/** Serializes [Instant] as an ISO 8601 string. */
object InstantSerializer : KSerializer<Instant> {
    override val descriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

@Serializable(with = CacheScopeSerializer::class)
sealed interface CacheScope {
    val value: String
    @Serializable
    data object Public : CacheScope {
        override val value = "public"
    }
    @Serializable
    data object Private : CacheScope {
        override val value = "private"
    }
    @Serializable
    data class Other(override val value: String) : CacheScope
}

object CacheScopeSerializer : KSerializer<CacheScope> {
    override val descriptor = PrimitiveSerialDescriptor("CacheScope", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: CacheScope) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): CacheScope {
        val v = decoder.decodeString()
        return when (v) {
            "public" -> CacheScope.Public
            "private" -> CacheScope.Private
            else -> CacheScope.Other(v)
        }
    }
}

@Serializable(with = ContentTypeSerializer::class)
sealed interface ContentType {
    val value: String
    @Serializable
    data object Audio : ContentType {
        override val value = "audio"
    }
    @Serializable
    data object Image : ContentType {
        override val value = "image"
    }
    @Serializable
    data object Resource : ContentType {
        override val value = "resource"
    }
    @Serializable
    data object ResourceLink : ContentType {
        override val value = "resource_link"
    }
    @Serializable
    data object Text : ContentType {
        override val value = "text"
    }
    @Serializable
    data class Other(override val value: String) : ContentType
}

object ContentTypeSerializer : KSerializer<ContentType> {
    override val descriptor = PrimitiveSerialDescriptor("ContentType", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ContentType) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): ContentType {
        val v = decoder.decodeString()
        return when (v) {
            "audio" -> ContentType.Audio
            "image" -> ContentType.Image
            "resource" -> ContentType.Resource
            "resource_link" -> ContentType.ResourceLink
            "text" -> ContentType.Text
            else -> ContentType.Other(v)
        }
    }
}

@Serializable(with = MethodSerializer::class)
sealed interface Method {
    val value: String
    @Serializable
    data object ServerDiscover : Method {
        override val value = "server/discover"
    }
    @Serializable
    data object ToolsList : Method {
        override val value = "tools/list"
    }
    @Serializable
    data object ToolsCall : Method {
        override val value = "tools/call"
    }
    @Serializable
    data object ResourcesList : Method {
        override val value = "resources/list"
    }
    @Serializable
    data object ResourcesRead : Method {
        override val value = "resources/read"
    }
    @Serializable
    data object ResourceTemplatesList : Method {
        override val value = "resources/templates/list"
    }
    @Serializable
    data object SubscriptionsListen : Method {
        override val value = "subscriptions/listen"
    }
    @Serializable
    data class Other(override val value: String) : Method
}

object MethodSerializer : KSerializer<Method> {
    override val descriptor = PrimitiveSerialDescriptor("Method", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Method) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Method {
        val v = decoder.decodeString()
        return when (v) {
            "server/discover" -> Method.ServerDiscover
            "tools/list" -> Method.ToolsList
            "tools/call" -> Method.ToolsCall
            "resources/list" -> Method.ResourcesList
            "resources/read" -> Method.ResourcesRead
            "resources/templates/list" -> Method.ResourceTemplatesList
            "subscriptions/listen" -> Method.SubscriptionsListen
            else -> Method.Other(v)
        }
    }
}

@Serializable(with = ResultTypeSerializer::class)
sealed interface ResultType {
    val value: String
    @Serializable
    data object Complete : ResultType {
        override val value = "complete"
    }
    @Serializable
    data class Other(override val value: String) : ResultType
}

object ResultTypeSerializer : KSerializer<ResultType> {
    override val descriptor = PrimitiveSerialDescriptor("ResultType", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ResultType) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): ResultType {
        val v = decoder.decodeString()
        return when (v) {
            "complete" -> ResultType.Complete
            else -> ResultType.Other(v)
        }
    }
}

@Serializable(with = RoleSerializer::class)
sealed interface Role {
    val value: String
    @Serializable
    data object User : Role {
        override val value = "user"
    }
    @Serializable
    data object Assistant : Role {
        override val value = "assistant"
    }
    @Serializable
    data class Other(override val value: String) : Role
}

object RoleSerializer : KSerializer<Role> {
    override val descriptor = PrimitiveSerialDescriptor("Role", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Role) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Role {
        val v = decoder.decodeString()
        return when (v) {
            "user" -> Role.User
            "assistant" -> Role.Assistant
            else -> Role.Other(v)
        }
    }
}

object ErrorCodes {
}

/** JSONRPCRequest is a JSON-RPC request that expects a response. */
@Serializable
data class JSONRPCRequest(
    val jsonrpc: String,
    val id: JsonElement? = null,
    val method: Method,
    val params: JsonElement? = null,
)

/** JSONRPCError is a JSON-RPC error object. */
@Serializable
data class JSONRPCError(
    val code: Int,
    val message: String,
    val data: JsonElement? = null,
)

/** JSONRPCResponse is a JSON-RPC response containing either a result or an error. */
@Serializable
data class JSONRPCResponse(
    val jsonrpc: String,
    val id: JsonElement? = null,
    val result: JsonElement? = null,
    val error: JSONRPCError? = null,
)

/** PromptsCapability describes prompt support advertised by the server. */
@Serializable
data class PromptsCapability(val listChanged: Boolean? = null)

/** ResourcesCapability describes resource support advertised by the server. */
@Serializable
data class ResourcesCapability(val subscribe: Boolean? = null, val listChanged: Boolean? = null)

/** ToolsCapability describes tool support advertised by the server. */
@Serializable
data class ToolsCapability(val listChanged: Boolean? = null)

/** Capabilities describes server-supported MCP features. */
@Serializable
data class Capabilities(
    val experimental: Map<String, JsonElement>? = null,
    val logging: Map<String, JsonElement>? = null,
    val completions: Map<String, JsonElement>? = null,
    val prompts: PromptsCapability? = null,
    val resources: ResourcesCapability? = null,
    val tools: ToolsCapability? = null,
    val extensions: Map<String, JsonElement>? = null,
)

/** Icon describes an optionally-sized icon for UI display. */
@Serializable
data class Icon(
    val src: String,
    val mimeType: String? = null,
    val sizes: List<String>? = null,
    val theme: String? = null,
)

/** Implementation describes an MCP client or server implementation. */
@Serializable
data class Implementation(
    val icons: List<Icon>? = null,
    val name: String,
    val title: String? = null,
    val version: String,
    val description: String? = null,
    val websiteUrl: String? = null,
)

/** ServerDiscoverResult is the result returned for a server/discover request. */
@Serializable
data class ServerDiscoverResult(
    val resultType: ResultType,
    val supportedVersions: List<String>,
    val capabilities: Capabilities,
    val serverInfo: Implementation,
    val instructions: String? = null,
    val ttlMs: Int,
    val cacheScope: CacheScope,
)

/** SamplingCapability describes deprecated client sampling support. */
@Serializable
data class SamplingCapability(val context: Map<String, JsonElement>? = null, val tools: Map<String, JsonElement>? = null)

/** ElicitationCapability describes client elicitation support. */
@Serializable
data class ElicitationCapability(val form: Map<String, JsonElement>? = null, val url: Map<String, JsonElement>? = null)

/** ClientCapabilities describes capabilities the client supports for a request. */
@Serializable
data class ClientCapabilities(
    val experimental: Map<String, JsonElement>? = null,
    val roots: Map<String, JsonElement>? = null,
    val sampling: SamplingCapability? = null,
    val elicitation: ElicitationCapability? = null,
    val extensions: Map<String, JsonElement>? = null,
)

/** RequestMeta is the metadata object required in MCP request params. */
@Serializable
data class RequestMeta(
    @SerialName("io.modelcontextprotocol/protocolVersion") val protocolVersion: String,
    @SerialName("io.modelcontextprotocol/clientInfo") val clientInfo: Implementation,
    @SerialName("io.modelcontextprotocol/clientCapabilities") val clientCapabilities: ClientCapabilities,
    val progressToken: JsonElement? = null,
    @SerialName("io.modelcontextprotocol/logLevel") val deprecatedLogLevel: String? = null,
)

/** PaginatedRequestParams contains common request metadata and an optional cursor. */
@Serializable
data class PaginatedRequestParams(val _meta: RequestMeta, val cursor: String? = null)

/** ToolAnnotations describe MCP tool behavior hints. */
@Serializable
data class ToolAnnotations(
    val title: String? = null,
    val readOnlyHint: Boolean? = null,
    val destructiveHint: Boolean? = null,
    val idempotentHint: Boolean? = null,
    val openWorldHint: Boolean? = null,
)

/** ToolDescriptor describes a tool the client can call. */
@Serializable
data class ToolDescriptor(
    val _meta: Map<String, JsonElement>? = null,
    val icons: List<Icon>? = null,
    val name: String,
    val title: String? = null,
    val description: String? = null,
    val inputSchema: JsonElement? = null,
    val outputSchema: JsonElement? = null,
    val annotations: ToolAnnotations? = null,
)

/** ToolsListResult is the response payload for tools/list. */
@Serializable
data class ToolsListResult(
    val _meta: Map<String, JsonElement>? = null,
    val resultType: ResultType,
    val nextCursor: String? = null,
    val tools: List<ToolDescriptor>,
    val ttlMs: Int,
    val cacheScope: CacheScope,
)

/** ToolsCallParams is the request params payload for tools/call. */
@Serializable
data class ToolsCallParams(
    val _meta: RequestMeta,
    val inputResponses: JsonElement? = null,
    val requestState: String? = null,
    val name: String,
    val arguments: JsonElement? = null,
)

/** ResourceContent contains resource data returned by resources/read. */
@Serializable
data class ResourceContent(
    val _meta: Map<String, JsonElement>? = null,
    val uri: String,
    val mimeType: String? = null,
    val text: String? = null,
    val blob: String? = null,
)

/** Annotations provide optional metadata for MCP resources and content. */
@Serializable
data class Annotations(
    val audience: List<Role>? = null,
    val priority: Int? = null,
    val lastModified: String? = null,
)

/**
 * ContentBlock is an MCP content item.
 *
 * The draft schema models this as a union. Validate checks that only fields for
 * the selected content type are present.
 */
@Serializable
data class ContentBlock(
    val _meta: Map<String, JsonElement>? = null,
    val icons: List<Icon>? = null,
    val type: ContentType,
    val name: String? = null,
    val title: String? = null,
    val text: String? = null,
    val data: String? = null,
    val uri: String? = null,
    val description: String? = null,
    val mimeType: String? = null,
    val size: Long? = null,
    val resource: ResourceContent? = null,
    val annotations: Annotations? = null,
)

/** ToolCallResult is the response payload for a tool call. */
@Serializable
data class ToolCallResult(
    val _meta: Map<String, JsonElement>? = null,
    val resultType: ResultType,
    val content: List<ContentBlock>,
    val structuredContent: JsonElement? = null,
    val isError: Boolean? = null,
)

/** ResourceDescriptor describes a resource the server can read. */
@Serializable
data class ResourceDescriptor(
    val _meta: Map<String, JsonElement>? = null,
    val icons: List<Icon>? = null,
    val uri: String,
    val name: String,
    val title: String? = null,
    val description: String? = null,
    val mimeType: String? = null,
    val annotations: Annotations? = null,
    val size: Long? = null,
)

/** ResourcesListResult is the response payload for resources/list. */
@Serializable
data class ResourcesListResult(
    val _meta: Map<String, JsonElement>? = null,
    val resultType: ResultType,
    val nextCursor: String? = null,
    val resources: List<ResourceDescriptor>,
    val ttlMs: Int,
    val cacheScope: CacheScope,
)

/** ResourceTemplateDescriptor describes a parameterized MCP resource. */
@Serializable
data class ResourceTemplateDescriptor(
    val _meta: Map<String, JsonElement>? = null,
    val icons: List<Icon>? = null,
    val name: String,
    val title: String? = null,
    val uriTemplate: String,
    val description: String? = null,
    val mimeType: String? = null,
    val annotations: Annotations? = null,
)

/** ResourceTemplatesListResult is the response payload for resources/templates/list. */
@Serializable
data class ResourceTemplatesListResult(
    val _meta: Map<String, JsonElement>? = null,
    val resultType: ResultType,
    val nextCursor: String? = null,
    val resourceTemplates: List<ResourceTemplateDescriptor>,
    val ttlMs: Int,
    val cacheScope: CacheScope,
)

/** ResourcesReadParams is the request params payload for resources/read. */
@Serializable
data class ResourcesReadParams(
    val _meta: RequestMeta,
    val inputResponses: JsonElement? = null,
    val requestState: String? = null,
    val uri: String,
)

/** ResourcesReadResult is the response payload for resources/read. */
@Serializable
data class ResourcesReadResult(
    val _meta: Map<String, JsonElement>? = null,
    val resultType: ResultType,
    val contents: List<ResourceContent>,
    val ttlMs: Int,
    val cacheScope: CacheScope,
)

/** SubscriptionFilter describes MCP subscription notifications requested by a client. */
@Serializable
data class SubscriptionFilter(
    val toolsListChanged: Boolean? = null,
    val promptsListChanged: Boolean? = null,
    val resourcesListChanged: Boolean? = null,
    val resourceSubscriptions: List<String>? = null,
)

/** SubscriptionsListenParams is the request params payload for subscriptions/listen. */
@Serializable
data class SubscriptionsListenParams(val _meta: RequestMeta, val notifications: SubscriptionFilter)

/** JSONRPCNotification is a JSON-RPC notification that does not expect a response. */
@Serializable
data class JSONRPCNotification(
    val jsonrpc: String,
    val method: String,
    val params: JsonElement? = null,
)

/** SubscriptionNotificationParams is the payload for subscription notifications. */
@Serializable
data class SubscriptionNotificationParams(
    val _meta: Map<String, JsonElement>? = null,
    val notifications: SubscriptionFilter? = null,
    val uri: String? = null,
)

