// Code generated by gen-api-sdk. DO NOT EDIT.
import Foundation

/// ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z").
public typealias ISOTimestamp = String

/// A Codable representation of an arbitrary JSON value.
public enum JSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let v = try? c.decode(Bool.self) { self = .bool(v); return }
        if let v = try? c.decode(Double.self) { self = .number(v); return }
        if let v = try? c.decode(String.self) { self = .string(v); return }
        if let v = try? c.decode([String: JSONValue].self) { self = .object(v); return }
        if let v = try? c.decode([JSONValue].self) { self = .array(v); return }
        throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown JSON value"))
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        case .array(let v): try c.encode(v)
        case .null: try c.encodeNil()
        }
    }
}

public enum ErrorCodes {
}

/// MCPSettings describes the service MCP endpoint Android can use for tools and resources.
public struct MCPSettings: Codable {
    public let endpoint: String
    public let protocolVersion: String
    public let authRequired: Bool
}

/// VoiceGatewaySettings describes the preferred voice gateway for this service.
public struct VoiceGatewaySettings: Codable {
    public let required: Bool
    public let url: String?
    public let authRequired: Bool?
    public let tokenEndpoint: String?
}

/// WebShellSettings describes the hosted frontend's native-shell contract.
public struct WebShellSettings: Codable {
    public let bridgeVersion: Int
    public let mcp: MCPSettings
    public let voiceGateway: VoiceGatewaySettings
}

/// Settings is the service compatibility document consumed by Go Mode Android.
public struct Settings: Codable {
    public let service: String
    public let serviceVersion: String?
    public let apiVersion: Int
    public let webShell: WebShellSettings
}

/// ErrorBody describes a Go Mode API error.
public struct ErrorBody: Codable {
    public let code: String
    public let message: String
}

/// ErrorResponse is the standard JSON error envelope for Go Mode SDK clients.
public struct ErrorResponse: Codable {
    public let error: ErrorBody
    public let details: [String: JSONValue]?
}

