// Golden-file tests for ExportDiscussion using the OpenCode parser.
//
// Golden files are generated by record-trace (go generate). To regenerate:
//
//	go generate ./backend/internal/agent/opencode/...

package opencode_test

import (
	"testing"

	"github.com/caic-xyz/caic/backend/internal/agent/agenttest"
	"github.com/caic-xyz/caic/backend/internal/agent/opencode"
)

func TestExportDiscussionGolden(t *testing.T) {
	t.Parallel()
	agenttest.RunExportDiscussionGolden(t, opencode.New("", nil).NewWire().ParseMessage)
}
