// Code generated by gen-api-sdk. DO NOT EDIT.
package com.caic.sdk.v1

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import okhttp3.sse.EventSource
import okhttp3.sse.EventSourceListener
import okhttp3.sse.EventSources
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

class ApiException(
    val statusCode: Int,
    val code: String,
    message: String,
    val details: Map<String, kotlinx.serialization.json.JsonElement>? = null,
) : Exception(message)

class ApiClient(
    baseURL: String,
    private val tokenProvider: (() -> String?)? = null,
) {
    private val baseURL: String = baseURL.trimEnd('/')
    private val client = OkHttpClient()
    private val json = Json { ignoreUnknownKeys = true }
    private val jsonMediaType = "application/json".toMediaType()

    private suspend inline fun <reified T> request(method: String, path: String, body: String? = null): T {
        val url = "$baseURL$path"
        val needsBody = method in listOf("POST", "PUT", "PATCH")
        val requestBody = body?.toRequestBody(jsonMediaType)
            ?: if (needsBody) "".toRequestBody(jsonMediaType) else null
        val request = Request.Builder()
            .url(url)
            .method(method, requestBody)
            .header("Content-Type", "application/json")
            .apply { tokenProvider?.invoke()?.let { header("Authorization", "Bearer $it") } }
            .build()
        return suspendCancellableCoroutine { cont ->
            val call = client.newCall(request)
            cont.invokeOnCancellation { call.cancel() }
            call.enqueue(object : okhttp3.Callback {
                override fun onFailure(call: okhttp3.Call, e: java.io.IOException) {
                    cont.resumeWithException(e)
                }
                override fun onResponse(call: okhttp3.Call, response: Response) {
                    response.use { resp ->
                        val responseBody = resp.body?.string() ?: ""
                        if (!resp.isSuccessful) {
                            try {
                                val err = json.decodeFromString<ErrorResponse>(responseBody)
                                cont.resumeWithException(
                                    ApiException(resp.code, err.error.code, err.error.message, err.details)
                                )
                            } catch (_: Exception) {
                                cont.resumeWithException(
                                    ApiException(resp.code, "UNKNOWN", responseBody)
                                )
                            }
                            return
                        }
                        try {
                            cont.resume(json.decodeFromString<T>(responseBody))
                        } catch (e: Exception) {
                            cont.resumeWithException(e)
                        }
                    }
                }
            })
        }
    }

    // JSON endpoints
    /** Returns server capabilities and feature flags. */
    suspend fun getConfig(): Config = request("GET", "/api/v1/server/config")
    /** Returns the authenticated user's profile. */
    suspend fun getMe(): UserResp = request("GET", "/api/v1/auth/me")
    /** Invalidates the current session. */
    suspend fun logout(): StatusResp = request("POST", "/api/v1/auth/logout")
    /** Returns server and per-repository preferences. */
    suspend fun getPreferences(): PreferencesResp = request("GET", "/api/v1/server/preferences")
    /** Updates server settings and preferences. */
    suspend fun updatePreferences(req: UpdatePreferencesReq): PreferencesResp = request("POST", "/api/v1/server/preferences", json.encodeToString(req))
    /** Lists available coding agent harnesses. */
    suspend fun listHarnesses(): List<HarnessInfo> = request("GET", "/api/v1/server/harnesses")
    /** Lists well-known cache configurations. */
    suspend fun listCaches(): WellKnownCachesResp = request("GET", "/api/v1/server/caches")
    /** Lists all discovered repositories. */
    suspend fun listRepos(): List<Repo> = request("GET", "/api/v1/server/repos")
    /** Clones a repository into the server's root directory. */
    suspend fun cloneRepo(req: CloneRepoReq): Repo = request("POST", "/api/v1/server/repos", json.encodeToString(req))
    /** Lists branches for a repository. */
    suspend fun listRepoBranches(repo: String): RepoBranchesResp = request("GET", "/api/v1/server/repos/branches?repo=$repo")
    /** Creates a task to fix a failing CI pipeline. */
    suspend fun botFixCI(req: BotFixCIReq): CreateTaskResp = request("POST", "/api/v1/bot/fix-ci", json.encodeToString(req))
    /** Injects a CI fix command into an existing task's PR. */
    suspend fun botFixPR(req: BotFixPRReq): StatusResp = request("POST", "/api/v1/bot/fix-pr", json.encodeToString(req))
    /** Returns all tasks. */
    suspend fun listTasks(): List<Task> = request("GET", "/api/v1/tasks")
    /** Creates and starts a new coding agent task. */
    suspend fun createTask(req: CreateTaskReq): CreateTaskResp = request("POST", "/api/v1/tasks", json.encodeToString(req))
    /** Sends user input to a running task. */
    suspend fun sendInput(id: String, req: InputReq): StatusResp = request("POST", "/api/v1/tasks/$id/input", json.encodeToString(req))
    /** Restarts a completed or errored task with a new prompt. */
    suspend fun restartTask(id: String, req: RestartReq): StatusResp = request("POST", "/api/v1/tasks/$id/restart", json.encodeToString(req))
    /** Requests graceful stop of a running task. */
    suspend fun stopTask(id: String): StatusResp = request("POST", "/api/v1/tasks/$id/stop")
    /** Permanently deletes a task and its container. */
    suspend fun purgeTask(id: String): StatusResp = request("POST", "/api/v1/tasks/$id/purge")
    /** Reconnects to an orphaned task container. */
    suspend fun reviveTask(id: String): StatusResp = request("POST", "/api/v1/tasks/$id/revive")
    /** Returns the log tail of a failed CI check run. */
    suspend fun getTaskCILog(id: String, jobID: String): CILogResp = request("GET", "/api/v1/tasks/$id/ci-log?jobID=$jobID")
    /** Pushes task changes to the remote repository. */
    suspend fun syncTask(id: String, req: SyncReq): SyncResp = request("POST", "/api/v1/tasks/$id/sync", json.encodeToString(req))
    /** Returns the unified diff for a task's branch. */
    suspend fun getTaskDiff(id: String): DiffResp = request("GET", "/api/v1/tasks/$id/diff")
    /** Returns the full (untruncated) input for a tool call. */
    suspend fun getTaskToolInput(id: String, toolUseID: String): TaskToolInputResp = request("GET", "/api/v1/tasks/$id/tool/$toolUseID")
    /** Returns current usage quota statistics. */
    suspend fun getUsage(): UsageResp = request("GET", "/api/v1/usage")
    /** Returns a short-lived voice API token. */
    suspend fun getVoiceToken(): VoiceTokenResp = request("GET", "/api/v1/voice/token")
    /** Fetches a URL and returns its text content. */
    suspend fun webFetch(req: WebFetchReq): WebFetchResp = request("POST", "/api/v1/web/fetch", json.encodeToString(req))

    // SSE endpoints
    /** Streams raw backend-specific task events via SSE. */
    fun taskRawEvents(id: String): Flow<EventMessage> = sseFlow<EventMessage>("/api/v1/tasks/$id/raw_events")
    /** Streams backend-neutral task events via SSE. */
    fun taskEvents(id: String): Flow<EventMessage> = sseFlow<EventMessage>("/api/v1/tasks/$id/events")
    /** Streams task list updates for all tasks via SSE. */
    fun globalTaskEvents(): Flow<TaskListEvent> = sseFlow<TaskListEvent>("/api/v1/server/tasks/events")
    /** Streams usage quota updates via SSE. */
    fun globalUsageEvents(): Flow<UsageResp> = sseFlow<UsageResp>("/api/v1/server/usage/events")

    private inline fun <reified T> sseFlow(path: String): Flow<T> = callbackFlow {
        val request = Request.Builder()
            .url("$baseURL$path")
            .header("Accept", "text/event-stream")
            .apply { tokenProvider?.invoke()?.let { header("Authorization", "Bearer $it") } }
            .build()
        val factory = EventSources.createFactory(client)
        val source = factory.newEventSource(request, object : EventSourceListener() {
            override fun onEvent(eventSource: EventSource, id: String?, type: String?, data: String) {
                try {
                    val event = json.decodeFromString<T>(data)
                    trySend(event)
                } catch (_: Exception) {
                    // Skip malformed events.
                }
            }
            override fun onFailure(eventSource: EventSource, t: Throwable?, response: Response?) {
                close(t?.let { java.io.IOException("SSE connection failed", it) })
            }
            override fun onClosed(eventSource: EventSource) {
                close()
            }
        })
        awaitClose { source.cancel() }
    }

    // Reconnecting SSE wrappers with exponential backoff.
    /** Streams raw backend-specific task events via SSE. */
    fun taskRawEventsReconnecting(id: String): Flow<EventMessage> = reconnectingFlow { taskRawEvents(id) }
    /** Streams backend-neutral task events via SSE. */
    fun taskEventsReconnecting(id: String): Flow<EventMessage> = reconnectingFlow { taskEvents(id) }
    /** Streams task list updates for all tasks via SSE. */
    fun globalTaskEventsReconnecting(): Flow<TaskListEvent> = reconnectingFlow { globalTaskEvents() }
    /** Streams usage quota updates via SSE. */
    fun globalUsageEventsReconnecting(): Flow<UsageResp> = reconnectingFlow { globalUsageEvents() }

    private fun <T> reconnectingFlow(connect: () -> Flow<T>): Flow<T> = flow {
        var delayMs = 500L
        while (true) {
            try {
                connect().onEach { delayMs = 500L }.collect { emit(it) }
            } catch (e: CancellationException) {
                throw e
            } catch (_: Exception) {
                delay(delayMs)
                delayMs = (delayMs * 3 / 2).coerceAtMost(4000L)
            }
        }
    }
}
