// Code generated by gen-api-sdk. DO NOT EDIT.
@file:UseSerializers(InstantSerializer::class)

package com.caic.voicegateway.sdk.v1

import java.time.Instant
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

/** Serializes [Instant] as an ISO 8601 string. */
object InstantSerializer : KSerializer<Instant> {
    override val descriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

object ErrorCodes {
    const val BadRequest = "BAD_REQUEST"
    const val Unauthorized = "UNAUTHORIZED"
    const val InternalError = "INTERNAL_ERROR"
}

/** VoiceTokenResp is the response for GET /api/v1/voice/token. */
@Serializable
data class VoiceTokenResp(
    val token: String,
    val expiresAt: String,
    val ephemeral: Boolean,
)

/** VoiceRTCOfferReq is the request body for POST /api/v1/voice/rtc/offer. */
@Serializable
data class VoiceRTCOfferReq(val sdp: String)

/** VoiceRTCAnswerResp is the response for POST /api/v1/voice/rtc/offer. */
@Serializable
data class VoiceRTCAnswerResp(
    val sdp: String,
    @SerialName("sessionID") val sessionID: String,
)

/** StatusResp is a common response for mutation endpoints. */
@Serializable
data class StatusResp(val status: String)

@Serializable
data class ErrorDetails(val code: String, val message: String)

@Serializable
data class ErrorResponse(val error: ErrorDetails, val details: Map<String, JsonElement>? = null)

