// Singleton API client for the caic web UI.

import { createApiClient } from "@sdk/api.gen";

export const api = createApiClient();

export const {
  getConfig,
  getVersion,
  triggerUpdate,
  getMe,
  logout,
  getPreferences,
  updatePreferences,
  listOAuthGrants,
  revokeOAuthGrant,
  listHarnesses,
  listCaches,
  getCacheSizes,
  listRepos,
  cloneRepo,
  listRepoBranches,
  botFixCI,
  botFixPR,
  listTasks,
  createTask,
  taskRawEvents,
  taskEvents: taskEventStream,
  sendInput,
  restartTask,
  clearContext,
  compactContext,
  forkTask,
  stopTask,
  purgeTask,
  reviveTask,
  getTask,
  getTaskInfo,
  getTaskCILog,
  syncTask,
  getTaskDiff,
  getTaskProcesses,
  signalProcess,
  getTaskToolInput,
  globalTaskEvents,
  globalUsageEvents,
  getUsage,
  webFetch,
} = api;
