// Code generated by gen-api-sdk. DO NOT EDIT.
import type { BotFixCIReq, BotFixPRReq, CILogResp, CacheSizesResp, CloneRepoReq, CompactReq, Config, CreateTaskReq, DiffResp, ErrorCode, ErrorResponse, EventMessage, FileDiffResp, ForkTaskReq, HarnessInfo, InputReq, MetricsResp, OAuthGrantsResp, PreferencesResp, ProcessListResp, RefreshHarnessReq, Repo, RepoBranchesResp, RestartReq, RevokeOAuthGrantReq, SignalProcessReq, StatusResp, SyncReq, SyncResp, Task, TaskDiffIndexResp, TaskHandoffResp, TaskHistoryStreamError, TaskInfo, TaskListEvent, TaskRepoStatusResp, TaskToolInputResp, UpdatePreferencesReq, UpdateResp, UsageDashboardResp, UsageResp, UserResp, VersionResp, WebFetchReq, WebFetchResp, WellKnownCachesResp } from "./types.gen";
import { validateEventMessage, validateTaskHistoryStreamError, validateTaskListEvent, validateUsageResp } from "./validate.gen";

export interface TaskRawEventsHandlers {
  onMessage: (event: EventMessage) => void;
  onError: (err: unknown) => void;
}

export interface TaskEventsHandlers {
  onMessage: (event: EventMessage) => void;
  onError: (err: unknown) => void;
  onReady?: () => void;
  onReset?: () => void;
  onHistoryError?: (event: TaskHistoryStreamError) => void;
}

export interface GlobalTaskEventsHandlers {
  onMessage: (event: TaskListEvent) => void;
  onError: (err: unknown) => void;
}

export interface GlobalUsageEventsHandlers {
  onMessage: (event: UsageResp) => void;
  onError: (err: unknown) => void;
}

export class APIError extends Error {
  constructor(
    public status: number,
    public code: ErrorCode,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

function makeRequester(fetchFn: FetchFn) {
  return async function request<T>(method: string, path: string, body?: unknown, headers: Record<string, string> = {}): Promise<T> {
    const init: RequestInit = { method, headers: { "Content-Type": "application/json", ...headers }, signal: AbortSignal.timeout(60_000) };
    if (body !== undefined) init.body = JSON.stringify(body);
    const res = await fetchFn(path, init);
    if (!res.ok) {
      const err = (await res.json()) as ErrorResponse;
      const e = new APIError(res.status, err.error.code, err.details);
      e.message = err.error.message;
      throw e;
    }
    return res.json() as Promise<T>;
  };
}

// createApiClient returns an API client bound to the given fetch function.
// When fetchFn is omitted, globalThis.fetch is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createApiClient(fetchFn: FetchFn = (globalThis as any).fetch.bind(globalThis)) {
  const request = makeRequester(fetchFn);
  return {
    /** Returns server capabilities and feature flags. */
    getConfig: (): Promise<Config> => request<Config>("GET", "/api/caic/v1/server/config"),
    /** Returns the current server version and checks for available updates. */
    getVersion: (): Promise<VersionResp> => request<VersionResp>("GET", "/api/caic/v1/server/version"),
    /** Triggers a background server auto-update to the latest release. */
    triggerUpdate: (): Promise<UpdateResp> => request<UpdateResp>("POST", "/api/caic/v1/server/update"),
    /** Returns the authenticated user's profile. */
    getMe: (): Promise<UserResp> => request<UserResp>("GET", "/auth/me"),
    /** Invalidates the current session. */
    logout: (): Promise<StatusResp> => request<StatusResp>("POST", "/auth/logout"),
    /** Returns server and per-repository preferences. */
    getPreferences: (): Promise<PreferencesResp> => request<PreferencesResp>("GET", "/api/caic/v1/server/preferences"),
    /** Updates server settings and preferences. */
    updatePreferences: (req: UpdatePreferencesReq): Promise<PreferencesResp> => request<PreferencesResp>("POST", "/api/caic/v1/server/preferences", req),
    /** Lists the authenticated user's connected OAuth clients. */
    listOAuthGrants: (): Promise<OAuthGrantsResp> => request<OAuthGrantsResp>("GET", "/api/caic/v1/oauth/grants"),
    /** Revokes one connected OAuth client grant for the authenticated user. */
    revokeOAuthGrant: (grantID: string, req: RevokeOAuthGrantReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/oauth/grants/${encodeURIComponent(grantID)}/revoke`, req),
    /** Lists available coding agent harnesses. */
    listHarnesses: (): Promise<HarnessInfo[]> => request<HarnessInfo[]>("GET", "/api/caic/v1/server/harnesses"),
    /** Refreshes one coding agent model inventory, bypassing its cache. */
    refreshHarness: (harness: string, req: RefreshHarnessReq): Promise<HarnessInfo> => request<HarnessInfo>("POST", `/api/caic/v1/server/harnesses/${encodeURIComponent(harness)}/refresh`, req),
    /** Lists well-known cache configurations. */
    listCaches: (): Promise<WellKnownCachesResp> => request<WellKnownCachesResp>("GET", "/api/caic/v1/server/caches"),
    /** Returns the latest size snapshot for well-known caches. */
    getCacheSizes: (): Promise<CacheSizesResp> => request<CacheSizesResp>("GET", "/api/caic/v1/server/cache-sizes"),
    /** Returns aggregated operation latency statistics. */
    getMetrics: (): Promise<MetricsResp> => request<MetricsResp>("GET", "/api/caic/v1/server/metrics"),
    /** Lists all discovered repositories. */
    listRepos: (): Promise<Repo[]> => request<Repo[]>("GET", "/api/caic/v1/server/repos"),
    /** Clones a repository into the server's root directory. */
    cloneRepo: (req: CloneRepoReq): Promise<Repo> => request<Repo>("POST", "/api/caic/v1/server/repos", req),
    /** Lists branches for a repository. */
    listRepoBranches: (repo: string): Promise<RepoBranchesResp> => request<RepoBranchesResp>("GET", `/api/caic/v1/server/repos/branches?repo=${encodeURIComponent(repo)}`),
    /** Creates a task to fix a failing CI pipeline. */
    botFixCI: (req: BotFixCIReq): Promise<Task> => request<Task>("POST", "/api/caic/v1/ci/fix-ci", req),
    /** Injects a CI fix command into an existing task's PR. */
    botFixPR: (req: BotFixPRReq): Promise<StatusResp> => request<StatusResp>("POST", "/api/caic/v1/ci/fix-pr", req),
    /** Returns all tasks. */
    listTasks: (): Promise<Task[]> => request<Task[]>("GET", "/api/caic/v1/tasks"),
    /** Returns a single task by id (404 if it does not exist). */
    getTask: (id: string): Promise<Task> => request<Task>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}`),
    /** Returns recorded and observed runtime metadata for a task. */
    getTaskInfo: (id: string): Promise<TaskInfo> => request<TaskInfo>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/info`),
    /** Creates and starts a new coding agent task. */
    createTask: (req: CreateTaskReq): Promise<Task> => request<Task>("POST", "/api/caic/v1/tasks", req),
    /** Streams raw backend-specific task events via SSE. */
    taskRawEvents: (id: string, handlers: TaskRawEventsHandlers): EventSource => {
      const es = new EventSource(`/api/caic/v1/tasks/${encodeURIComponent(id)}/raw_events`);
      es.addEventListener("message", (e) => {
        try {
          handlers.onMessage(validateEventMessage(JSON.parse(e.data)));
        } catch (err) {
          handlers.onError(err);
        }
      });
      return es;
    },
    /** Streams backend-neutral task events via SSE. */
    taskEvents: (id: string, handlers: TaskEventsHandlers): EventSource => {
      const es = new EventSource(`/api/caic/v1/tasks/${encodeURIComponent(id)}/events`);
      es.addEventListener("message", (e) => {
        try {
          handlers.onMessage(validateEventMessage(JSON.parse(e.data)));
        } catch (err) {
          handlers.onError(err);
        }
      });
      if (handlers.onReady) {
        es.addEventListener("ready", handlers.onReady);
      }
      if (handlers.onReset) {
        es.addEventListener("reset", handlers.onReset);
      }
      es.addEventListener("error", (e) => {
        if (!(e instanceof MessageEvent) || typeof e.data !== "string") return;
        try {
          handlers.onHistoryError?.(validateTaskHistoryStreamError(JSON.parse(e.data)));
        } catch (err) {
          handlers.onError(err);
        }
      });
      return es;
    },
    /** Sends user input to a running task. */
    sendInput: (id: string, req: InputReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/input`, req),
    /** Restarts a completed or errored task with a new prompt. */
    restartTask: (id: string, req: RestartReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/restart`, req),
    /** Clears context and restarts the agent session without a prompt. */
    clearContext: (id: string): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/clear-context`),
    /** Sends a compact command to reduce the agent's context window usage. */
    compactContext: (id: string, req: CompactReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/compact`, req),
    /** Requests graceful stop of a running task. */
    stopTask: (id: string): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/stop`),
    /** Stops a task, then deletes its runtime instance after the configured recovery window unless revived. */
    purgeTask: (id: string): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/purge`),
    /** Reconnects to an orphaned task runtime instance. */
    reviveTask: (id: string): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/revive`),
    /** Returns the log tail of a failed CI check run. */
    getTaskCILog: (id: string, jobID: string): Promise<CILogResp> => request<CILogResp>("GET", `/api/caic/v1/ci/log/${encodeURIComponent(id)}?jobID=${encodeURIComponent(jobID)}`),
    /** Pushes task changes to the remote repository. */
    syncTask: (id: string, req: SyncReq): Promise<SyncResp> => request<SyncResp>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/sync`, req),
    /** Forks a task by snapshotting its runtime instance and creating a new task on a derived branch. */
    forkTask: (id: string, req: ForkTaskReq): Promise<Task> => request<Task>("POST", `/api/caic/v1/tasks/${encodeURIComponent(id)}/fork`, req),
    /** Builds an editable handoff prompt for continuing a task in a fresh agent session. */
    getTaskHandoff: (id: string): Promise<TaskHandoffResp> => request<TaskHandoffResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/handoff`),
    /** Returns repository status and the unified diff for a task's branch. */
    getTaskDiff: (id: string, path: string): Promise<DiffResp> => request<DiffResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/diff?path=${encodeURIComponent(path)}`),
    /** Returns repository and changed-file metadata without loading patch bodies. */
    getTaskDiffIndex: (id: string): Promise<TaskDiffIndexResp> => request<TaskDiffIndexResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/diff/index`),
    /** Returns one committed or uncommitted file patch. */
    getTaskFileDiff: (id: string, repository: string, commit: string, path: string, originalPath: string): Promise<FileDiffResp> => request<FileDiffResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/diff/file?repository=${encodeURIComponent(repository)}&commit=${encodeURIComponent(commit)}&path=${encodeURIComponent(path)}&originalPath=${encodeURIComponent(originalPath)}`),
    /** Returns compact Git state for every repository mapped to a task. */
    getTaskRepoStatus: (id: string): Promise<TaskRepoStatusResp> => request<TaskRepoStatusResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/repo-status`),
    /** Returns the list of running processes inside the task's runtime instance. */
    getTaskProcesses: (id: string): Promise<ProcessListResp> => request<ProcessListResp>("GET", `/api/caic/v1/processes/${encodeURIComponent(id)}`),
    /** Sends SIGTERM or SIGKILL to a process inside the task's runtime instance. */
    signalProcess: (id: string, pid: string, req: SignalProcessReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/caic/v1/processes/${encodeURIComponent(id)}/${encodeURIComponent(pid)}/signal`, req),
    /** Returns the full (untruncated) input for a tool call. */
    getTaskToolInput: (id: string, toolUseID: string): Promise<TaskToolInputResp> => request<TaskToolInputResp>("GET", `/api/caic/v1/tasks/${encodeURIComponent(id)}/tool/${encodeURIComponent(toolUseID)}`),
    /** Streams task list updates for all tasks via SSE. */
    globalTaskEvents: (handlers: GlobalTaskEventsHandlers): EventSource => {
      const es = new EventSource("/api/caic/v1/tasks/events");
      es.addEventListener("message", (e) => {
        try {
          handlers.onMessage(validateTaskListEvent(JSON.parse(e.data)));
        } catch (err) {
          handlers.onError(err);
        }
      });
      return es;
    },
    /** Streams usage quota updates via SSE. */
    globalUsageEvents: (handlers: GlobalUsageEventsHandlers): EventSource => {
      const es = new EventSource("/api/caic/v1/usage/events");
      es.addEventListener("message", (e) => {
        try {
          handlers.onMessage(validateUsageResp(JSON.parse(e.data)));
        } catch (err) {
          handlers.onError(err);
        }
      });
      return es;
    },
    /** Returns current usage quota statistics. */
    getUsage: (): Promise<UsageResp> => request<UsageResp>("GET", "/api/caic/v1/usage"),
    /** Returns daily cross-task usage rollups for the usage dashboard. */
    getUsageDashboard: (): Promise<UsageDashboardResp> => request<UsageDashboardResp>("GET", "/api/caic/v1/usage/dashboard"),
    /** Fetches a URL and returns its text content. */
    webFetch: (req: WebFetchReq): Promise<WebFetchResp> => request<WebFetchResp>("POST", "/api/caic/v1/web/fetch", req),
  };
}

export type APIClient = ReturnType<typeof createApiClient>;
