// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };

//////////
// source: events.go
/*
SSE event types sent to the frontend for task event streams.
*/

export type EventCostSource =
  | "estimated"
  | "reported";
/**
 * Supported values.
 */
export const EventCostEstimated = "estimated";
export const EventCostReported = "reported";

export type EventKind =
  | "init"
  | "text"
  | "textDelta"
  | "toolUse"
  | "toolResult"
  | "ask"
  | "usage"
  | "result"
  | "system"
  | "userInput"
  | "todo"
  | "diffStat"
  | "error"
  | "thinking"
  | "thinkingDelta"
  | "subagentStart"
  | "subagentEnd"
  | "nativeSubagent"
  | "backgroundCommand"
  | "log"
  | "toolOutputDelta"
  | "widget"
  | "widgetDelta"
  | "rateLimit"
  | "stats"
  | "commitSnapshot";
/**
 * Supported values.
 */
export const EventKindInit = "init";
export const EventKindText = "text";
export const EventKindTextDelta = "textDelta";
export const EventKindToolUse = "toolUse";
export const EventKindToolResult = "toolResult";
export const EventKindAsk = "ask";
export const EventKindUsage = "usage";
export const EventKindResult = "result";
export const EventKindSystem = "system";
export const EventKindUserInput = "userInput";
export const EventKindTodo = "todo";
export const EventKindDiffStat = "diffStat";
export const EventKindError = "error";
export const EventKindThinking = "thinking";
export const EventKindThinkingDelta = "thinkingDelta";
export const EventKindSubagentStart = "subagentStart";
export const EventKindSubagentEnd = "subagentEnd";
export const EventKindNativeSubagent = "nativeSubagent";
export const EventKindBackgroundCommand = "backgroundCommand";
export const EventKindLog = "log";
export const EventKindToolOutputDelta = "toolOutputDelta";
export const EventKindWidget = "widget";
export const EventKindWidgetDelta = "widgetDelta";
export const EventKindRateLimit = "rateLimit";
export const EventKindStats = "stats";
export const EventKindCommitSnapshot = "commitSnapshot";

export type EventNativeSubagentScope =
  | "agent"
  | "batch";
/**
 * Supported values.
 */
export const EventNativeSubagentScopeAgent = "agent";
export const EventNativeSubagentScopeBatch = "batch";

export type EventNativeSubagentStatus =
  | "completed"
  | "failed"
  | "interrupted"
  | "paused"
  | "running"
  | "unknown";
/**
 * Supported values.
 */
export const EventNativeSubagentStatusCompleted = "completed";
export const EventNativeSubagentStatusFailed = "failed";
export const EventNativeSubagentStatusInterrupted = "interrupted";
export const EventNativeSubagentStatusPaused = "paused";
export const EventNativeSubagentStatusRunning = "running";
export const EventNativeSubagentStatusUnknown = "unknown";

export type EventRateLimitStatus =
  | "allowed"
  | "allowed_warning"
  | "rejected";
/**
 * Supported values.
 */
export const EventRateLimitStatusAllowed = "allowed";
export const EventRateLimitStatusAllowedWarning = "allowed_warning";
export const EventRateLimitStatusRejected = "rejected";

export type EventToolInputKind =
  | "fileChanges"
  | "subagents";
/**
 * Supported values.
 */
export const EventToolInputFileChanges = "fileChanges";
export const EventToolInputSubagents = "subagents";

export type ToolOutputContentType =
  | "text"
  | "json"
  | "markdown";
/**
 * Supported values.
 */
export const ToolOutputText = "text";
export const ToolOutputJSON = "json";
export const ToolOutputMarkdown = "markdown";

/**
 * EventInit is emitted once at the start of a session. It includes a Harness
 * field so the client knows which backend produced the stream.
 */
export interface EventInit {
  reportedModel: string;
  /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty when not supported. */
  reportedEffort?: string;
  agentVersion: string;
  sessionID: string;
  tools?: string[];
  cwd: string;
  harness: string;
}

/** EventText is an assistant text block. */
export interface EventText {
  text: string;
}

/** EventTextDelta is a streaming text fragment from --include-partial-messages. */
export interface EventTextDelta {
  text: string;
}

/** EventFileChange is one changed file rendered from a unified patch. */
export interface EventFileChange {
  path: string;
  patch: string;
}

/** EventSubagentSpawn is one backend-normalized subagent invocation. */
export interface EventSubagentSpawn {
  agent: string;
  task: string;
  label?: string;
  phase?: string;
}

/**
 * EventToolInputView is a backend-normalized rendering model for known tool
 * inputs. It keeps harness-specific tool schemas out of clients.
 */
export interface EventToolInputView {
  kind: EventToolInputKind;
  files?: EventFileChange[];
  subagents?: EventSubagentSpawn[];
}

/** EventToolUse is emitted when the assistant invokes a tool. */
export interface EventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
  /** Backend-normalized short display detail for tool headers. */
  detail?: string;
  /** Backend-normalized structured input for tool-card rendering. */
  inputView?: EventToolInputView;
  /** Snapshot of plan content for ExitPlanMode events. */
  planContent?: string;
  /** True when Input was omitted due to size; fetch via GET /api/caic/v1/tasks/{id}/tool/{toolUseID}. */
  inputTruncated?: boolean;
  /** True when the tool runs in the background (Bash/Agent run_in_background). */
  background?: boolean;
}

/** EventToolResult is emitted when a tool call completes. */
export interface EventToolResult {
  toolUseID: string;
  /** Seconds; server-computed; 0 if unknown. */
  duration: number /* float64 */;
  error?: string;
}

/** AskOption is a single option in an AskUserQuestion. */
export interface AskOption {
  label: string;
  description?: string;
}

/** AskQuestion is a single question from AskUserQuestion. */
export interface AskQuestion {
  question: string;
  header?: string;
  options: AskOption[];
  multiSelect?: boolean;
}

/** EventAsk is emitted when the agent asks the user a question. */
export interface EventAsk {
  toolUseID: string;
  questions: AskQuestion[];
}

/**
 * EventUsage reports per-turn token usage.
 * ReasoningOutputTokens is a subset of OutputTokens for extended thinking (Claude)
 * or reasoning summaries (Codex). Zero when the harness does not report it.
 */
export interface EventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  reasoningOutputTokens?: number /* int */;
  reportedModel: string;
}

/** EventCost is one completed turn's reported or API-equivalent estimated cost. */
export interface EventCost {
  usd: number /* float64 */;
  source: EventCostSource;
}

/** EventResult is emitted when the task reaches a terminal state. */
export interface EventResult {
  cost?: EventCost;
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  /** Seconds. */
  duration: number /* float64 */;
  /** Seconds. */
  durationAPI: number /* float64 */;
  numTurns: number /* int */;
  usage: EventUsage;
}

/** EventSystem is a system event (status, compact_boundary, etc.). */
export interface EventSystem {
  subtype: string;
  /** Optional human-readable detail (e.g. model names for model_rerouted). */
  detail?: string;
  /**
   * ContextTokensBefore is the context size the harness reported before a
   * compact_boundary. Zero means the harness did not report it.
   */
  contextTokensBefore?: number /* int64 */;
  /**
   * ContextTokensAfter is the context size the harness reported after a
   * compact_boundary, measured or estimated. Zero means it did not report it.
   */
  contextTokensAfter?: number /* int64 */;
}

/** EventUserInput is emitted when a user sends a text message to the agent. */
export interface EventUserInput {
  text: string;
  images?: ImageData[];
}

/** TodoItem is a single todo entry from a TodoWrite tool call. */
export interface TodoItem {
  content: string;
  /** "pending", "in_progress", "completed". */
  status: string;
  activeForm?: string;
}

/** EventTodo is emitted when the agent writes/updates its todo list. */
export interface EventTodo {
  toolUseID: string;
  todos: TodoItem[];
}

/** EventDiffStat is emitted when the relay reports updated diff statistics. */
export interface EventDiffStat {
  diffStat?: DiffStat;
}

/** EventError is emitted when the backend fails to parse an agent output line. */
export interface EventError {
  err: string;
  line: string;
}

/** EventThinking is an assistant thinking block. */
export interface EventThinking {
  text: string;
}

/** EventThinkingDelta is a streaming thinking fragment. */
export interface EventThinkingDelta {
  text: string;
}

/**
 * EventSubagentStart is emitted when a subagent task begins. It is the legacy
 * harness-agnostic shape: no current parser produces it, and clients should
 * render EventNativeSubagent instead. It stays in the v1 event union and the
 * generated SDKs so existing clients that switch on these kinds keep compiling.
 */
export interface EventSubagentStart {
  taskID: string;
  description: string;
}

/**
 * EventSubagentEnd is emitted when a subagent task completes, fails, or stops.
 * It is the legacy harness-agnostic shape: no current parser produces it, and
 * clients should render EventNativeSubagent instead. It stays in the v1 event
 * union and the generated SDKs so existing clients that switch on these kinds
 * keep compiling.
 */
export interface EventSubagentEnd {
  taskID: string;
  /** "completed", "failed", "stopped" */
  status: string;
}

/**
 * EventNativeSubagent is one lifecycle update for a harness native subagent.
 * ID and GroupID are opaque harness identities. Optional fields remain absent
 * when the harness did not expose them.
 */
export interface EventNativeSubagent {
  toolUseID?: string;
  scope?: EventNativeSubagentScope;
  id: string;
  groupID?: string;
  label?: string;
  prompt?: string;
  status: EventNativeSubagentStatus;
  result?: string;
  /**
   * Background reports that the harness launched the delegation detached from
   * the parent turn, so it can outlive that turn's result.
   */
  background?: boolean;
}

/**
 * EventBackgroundCommand reports one harness-native detached shell command's
 * folded lifecycle. ExitCode is the command's numeric outcome when the harness
 * reported one; OutputRef is an opaque harness-owned output reference, not a
 * caic resource.
 */
export interface EventBackgroundCommand {
  id: string;
  label?: string;
  status: string;
  result?: string;
  exitCode?: number /* int */;
  outputRef?: string;
  toolUseID?: string;
}

/** EventLog is a provisioning/startup log line from the runtime backend. */
export interface EventLog {
  line: string;
}

/**
 * EventToolOutputDelta is a streaming output fragment from a running tool.
 * Codex only: emitted for Bash stdout (item/commandExecution/outputDelta) and
 * MCP tool progress messages (item/mcpToolCall/progress).
 */
export interface EventToolOutputDelta {
  toolUseID: string;
  delta: string;
  contentType?: ToolOutputContentType;
  /** Pretty-printed JSON or other transformation. */
  formatted?: string;
}

/** EventWidget is emitted when the agent produces a complete HTML widget. */
export interface EventWidget {
  toolUseID: string;
  title: string;
  html: string;
}

/** EventWidgetDelta is a streaming HTML fragment for progressive widget rendering. */
export interface EventWidgetDelta {
  toolUseID: string;
  delta: string;
}

/** EventRateLimit is emitted when the agent's rate limit status changes. */
export interface EventRateLimit {
  status: EventRateLimitStatus;
  /** When the limit resets; zero if unknown. */
  resetsAt?: ISOTimestamp;
  /** "five_hour", "seven_day", etc. */
  rateLimitType: string;
  /** 0.0–1.0; -1 when unknown. */
  utilization: number /* float64 */;
  /** True when extra/overage usage is active. */
  isUsingOverage?: boolean;
  /** When overage resets; zero if not using overage. */
  overageResetsAt?: ISOTimestamp;
}

/** EventStats is a runtime resource usage snapshot emitted periodically. */
export interface EventStats {
  ts: number /* int64 */;
  cpuPerc: number /* float64 */;
  memUsed: number /* uint64 */;
  memLimit: number /* uint64 */;
  memPerc: number /* float64 */;
  netRx: number /* uint64 */;
  netTx: number /* uint64 */;
  blockRead: number /* uint64 */;
  blockWrite: number /* uint64 */;
  diskUsed: number /* int64 */;
}

/**
 * EventRepositoryCommit identifies one immutable repository branch tip in a
 * commit snapshot.
 */
export interface EventRepositoryCommit {
  /** RepositoryPath is the repository's absolute path inside the task runtime. */
  repositoryPath: string;
  /** BranchName is the short local branch name, such as "main" or "caic-1". */
  branchName: string;
  /** CommitHash is the full Git object ID of the branch tip. */
  commitHash: string;
}

/** EventChangeStat summarizes a completed turn's net committed change. */
export interface EventChangeStat {
  files: number /* int */;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  binaryFiles: number /* int */;
}

/**
 * EventCommitSnapshot records the exact committed repository branch tips
 * fetched from the runtime when a turn finishes.
 */
export interface EventCommitSnapshot {
  repositoryCommits: EventRepositoryCommit[];
  baseline?: boolean;
  changeStat?: EventChangeStat;
}

/**
 * EventMessage is a single SSE event in the backend-neutral stream
 * (/api/caic/v1/tasks/{id}/events). All backends produce these events.
 */
export interface EventMessage {
  kind: EventKind;
  ts: number /* int64 */;
  init?: EventInit;
  text?: EventText;
  textDelta?: EventTextDelta;
  toolUse?: EventToolUse;
  toolResult?: EventToolResult;
  ask?: EventAsk;
  usage?: EventUsage;
  result?: EventResult;
  system?: EventSystem;
  userInput?: EventUserInput;
  todo?: EventTodo;
  diffStat?: EventDiffStat;
  error?: EventError;
  thinking?: EventThinking;
  thinkingDelta?: EventThinkingDelta;
  subagentStart?: EventSubagentStart;
  subagentEnd?: EventSubagentEnd;
  nativeSubagent?: EventNativeSubagent;
  backgroundCommand?: EventBackgroundCommand;
  log?: EventLog;
  toolOutputDelta?: EventToolOutputDelta;
  widget?: EventWidget;
  widgetDelta?: EventWidgetDelta;
  rateLimit?: EventRateLimit;
  stats?: EventStats;
  commitSnapshot?: EventCommitSnapshot;
}

/**
 * TaskEventBackward carries the latest visible agent response and its canonical
 * event ID. Pass EventID as the events endpoint's last-event-id query parameter
 * to stream newer events while earlier history is replayed.
 */
export interface TaskEventBackward {
  message: EventMessage;
  eventId: string;
}

/** TaskHistoryStreamError reports that task history could not be replayed. */
export interface TaskHistoryStreamError {
  message: string;
}


//////////
// source: types.go

export type BranchAction =
  | "adopt"
  | "branch_off";
/**
 * Supported values.
 */
export const BranchActionAdopt = "adopt";
export const BranchActionBranchOff = "branch_off";

export type CIStatus =
  | "pending"
  | "success"
  | "failure";
/**
 * Supported values.
 */
export const CIStatusPending = "pending";
export const CIStatusSuccess = "success";
export const CIStatusFailure = "failure";

export type CheckConclusion =
  | "success"
  | "failure"
  | "neutral"
  | "skipped"
  | "cancelled"
  | "timed_out"
  | "action_required"
  | "stale";
/**
 * Supported values.
 */
export const CheckConclusionSuccess = "success";
export const CheckConclusionFailure = "failure";
export const CheckConclusionNeutral = "neutral";
export const CheckConclusionSkipped = "skipped";
export const CheckConclusionCancelled = "cancelled";
export const CheckConclusionTimedOut = "timed_out";
export const CheckConclusionActionRequired = "action_required";
export const CheckConclusionStale = "stale";

export type CheckStatus =
  | "queued"
  | "in_progress"
  | "completed";
/**
 * Supported values.
 */
export const CheckStatusQueued = "queued";
export const CheckStatusInProgress = "in_progress";
export const CheckStatusCompleted = "completed";

export type ErrorCode =
  | "BAD_REQUEST"
  | "UNKNOWN_HARNESS"
  | "UNKNOWN_REPOSITORY"
  | "UNSUPPORTED_MODEL"
  | "INVALID_OAUTH_STATE"
  | "UNKNOWN_CACHE"
  | "UNKNOWN_RUNTIME"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "OAUTH_GRANT_NOT_FOUND"
  | "OAUTH_PROVIDER_UNAVAILABLE"
  | "CONFLICT"
  | "REPOSITORY_PATH_CONFLICT"
  | "INTERNAL_ERROR"
  | "UPDATE_CHECK_FAILED"
  | "UPDATE_UNAVAILABLE"
  | (string & {});
/**
 * Supported values.
 */
export const ErrorCodeBadRequest = "BAD_REQUEST";
export const ErrorCodeUnknownHarness = "UNKNOWN_HARNESS";
export const ErrorCodeUnknownRepository = "UNKNOWN_REPOSITORY";
export const ErrorCodeUnsupportedModel = "UNSUPPORTED_MODEL";
export const ErrorCodeInvalidOauthState = "INVALID_OAUTH_STATE";
export const ErrorCodeUnknownCache = "UNKNOWN_CACHE";
export const ErrorCodeUnknownRuntime = "UNKNOWN_RUNTIME";
export const ErrorCodeUnauthorized = "UNAUTHORIZED";
export const ErrorCodeForbidden = "FORBIDDEN";
export const ErrorCodeNotFound = "NOT_FOUND";
export const ErrorCodeOauthGrantNotFound = "OAUTH_GRANT_NOT_FOUND";
export const ErrorCodeOauthProviderUnavailable = "OAUTH_PROVIDER_UNAVAILABLE";
export const ErrorCodeConflict = "CONFLICT";
export const ErrorCodeRepositoryPathConflict = "REPOSITORY_PATH_CONFLICT";
export const ErrorCodeInternalError = "INTERNAL_ERROR";
export const ErrorCodeUpdateCheckFailed = "UPDATE_CHECK_FAILED";
export const ErrorCodeUpdateUnavailable = "UPDATE_UNAVAILABLE";

export type Forge =
  | "github"
  | "gitlab";
/**
 * Supported values.
 */
export const ForgeGitHub = "github";
export const ForgeGitLab = "gitlab";

export type ForgePRState =
  | "open"
  | "closed"
  | "merged";
/**
 * Supported values.
 */
export const ForgePRStateOpen = "open";
export const ForgePRStateClosed = "closed";
export const ForgePRStateMerged = "merged";

export type GitOperation =
  | "rebase"
  | "merge"
  | "cherry-pick"
  | "revert"
  | "bisect";
/**
 * Supported values.
 */
export const GitOperationRebase = "rebase";
export const GitOperationMerge = "merge";
export const GitOperationCherryPick = "cherry-pick";
export const GitOperationRevert = "revert";
export const GitOperationBisect = "bisect";

export type Harness =
  | "claude"
  | "codex"
  | "opencode"
  | "pi";
/**
 * Supported values.
 */
export const HarnessClaude = "claude";
export const HarnessCodex = "codex";
export const HarnessOpenCode = "opencode";
export const HarnessPi = "pi";

export type ImageRefreshState =
  | "idle"
  | "running"
  | "succeeded"
  | "failed";
/**
 * Supported values.
 */
export const ImageRefreshIdle = "idle";
export const ImageRefreshRunning = "running";
export const ImageRefreshSucceeded = "succeeded";
export const ImageRefreshFailed = "failed";

export type OAuthGrantStatus =
  | "active"
  | "expired"
  | "revoked";
/**
 * Supported values.
 */
export const OAuthGrantStatusActive = "active";
export const OAuthGrantStatusExpired = "expired";
export const OAuthGrantStatusRevoked = "revoked";

export type Platform =
  | ""
  | "linux/arm64"
  | "linux/amd64";
/**
 * Supported values.
 */
export const PlatformDefault = "";
export const PlatformLinuxARM64 = "linux/arm64";
export const PlatformLinuxAMD64 = "linux/amd64";

export type ProviderAuthKind =
  | "oauth"
  | "apikey";
/**
 * Supported values.
 */
export const ProviderAuthKindOAuth = "oauth";
export const ProviderAuthKindAPIKey = "apikey";

export type ProviderFetchStatus =
  | "error"
  | "fresh"
  | "stale"
  | "unknown";
/**
 * Supported values.
 */
export const ProviderFetchStatusError = "error";
export const ProviderFetchStatusFresh = "fresh";
export const ProviderFetchStatusStale = "stale";
export const ProviderFetchStatusUnknown = "unknown";

export type QuotaProvider =
  | "alibaba"
  | "anthropic"
  | "cerebras"
  | "claudecode"
  | "codex"
  | "deepseek"
  | "gemini"
  | "grok"
  | "groq"
  | "openrouter"
  | "runinfra"
  | "typesafe"
  | "xiaomi"
  | "zai";
/**
 * Supported values.
 */
export const QuotaProviderAlibaba = "alibaba";
export const QuotaProviderAnthropic = "anthropic";
export const QuotaProviderCerebras = "cerebras";
export const QuotaProviderClaudeCode = "claudecode";
export const QuotaProviderCodex = "codex";
export const QuotaProviderDeepSeek = "deepseek";
export const QuotaProviderGemini = "gemini";
export const QuotaProviderGrok = "grok";
export const QuotaProviderGroq = "groq";
export const QuotaProviderOpenRouter = "openrouter";
export const QuotaProviderRunInfra = "runinfra";
export const QuotaProviderTypeSafe = "typesafe";
export const QuotaProviderXiaomi = "xiaomi";
export const QuotaProviderZai = "zai";

export type SyncTarget =
  | "branch"
  | "default";
/**
 * Supported values.
 */
export const SyncTargetBranch = "branch";
export const SyncTargetDefault = "default";

export type TaskState =
  | "pending"
  | "branching"
  | "provisioning"
  | "starting"
  | "running"
  | "waiting"
  | "asking"
  | "has_plan"
  | "pulling"
  | "pushing"
  | "stopping"
  | "stopped"
  | "purging"
  | "crashed"
  | "failed"
  | "purged";
/**
 * Supported values.
 */
export const TaskStatePending = "pending";
export const TaskStateBranching = "branching";
export const TaskStateProvisioning = "provisioning";
export const TaskStateStarting = "starting";
export const TaskStateRunning = "running";
export const TaskStateWaiting = "waiting";
export const TaskStateAsking = "asking";
export const TaskStateHasPlan = "has_plan";
export const TaskStatePulling = "pulling";
export const TaskStatePushing = "pushing";
export const TaskStateStopping = "stopping";
export const TaskStateStopped = "stopped";
export const TaskStatePurging = "purging";
export const TaskStateCrashed = "crashed";
export const TaskStateFailed = "failed";
export const TaskStatePurged = "purged";

export type VoiceGatewayMode =
  | "disabled"
  | "embedded"
  | "external";
/**
 * Supported values.
 */
export const VoiceGatewayModeDisabled = "disabled";
export const VoiceGatewayModeEmbedded = "embedded";
export const VoiceGatewayModeExternal = "external";

export type WarningCategory =
  | "ci_poll_failed"
  | "runtime_restore_failed";
/**
 * Supported values.
 */
export const WarningCategoryCIPollFailed = "ci_poll_failed";
export const WarningCategoryRuntimeRestoreFailed = "runtime_restore_failed";

/** DiffStat summarises the changes in a branch relative to its base. */
export type DiffStat = DiffFileStat[];

/** ImageConstraints describes decoded-byte budgets and supported image MIME types. */
export interface ImageConstraints {
  allowedMediaTypes: string[];
  maxImageBytes: number /* int */;
  maxPromptImageBytes: number /* int */;
}

/** VoiceGatewayMetadata reports structured voice gateway support. */
export interface VoiceGatewayMetadata {
  mode: VoiceGatewayMode;
  url?: string;
  authRequired?: boolean;
  capabilities?: string[];
}

/** RuntimeInfo is the JSON representation of an available task runtime backend. */
export interface RuntimeInfo {
  name: string;
}

/** Config reports server capabilities to the frontend. */
export interface Config {
  imageConstraints: ImageConstraints;
  version?: string;
  displayName: string;
  tailscaleAvailable: boolean;
  usbAvailable: boolean;
  displayAvailable: boolean;
  sudoAvailable: boolean;
  gitHubTokenAvailable: boolean;
  voiceGateway: VoiceGatewayMetadata;
  gitHubAppEnabled?: boolean;
  /** e.g. ["github","gitlab"] */
  authProviders?: string[];
  mcpOAuthAvailable: boolean;
  runtimes?: RuntimeInfo[];
}

/** VersionResp is the response for GET /api/caic/v1/server/version. */
export interface VersionResp {
  current: string;
  /** empty when check failed */
  latest?: string;
  /** true when Latest > Current */
  updateAvailable: boolean;
  /** non-empty when the GitHub check failed */
  checkError?: string;
  /** true when autoupdate schedule is configured */
  autoUpdateEnabled: boolean;
}

/** UpdateResp is the response for POST /api/caic/v1/server/update. */
export interface UpdateResp {
  /** "started" or "already_up_to_date" */
  status: string;
}

/** UserResp is returned by GET /auth/me. */
export interface UserResp {
  id: string;
  provider: string;
  username: string;
  avatarURL?: string;
}

/** StatusResp is a common response for mutation endpoints. */
export interface StatusResp {
  status: string;
}

/** RepoPrefsResp holds per-repository preferences. */
export interface RepoPrefsResp {
  path: string;
  baseBranch?: string;
  harness?: string;
  requestedModel?: string;
}

/** RuntimeSettings holds CPU configuration for a single runtime. */
export interface RuntimeSettings {
  /**
   * ContainerPlatform selects the runtime CPU architecture. Empty means use
   * the host's native platform. Valid values are linux/amd64 and linux/arm64.
   */
  containerPlatform?: Platform;
  /**
   * MaxCPUs limits the number of CPU cores the runtime instance may use.
   * Zero means use the runtime default: leave two CPUs of headroom where
   * possible, allowing at least two CPUs when available.
   */
  maxCPUs?: number /* int */;
}

/** CacheMappingResp represents a directory mapping for cache/state sharing. */
export interface CacheMappingResp {
  hostPath: string;
  /** ContainerPath is optional; empty uses the matching home-relative HostPath. */
  containerPath: string;
  /** ResolvedContainerPath is the runtime target after applying the ContainerPath default. */
  resolvedContainerPath?: string;
  enabled: boolean;
}

/** MountMappingResp represents a general host-to-runtime directory mount. */
export interface MountMappingResp {
  hostPath: string;
  /** ContainerPath is optional; empty uses the matching home-relative HostPath. */
  containerPath: string;
  /** ResolvedContainerPath is the runtime target after applying the ContainerPath default. */
  resolvedContainerPath?: string;
  enabled: boolean;
  readOnly: boolean;
}

/** UserSettings holds user-configurable behavioral settings. */
export interface UserSettings {
  /**
   * AutoFixOnCIFailure automatically starts a new task to fix CI when a
   * task's PR CI fails and the original task can no longer receive input.
   * Only effective when the GitHub App is configured.
   */
  autoFixOnCIFailure: boolean;
  /**
   * AutoFixOnPROpen automatically creates a task to review and fix a pull
   * request when it is opened or reopened via a forge webhook.
   */
  autoFixOnPROpen: boolean;
  /**
   * BaseImage overrides the default runtime base image. Empty means use
   * the default.
   */
  baseImage?: string;
  /** RuntimeSettings stores CPU architecture and limits by runtime name. */
  runtimeSettings?: { [key: string]: RuntimeSettings};
  /**
   * PurgeDelay is the recovery window in nanoseconds before a stopped task is
   * permanently deleted.
   */
  purgeDelay: number /* int64 */;
  /** RuntimeName is the preferred runtime backend for new tasks. */
  runtimeName?: string;
  /**
   * WellKnownCaches maps cache name to enabled state. Absent or false means
   * disabled, true means enabled. Caches are opt-in.
   */
  wellKnownCaches?: { [key: string]: boolean};
  /** CacheMappings are custom host-to-runtime directory mappings. */
  cacheMappings?: CacheMappingResp[];
  /** CustomMounts are custom non-cache host-to-runtime directory mappings. */
  customMounts?: MountMappingResp[];
}

/** PreferencesResp is the response for GET /api/caic/v1/server/preferences. */
export interface PreferencesResp {
  repositories: RepoPrefsResp[];
  harness?: string;
  models?: { [key: string]: string};
  efforts?: { [key: string]: { [key: string]: string}};
  settings: UserSettings;
}

/** UpdatePreferencesReq is the request body for POST /api/caic/v1/server/preferences. */
export interface UpdatePreferencesReq {
  settings: UserSettings;
}

/** OAuthGrantResp describes one user-authorized remote MCP client grant. */
export interface OAuthGrantResp {
  id: string;
  clientID: string;
  clientName: string;
  scopes: string[];
  resource: string;
  createdAt: ISOTimestamp;
  lastUsedAt?: ISOTimestamp;
  expiresAt: ISOTimestamp;
  revokedAt?: ISOTimestamp;
  status: OAuthGrantStatus;
}

/** OAuthGrantsResp is the response for GET /api/caic/v1/oauth/grants. */
export interface OAuthGrantsResp {
  grants: OAuthGrantResp[];
}

/** RevokeOAuthGrantReq is the request for POST /api/caic/v1/oauth/grants/{grantID}/revoke. */
export interface RevokeOAuthGrantReq {
}

/** Model describes the configuration choices supported by a harness model. */
export interface Model {
  id: string;
  effortOptions: string[];
}

/** HarnessInfo is the JSON representation of an available harness. */
export interface HarnessInfo {
  name: Harness;
  models: Model[];
  supportsImages: boolean;
  supportsCompact: boolean;
  supportsModelRefresh: boolean;
  /** Shared quota source; empty when harness usage cannot be inferred. */
  quotaGroup?: QuotaProvider;
}

/** RefreshHarnessReq is the request for POST /api/caic/v1/server/harnesses/{harness}/refresh. */
export interface RefreshHarnessReq {
}

/** ImageRefreshReq identifies the runtime whose specialized image is refreshed. */
export interface ImageRefreshReq {
}

/** ImageRefreshStatus describes the current or most recent image refresh. */
export interface ImageRefreshStatus {
  state: ImageRefreshState;
  error?: string;
  scheduled?: boolean;
}

/** WellKnownCache describes a single well-known cache. */
export interface WellKnownCache {
  name: string;
  description: string;
  /** List of runtime mount paths */
  mounts: string[];
}

/** WellKnownCachesResp is the response for GET /api/caic/v1/server/caches. */
export interface WellKnownCachesResp {
  /** e.g. "~/.claude", "~/.codex" */
  harnessMounts: string[];
  wellKnown: WellKnownCache[];
}

/** CacheSize describes the most recent size snapshot for a well-known cache. */
export interface CacheSize {
  name: string;
  sizeBytes: number /* int64 */;
  calculatedAt?: ISOTimestamp;
  error?: string;
}

/** CacheSizesResp is the response for GET /api/caic/v1/server/cache-sizes. */
export interface CacheSizesResp {
  wellKnown: CacheSize[];
}

/** MetricResource identifies the process that produced the observations. */
export interface MetricResource {
  /** ServiceName is the emitting binary, such as "caic". */
  serviceName: string;
  /** ServiceVersion is the build version, when known. */
  serviceVersion?: string;
  /** Host is the machine the process runs on, when known. */
  host?: string;
}

/**
 * MetricSeries describes aggregated measurements sharing one name, kind, unit,
 * outcome, and attribute set.
 */
export interface MetricSeries {
  /**
   * Name is the measurement identifier, such as "container.launch" or
   * "mcp.tool.task_create".
   */
  name: string;
  /** Outcome is "ok" or "error". */
  outcome: string;
  /**
   * Kind is the OpenTelemetry instrument kind: "histogram", "counter",
   * "updowncounter", or "gauge". It decides which statistics are meaningful.
   */
  kind: string;
  /**
   * Unit is the unit the amounts are expressed in, in UCUM notation: "s" for
   * seconds, "By" for bytes, "1" for a dimensionless count.
   */
  unit: string;
  /**
   * Attrs are the bounded dimensions that separate this series from others
   * sharing its name and outcome, such as the container runtime. Omitted when
   * the measurement has no dimensions.
   */
  attrs?: { [key: string]: string};
  /** Count is the number of recorded measurements. */
  count: number /* int64 */;
  /** Samples is the number of retained measurements used for the percentiles. */
  samples: number /* int64 */;
  /** Sum is the total of every recorded amount, in Unit. */
  sum: number /* float64 */;
  /** Min is the smallest retained amount, in Unit. */
  min: number /* float64 */;
  /** P50 is the median retained amount, in Unit. */
  p50: number /* float64 */;
  /** P95 is the 95th percentile retained amount, in Unit. */
  p95: number /* float64 */;
  /** Max is the largest retained amount, in Unit. */
  max: number /* float64 */;
  /** Last is the most recently recorded amount, in Unit. */
  last: number /* float64 */;
}

/**
 * MetricsResp is the historical and live aggregate for GET
 * /api/caic/v1/server/metrics.
 */
export interface MetricsResp {
  /** Since is the earliest retained observation in the aggregate. */
  since?: ISOTimestamp;
  /** Resource identifies the process that produced the observations. */
  resource: MetricResource;
  /** Series holds per-operation aggregates, slowest p95 first. */
  series: MetricSeries[];
}

/** BranchInfo describes a single branch with its origin and task-creation action. */
export interface BranchInfo {
  name: string;
  remote?: string;
  action?: BranchAction;
}

/** ForgeCheck describes a CI check run with its status, conclusion, and timing. */
export interface ForgeCheck {
  name: string;
  owner: string;
  repo: string;
  /** Pipeline/workflow run ID. */
  runID: number /* int64 */;
  /** Check run / job ID. */
  jobID: number /* int64 */;
  /** queued, in_progress, completed. */
  status: CheckStatus;
  /** Empty when not completed. */
  conclusion: CheckConclusion;
  /** When the check was created/queued. */
  queuedAt?: ISOTimestamp;
  /** When execution began. */
  startedAt?: ISOTimestamp;
  /** When execution finished. */
  completedAt?: ISOTimestamp;
}

/** Repo is the JSON representation of a discovered repo. */
export interface Repo {
  path: string;
  branch: string;
  baseBranch: BranchInfo;
  remoteURL?: string;
  /** "github", "gitlab", or empty if unknown. */
  forge?: Forge;
  ci?: CIStatus;
  ciChecks?: ForgeCheck[];
  checksDate?: ISOTimestamp;
}

/** CloneRepoReq is the request body for POST /api/caic/v1/server/repos. */
export interface CloneRepoReq {
  /** Git clone URL (HTTPS or SSH). */
  url: string;
  /** Target subdirectory under rootDir; defaults to repo basename. */
  path?: string;
  depth?: number /* int */;
}

/** RepoBranchesResp is the response for GET /api/caic/v1/server/repos/branches. */
export interface RepoBranchesResp {
  branches: BranchInfo[];
}

/**
 * BotFixCIReq is the request body for POST /api/caic/v1/bot/fix-ci.
 * The server fetches CI logs, builds a prompt, and creates a fix task.
 */
export interface BotFixCIReq {
  repo: string;
}

/** TaskRepo describes a repository associated with a task in the API response. */
export interface TaskRepo {
  name: string;
  baseBranch?: string;
  branch: string;
  remoteURL?: string;
  /** "github", "gitlab", or empty if unknown. */
  forge?: Forge;
}

/**
 * DiffFileStat describes changes to a single file. LinesAdded and LinesDeleted
 * count text lines. OldSize and NewSize report byte sizes for binary files and
 * are -1 for text files, with 0 on the side where the path is added or removed.
 */
export interface DiffFileStat {
  path: string;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  /** OldSize is the binary pre-image byte size, or -1 for text files. */
  oldSize: number /* int64 */;
  /** NewSize is the binary post-image byte size, or -1 for text files. */
  newSize: number /* int64 */;
  diff?: string;
}

/** GitRepositoryState summarizes the compact Git state of one task repository. */
export interface GitRepositoryState {
  /** Last known data retained after a failed refresh. */
  stale?: boolean;
  name: string;
  branch: string;
  ahead: number /* int */;
  behind: number /* int */;
  changedFiles: number /* int */;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  uncommittedFiles: number /* int */;
  conflicts: number /* int */;
  operation?: GitOperation;
}

/** TaskStartupFailure identifies the failed startup phase and original agent diagnostic. */
export interface TaskStartupFailure {
  harness: Harness;
  phase: string;
  cause: string;
}

/** RuntimeInstance holds per-task runtime metadata. */
export interface RuntimeInstance {
  /** Runtime instance ID. */
  id: string;
  /** Runtime backend name. */
  runtimeName?: string;
  /** Tailscale URL (https://fqdn) or "true" if enabled but FQDN unknown. */
  tailscale?: string;
  usb?: boolean;
  display?: boolean;
  sudo?: boolean;
  /** SudoPassword is the random sudo password, only populated when Sudo is true. */
  sudoPassword?: string;
  vncPort?: number /* int */;
}

/** TaskRateLimit is the current quota block resolved by the backend for one task. */
export interface TaskRateLimit {
  blocked: boolean;
  quotaGroup?: QuotaProvider;
  window?: string;
  resetsAt?: ISOTimestamp;
}

/** Task is the JSON representation sent to the frontend. */
export interface Task {
  id: string;
  initialPrompt: string;
  title: string;
  repos?: TaskRepo[];
  state: TaskState;
  /** When the task state last changed. */
  stateUpdatedAt: ISOTimestamp;
  diffStat?: DiffStat;
  /** Pushed compact per-repo Git state from the latest diff probe. */
  repoStates?: GitRepositoryState[];
  costUSD: number /* float64 */;
  /** Seconds. */
  duration: number /* float64 */;
  numTurns: number /* int */;
  cumulativeInputTokens: number /* int */;
  cumulativeOutputTokens: number /* int */;
  cumulativeCacheCreationInputTokens: number /* int */;
  cumulativeCacheReadInputTokens: number /* int */;
  /** Last turn's non-cached input tokens (including cache creation). */
  activeInputTokens: number /* int */;
  /** Last turn's cache-read input tokens. */
  activeCacheReadTokens: number /* int */;
  /** Effective cache TTL from last API call (seconds); 0 = unknown. */
  cacheTTLSeconds?: number /* int */;
  /** When the prompt cache expires. */
  cacheExpiresAt?: ISOTimestamp;
  /** Final writable-layer size retained by a stopped task, or -1 when unavailable. */
  stoppedDiskUsedBytes: number /* int64 */;
  /** Model context window limit (tokens). */
  contextWindowLimit: number /* int */;
  error?: string;
  startupFailure?: TaskStartupFailure;
  result?: string;
  forgeOwner?: string;
  forgeRepo?: string;
  forgePR?: number /* int */;
  forgePRState?: ForgePRState;
  forgeIssue?: number /* int */;
  ciStatus?: CIStatus;
  ciChecks?: ForgeCheck[];
  /** username of creator; omitted in no-auth mode */
  owner?: string;
  forkedFromTaskID?: string;
  parentTaskID?: string;
  caicMCP?: boolean;
  /** Per-task harness/agent metadata. */
  harness: Harness;
  requestedModel?: string;
  requestedEffort?: string;
  reportedModel?: string;
  reportedEffort?: string;
  agentVersion?: string;
  sessionID?: string;
  /** When the task was created. */
  startedAt?: ISOTimestamp;
  /** When the current turn started; zero when not running. */
  turnStartedAt?: ISOTimestamp;
  inPlanMode?: boolean;
  planContent?: string;
  runtime: RuntimeInstance;
  /** Current quota block resolved by the backend. */
  rateLimit?: TaskRateLimit;
  /** Per-task feature flags. */
  gitHubToken?: boolean;
}

/**
 * BotFixPRReq is the request body for POST /api/caic/v1/bot/fix-pr.
 * The server fetches CI logs for the task's PR and injects a fix command.
 */
export interface BotFixPRReq {
  taskId: string;
}

/** TaskInfoCapability describes recorded runtime capabilities and injected-token presence. */
export interface TaskInfoCapability {
  tailscale?: boolean;
  usb?: boolean;
  display?: boolean;
  sudo?: boolean;
  gitHubToken?: boolean;
}

/** TaskInfoRepo describes a repository mounted into a task runtime. */
export interface TaskInfoRepo {
  name: string;
  baseBranch?: string;
  branch?: string;
  gitRoot?: string;
  containerPath?: string;
  remoteURL?: string;
  forge?: Forge;
}

/** TaskInfoCacheMount describes a recorded cache mount. */
export interface TaskInfoCacheMount {
  name?: string;
  description?: string;
  hostPath?: string;
  containerPath?: string;
  readOnly?: boolean;
  shallow?: boolean;
}

/** TaskInfoMount describes a recorded or observed bind mount. */
export interface TaskInfoMount {
  hostPath?: string;
  containerPath?: string;
  readOnly?: boolean;
}

/** TaskInfoRecorded holds caic-recorded task launch configuration and metadata. */
export interface TaskInfoRecorded {
  state: TaskState;
  forkedFromTaskID?: string;
  parentTaskID?: string;
  caicMCP?: boolean;
  startedAt?: ISOTimestamp;
  stateUpdatedAt?: ISOTimestamp;
  harness: Harness;
  requestedModel?: string;
  requestedEffort?: string;
  reportedModel?: string;
  reportedEffort?: string;
  agentVersion?: string;
  sessionID?: string;
  baseImage?: string;
  containerOS?: string;
  containerCPUArchitecture?: string;
  maxCPUs?: number /* int */;
  capabilities: TaskInfoCapability;
  runtime: RuntimeInstance;
  repos?: TaskInfoRepo[];
  caches?: TaskInfoCacheMount[];
  mounts?: TaskInfoMount[];
}

/** TaskInfoObservedRuntime describes runtime-observed instance details from the runtime adapter. */
export interface TaskInfoObservedRuntime {
  runtimeName?: string;
  runtime?: string;
  id?: string;
  state?: string;
  imageRef?: string;
  imageID?: string;
  os?: string;
  cpuArchitecture?: string;
  cpuLimit?: number /* int */;
  mounts?: TaskInfoMount[];
  caches?: TaskInfoCacheMount[];
}

/** TaskInfo is the detailed metadata response for a task. */
export interface TaskInfo {
  id: string;
  recorded: TaskInfoRecorded;
  observed?: TaskInfoObservedRuntime;
  warnings?: string[];
}

/** ImageData carries a single base64-encoded image. */
export interface ImageData {
  /** e.g. "image/png", "image/jpeg" */
  mediaType: string;
  /** base64-encoded */
  data: string;
}

/** Prompt bundles user text with optional images. */
export interface Prompt {
  text: string;
  images?: ImageData[];
}

/** RepoSpec describes a repository to associate with a task at creation time. */
export interface RepoSpec {
  name: string;
  baseBranch?: string;
}

/** CreateTaskReq is the request body for POST /api/caic/v1/tasks. */
export interface CreateTaskReq {
  initialPrompt: Prompt;
  repos?: RepoSpec[];
  model?: string;
  /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty = default. */
  effort?: string;
  harness: Harness;
  runtimeName?: string;
  tailscale?: boolean;
  usb?: boolean;
  display?: boolean;
  sudo?: boolean;
  gitHubToken?: boolean;
  /** Enables task-scoped CAIC MCP delegation. */
  caicMCP?: boolean;
}

/** InputReq is the request body for POST /api/caic/v1/tasks/{id}/input. */
export interface InputReq {
  prompt: Prompt;
}

/** RestartReq is the request body for POST /api/caic/v1/tasks/{id}/restart. */
export interface RestartReq {
  prompt: Prompt;
}

/** CompactReq is the request body for POST /api/caic/v1/tasks/{id}/compact. */
export interface CompactReq {
  instructions?: string;
}

/**
 * CILogResp is the response for GET /api/caic/v1/tasks/{id}/ci-log.
 * It contains the name of the first failed CI step and its log tail.
 */
export interface CILogResp {
  stepName: string;
  log: string;
}

/** SyncReq is the request body for POST /api/caic/v1/tasks/{id}/sync. */
export interface SyncReq {
  force?: boolean;
  target?: SyncTarget;
}

/** SafetyIssue describes a potential problem detected before pushing to origin. */
export interface SafetyIssue {
  file: string;
  /** "large_binary" or "secret" */
  kind: string;
  /** Human-readable description. */
  detail: string;
}

/** SyncResp is the response for POST /api/caic/v1/tasks/{id}/sync. */
export interface SyncResp {
  /** "synced", "blocked", or "empty" */
  status: string;
  branch?: string;
  diffStat?: DiffStat;
  safetyIssues?: SafetyIssue[];
  /** non-zero if a PR/MR was created */
  prNumber?: number /* int */;
}

/** ForkTaskReq is the request body for POST /api/caic/v1/tasks/{id}/fork. */
export interface ForkTaskReq {
  /** Initial prompt for the forked task. */
  prompt: Prompt;
  /** Override harness; empty means inherit from source. */
  harness?: Harness;
  /** Override model; empty means inherit from source. */
  model?: string;
  /** Override thinking effort; empty means inherit from source. */
  effort?: string;
  /** Additional repos to map into the fork. */
  extraRepos?: RepoSpec[];
  /** Override Tailscale; nil means inherit from source. */
  tailscale?: boolean;
  /** Override USB; nil means inherit from source. */
  usb?: boolean;
  /** Override virtual display; nil means inherit from source. */
  display?: boolean;
  /** Override sudo; nil means inherit from source. */
  sudo?: boolean;
  /** Override gitHubToken; nil means inherit from source. */
  gitHubToken?: boolean;
}

/**
 * TaskHandoffResp contains an editable prompt for continuing a source task in
 * a fresh agent session.
 */
export interface TaskHandoffResp {
  prompt: string;
}

/** GitCommit describes one commit unique to either side of a repository's comparison branch. */
export interface GitCommit {
  sha: string;
  subject: string;
  decorations?: string;
  authoredDate: string;
  /** Present on the comparison branch and missing from HEAD. */
  behind?: boolean;
  stat: DiffStat;
}

/** GitFileStatus describes one uncommitted repository path. */
export interface GitFileStatus {
  path: string;
  originalPath?: string;
  indexStatus?: string;
  worktreeStatus?: string;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  /** OldSize is the binary pre-image byte size, or -1 for text files. */
  oldSize: number /* int64 */;
  /** NewSize is the binary post-image byte size, or -1 for text files. */
  newSize: number /* int64 */;
  diff: string;
}

/** GitRepositoryStatus describes the checked-out state of one task repository. */
export interface GitRepositoryStatus {
  name: string;
  branch: string;
  upstream?: string;
  ahead: number /* int */;
  behind: number /* int */;
  commits: GitCommit[];
  uncommitted: GitFileStatus[];
}

/** DiffResp is the response for GET /api/caic/v1/tasks/{id}/diff. */
export interface DiffResp {
  diff: string;
  repositories: GitRepositoryStatus[];
}

/** DiffIndexFileStat describes a committed file without its patch body. */
export interface DiffIndexFileStat {
  path: string;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  /** OldSize is the binary pre-image byte size, or -1 for text files. */
  oldSize: number /* int64 */;
  /** NewSize is the binary post-image byte size, or -1 for text files. */
  newSize: number /* int64 */;
}

/** DiffIndexCommit describes one commit and its changed-file metadata. */
export interface DiffIndexCommit {
  sha: string;
  subject: string;
  decorations?: string;
  authoredDate: string;
  /** Present on the comparison branch and missing from HEAD. */
  behind?: boolean;
  stat: DiffIndexFileStat[];
}

/** DiffIndexFileStatus describes one uncommitted path without its patch body. */
export interface DiffIndexFileStatus {
  path: string;
  originalPath?: string;
  indexStatus?: string;
  worktreeStatus?: string;
  linesAdded: number /* int */;
  linesDeleted: number /* int */;
  /** OldSize is the binary pre-image byte size, or -1 for text files. */
  oldSize: number /* int64 */;
  /** NewSize is the binary post-image byte size, or -1 for text files. */
  newSize: number /* int64 */;
}

/** DiffIndexRepository describes one repository in a diff index. */
export interface DiffIndexRepository {
  name: string;
  branch: string;
  upstream?: string;
  ahead: number /* int */;
  behind: number /* int */;
  commits: DiffIndexCommit[];
  uncommitted: DiffIndexFileStatus[];
}

/** TaskDiffIndexResp is the response for GET /api/caic/v1/tasks/{id}/diff/index. */
export interface TaskDiffIndexResp {
  repositories: DiffIndexRepository[];
}

/** FileDiffResp is the response for GET /api/caic/v1/tasks/{id}/diff/file. */
export interface FileDiffResp {
  diff: string;
}

/** TaskRepoStatusResp is the response for GET /api/caic/v1/tasks/{id}/repo-status. */
export interface TaskRepoStatusResp {
  repositories: GitRepositoryState[];
}

/** ProcessInfo describes a single process running inside the task runtime instance. */
export interface ProcessInfo {
  /** PID is the process ID. */
  pid: number /* int */;
  /** PPID is the parent process ID. */
  ppid: number /* int */;
  /** PGRP is the process group ID. */
  pgrp: number /* int */;
  /** User is the effective user name. */
  user: string;
  /** State is the process state and modifiers reported by the runtime. */
  state: string;
  /** Priority is the kernel scheduling priority. */
  priority: number /* int */;
  /** Nice is the process niceness value. */
  nice: number /* int */;
  /** Threads is the number of threads in the process. */
  threads: number /* int */;
  /** OpenFDs is the number of open file descriptors, if available. */
  openFDs?: number /* int */;
  /** CPU is the percentage of CPU capacity used at the time of inspection. */
  cpu: number /* float64 */;
  /** Mem is the percentage of physical memory used at the time of inspection. */
  mem: number /* float64 */;
  /** RSSBytes is the resident set size in bytes. */
  rssBytes: number /* uint64 */;
  /** CPUTime is the cumulative user and system CPU time in nanoseconds. */
  cpuTime: number /* int64 */;
  /** StartedAt is when the process started. */
  startedAt: ISOTimestamp;
  /** Command is the full command line reported by the runtime. */
  command: string;
}

/** ProcessListResp is the response for GET /api/caic/v1/tasks/{id}/processes. */
export interface ProcessListResp {
  processes: ProcessInfo[];
}

/** SignalProcessReq is the request body for POST /api/caic/v1/tasks/{id}/processes/{pid}/signal. */
export interface SignalProcessReq {
  /** "SIGTERM" or "SIGKILL" */
  signal: string;
}

/**
 * TaskToolInputResp is the response for GET /api/caic/v1/tasks/{id}/tool/{toolUseID}.
 * It returns the full (untruncated) input for a tool call.
 */
export interface TaskToolInputResp {
  toolUseID: string;
  input: any /* json.RawMessage */;
}

/** WarningDetail describes a failed operation on a repository. */
export interface WarningDetail {
  repo: string;
  error: string;
}

/**
 * Warning is an alert episode. ID is stable across detail updates and SSE replay;
 * a new failure after recovery receives a new ID.
 */
export interface Warning {
  id: string;
  category: WarningCategory;
  message: string;
  details: WarningDetail[];
}

/**
 * TaskListRestorationStatus carries background runtime/history restoration
 * state on kind=="status" events. Loading is true until both stages finish;
 * Error is non-empty when any stage leaves task membership incomplete.
 */
export interface TaskListRestorationStatus {
  loading: boolean;
  error: string;
}

/**
 * TaskListEvent is a discriminated-union event for the task list SSE stream.
 * kind=="snapshot": Snapshot carries task data on connect and when restoration becomes complete.
 * Complete is present on snapshots only: false preserves prior membership and drafts;
 * true certifies omissions after successful runtime/history restoration and DTO conversion.
 * kind=="upsert":   Upsert holds a newly created task.
 * kind=="patch":    Patch holds only the changed fields (always includes "id") for an existing task.
 * kind=="delete":   Delete holds the string ID of the removed task.
 * kind=="repos":    Repos holds the updated repo list (emitted when default-branch CI status changes).
 * kind=="warning": Warning holds a categorized alert with identity and diagnostic details.
 * kind=="status":   Status holds runtime/history restoration state, emitted on connect and again whenever restoration transitions (in-progress -> completed | failed).
 */
export interface TaskListEvent {
  complete?: boolean;
  kind: string;
  snapshot?: Task[];
  upsert?: Task;
  patch?: { [key: string]: any /* json.RawMessage */};
  delete?: string;
  repos?: Repo[];
  warning?: Warning;
  status?: TaskListRestorationStatus;
}

/** QuotaRateLimit is a single rate-limit window snapshot from any provider. */
export interface QuotaRateLimit {
  /** "5h", "7d", "primary", "secondary", "rpm", "tpd", … */
  window: string;
  /** 0.0–1.0 */
  utilization: number /* float64 */;
  /** zero when unknown */
  resetsAt?: ISOTimestamp;
}

/**
 * QuotaBalance is a balance/credit snapshot from any provider. When the
 * provider also reports pay-as-you-go spending (Anthropic-style extra credits
 * or a spend cap), the spend fields carry that information too.
 */
export interface QuotaBalance {
  /** "USD", "CNY", "credits", … */
  currency: string;
  /** total available balance */
  total: number /* float64 */;
  /** unexpired promotional/grant balance */
  granted?: number /* float64 */;
  /** self-funded recharge balance */
  toppedUp?: number /* float64 */;
  /** ExtraEnabled reports whether the pay-as-you-go spend cap is active. */
  extraEnabled?: boolean;
  /** used against the cap */
  usedCredits?: number /* float64 */;
  /** spend cap, 0 when unset */
  monthlyLimit?: number /* float64 */;
  /** 0.0–1.0 against the cap */
  utilization?: number /* float64 */;
}

/** ProviderQuota is the quota data for one provider. */
export interface ProviderQuota {
  provider: QuotaProvider;
  /** human-readable: "Anthropic", "DeepSeek", … */
  label: string;
  /** absolute URL path to provider SVG, e.g. "/logos/anthropic.svg" */
  logoUrl: string;
  authKind: ProviderAuthKind;
  /** link to provider's usage/billing page */
  usageUrl: string;
  fetchStatus: ProviderFetchStatus;
  rateLimits?: QuotaRateLimit[];
  /**
   * Balance is the provider's money snapshot. Some providers, such as
   * Anthropic, report it as "extra usage" on top of the subscription
   * instead of a prepaid wallet balance.
   */
  balance?: QuotaBalance;
  /**
   * PricingPhase reports time-dependent pricing as of the snapshot:
   * "peak", "peak-soon", or "off-peak". Empty when the provider's pricing
   * does not vary by time of day.
   */
  pricingPhase?: string;
  /**
   * PricingTransitionAt is when PricingPhase next changes; zero for
   * off-peak. Clients should interpolate between snapshots, which arrive
   * at the usage cache TTL cadence.
   */
  pricingTransitionAt?: ISOTimestamp;
}

/** LocalWindow is the aggregated local cost for a rolling time window. */
export interface LocalWindow {
  /** "1h", "6h", "24h" */
  duration: string;
  costUSD: number /* float64 */;
  inputTokens: number /* int */;
  outputTokens: number /* int */;
}

/** LocalUsage is the aggregated cost across all tasks within recent time windows. */
export interface LocalUsage {
  windows: LocalWindow[];
}

/** UsageResp is the response for GET /api/caic/v1/usage. */
export interface UsageResp {
  providers?: ProviderQuota[];
  local: LocalUsage;
}

/**
 * UsageDashboardTokens separates usage totals by their prompt-cache bucket.
 * Input, cache writes, and cache reads are disjoint; their sum is the full
 * prompt context consumed by the model.
 */
export interface UsageDashboardTokens {
  inputTokens: number /* int64 */;
  cacheWrite5mTokens: number /* int64 */;
  cacheWrite1hTokens: number /* int64 */;
  cacheReadTokens: number /* int64 */;
  outputTokens: number /* int64 */;
  reasoningTokens: number /* int64 */;
}

/** UsageDashboardCount is a named counter such as a skill read or tool call. */
export interface UsageDashboardCount {
  name: string;
  count: number /* int */;
}

/** UsageDashboardToolTiming measures completed tool calls with known duration. */
export interface UsageDashboardToolTiming {
  name: string;
  count: number /* int */;
  durationMs: number /* int64 */;
}

/**
 * UsageDashboardRepo is a repository leaderboard entry for one UTC day.
 * Tasks is the number of distinct tasks that touched the repository.
 */
export interface UsageDashboardRepo {
  repo: string;
  tasks: number /* int */;
}

/**
 * UsageDashboardModel is one model's totals within a UTC day. It carries the
 * full delta fold so clients can drill every dashboard panel down to the
 * model; skills and repos keep the day leaderboards' distinct-task counts.
 */
export interface UsageDashboardModel {
  model: string;
  tokens: UsageDashboardTokens;
  turns: number /* int */;
  erroredTurns: number /* int */;
  apiMs: number /* int64 */;
  wallMs: number /* int64 */;
  compactions: number /* int */;
  subagentSpawns: number /* int */;
  costUSD: number /* float64 */;
  contextWindow: number /* int */;
  tools: UsageDashboardCount[];
  toolTimings: UsageDashboardToolTiming[];
  skills: UsageDashboardCount[];
  repos: UsageDashboardRepo[];
}

/**
 * UsageDashboardHarness is one coding harness's totals within a UTC day,
 * mirroring UsageDashboardModel plus the harness-by-model cross product so a
 * harness filter can still list the models used under it.
 */
export interface UsageDashboardHarness {
  harness: string;
  tokens: UsageDashboardTokens;
  turns: number /* int */;
  erroredTurns: number /* int */;
  apiMs: number /* int64 */;
  wallMs: number /* int64 */;
  compactions: number /* int */;
  subagentSpawns: number /* int */;
  costUSD: number /* float64 */;
  tools: UsageDashboardCount[];
  toolTimings: UsageDashboardToolTiming[];
  skills: UsageDashboardCount[];
  repos: UsageDashboardRepo[];
  models: UsageDashboardModel[];
}

/**
 * UsageDashboardDay is the complete daily usage snapshot from the durable
 * cross-task rollup. Day is a UTC calendar date in YYYY-MM-DD form.
 */
export interface UsageDashboardDay {
  day: string;
  tokens: UsageDashboardTokens;
  turns: number /* int */;
  erroredTurns: number /* int */;
  apiMs: number /* int64 */;
  wallMs: number /* int64 */;
  compactions: number /* int */;
  subagentSpawns: number /* int */;
  subagentSpawnsBackground: number /* int */;
  costUSD: number /* float64 */;
  models: UsageDashboardModel[];
  harnesses: UsageDashboardHarness[];
  repos: UsageDashboardRepo[];
  skills: UsageDashboardCount[];
  tools: UsageDashboardCount[];
  toolTimings: UsageDashboardToolTiming[];
}

/**
 * UsageDashboardResp is the response for GET /api/caic/v1/usage/dashboard.
 * DataSince is the first UTC day with retained usage, or empty when no usage
 * has been recorded yet.
 */
export interface UsageDashboardResp {
  dataSince?: string;
  days: UsageDashboardDay[];
}

/** WebFetchReq is the request body for POST /api/caic/v1/web/fetch. */
export interface WebFetchReq {
  url: string;
}

/** WebFetchResp is the response for POST /api/caic/v1/web/fetch. */
export interface WebFetchResp {
  title: string;
  content: string;
}

export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}

export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any /* json.RawMessage */};
}

/**
 * AuthBootstrapResp is injected into the SPA document before the frontend
 * hydrates. It mirrors the auth-related fields otherwise fetched from
 * /server-info/config and /auth/me.
 */
export interface AuthBootstrapResp {
  authProviders: string[];
  user?: UserResp;
}

