// Code generated by gen-api-sdk. DO NOT EDIT.

// Runtime schema validators for SSE payloads.
// Each validator checks structural correctness at runtime and throws
// TypeError on mismatch. Unknown kinds pass through for forward compat.

import type { AskOption, AskQuestion, BranchAction, BranchInfo, CIStatus, CheckConclusion, CheckStatus, DiffFileStat, EventAsk, EventBackgroundCommand, EventChangeStat, EventCommitSnapshot, EventDiffStat, EventError, EventFileChange, EventInit, EventKind, EventLog, EventMessage, EventNativeSubagent, EventNativeSubagentScope, EventNativeSubagentStatus, EventRateLimit, EventRateLimitStatus, EventRepositoryCommit, EventResult, EventStats, EventSubagentEnd, EventSubagentSpawn, EventSubagentStart, EventSystem, EventText, EventTextDelta, EventThinking, EventThinkingDelta, EventTodo, EventToolInputKind, EventToolInputView, EventToolOutputDelta, EventToolResult, EventToolUse, EventUsage, EventUserInput, EventWidget, EventWidgetDelta, Forge, ForgeCheck, ForgePRState, GitOperation, GitRepositoryState, Harness, ISOTimestamp, ImageData, LocalUsage, LocalWindow, ProviderAuthKind, ProviderFetchStatus, ProviderQuota, QuotaBalance, QuotaProvider, QuotaRateLimit, Repo, RuntimeInstance, Task, TaskHistoryStreamError, TaskListEvent, TaskListSettledStatus, TaskRateLimit, TaskRepo, TaskState, TodoItem, ToolOutputContentType, UsageResp } from "./types.gen";

// ---- helpers ----

type ValidatorInput = unknown;
type ObjectValue = Record<string, ValidatorInput>;
type ValueValidator<T> = (v: ValidatorInput) => T;

function asObject(v: ValidatorInput, path: string): ObjectValue {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    throw new TypeError(path + ": expected object");
  }
  return v as ObjectValue;
}

function asString(v: ValidatorInput, path: string): string {
  if (typeof v !== "string") {
    throw new TypeError(path + ": expected string, got " + typeof v);
  }
  return v;
}

function asNumber(v: ValidatorInput, path: string): number {
  if (typeof v !== "number" || Number.isNaN(v)) {
    throw new TypeError(path + ": expected number, got " + typeof v);
  }
  return v;
}

function asBoolean(v: ValidatorInput, path: string): boolean {
  if (typeof v !== "boolean") {
    throw new TypeError(path + ": expected boolean, got " + typeof v);
  }
  return v;
}

function validateArray<T>(v: ValidatorInput, path: string, elemValidator: ValueValidator<T>): T[] {
  if (!Array.isArray(v)) {
    throw new TypeError(path + ": expected array, got " + (v === null ? "null" : typeof v));
  }
  return v.map((e) => elemValidator(e));
}

function validateRecord<T>(v: ValidatorInput, path: string, valValidator: ValueValidator<T>): Record<string, T> {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    throw new TypeError(path + ": expected object, got " + (v === null ? "null" : Array.isArray(v) ? "array" : typeof v));
  }
  const result: Record<string, T> = {};
  for (const k of Object.keys(v as ObjectValue)) {
    result[k] = valValidator((v as ObjectValue)[k]);
  }
  return result;
}

export function validateEventInit(raw: ValidatorInput): EventInit {
  const obj = asObject(raw, "EventInit");
  return {
    reportedModel: asString(obj["reportedModel"], "EventInit.reportedModel"),
    reportedEffort: (obj["reportedEffort"] === undefined || obj["reportedEffort"] === null ? undefined : asString(obj["reportedEffort"], "EventInit.reportedEffort")),
    agentVersion: asString(obj["agentVersion"], "EventInit.agentVersion"),
    sessionID: asString(obj["sessionID"], "EventInit.sessionID"),
    tools: (obj["tools"] === undefined || obj["tools"] === null ? undefined : validateArray(obj["tools"], "EventInit.tools", (v) => asString(v, "EventInit.tools[i]")) as string[]),
    cwd: asString(obj["cwd"], "EventInit.cwd"),
    harness: asString(obj["harness"], "EventInit.harness"),
  };
}

export function validateEventText(raw: ValidatorInput): EventText {
  const obj = asObject(raw, "EventText");
  return {
    text: asString(obj["text"], "EventText.text"),
  };
}

export function validateEventTextDelta(raw: ValidatorInput): EventTextDelta {
  const obj = asObject(raw, "EventTextDelta");
  return {
    text: asString(obj["text"], "EventTextDelta.text"),
  };
}

export function validateEventFileChange(raw: ValidatorInput): EventFileChange {
  const obj = asObject(raw, "EventFileChange");
  return {
    path: asString(obj["path"], "EventFileChange.path"),
    patch: asString(obj["patch"], "EventFileChange.patch"),
  };
}

export function validateEventSubagentSpawn(raw: ValidatorInput): EventSubagentSpawn {
  const obj = asObject(raw, "EventSubagentSpawn");
  return {
    agent: asString(obj["agent"], "EventSubagentSpawn.agent"),
    task: asString(obj["task"], "EventSubagentSpawn.task"),
    label: (obj["label"] === undefined || obj["label"] === null ? undefined : asString(obj["label"], "EventSubagentSpawn.label")),
    phase: (obj["phase"] === undefined || obj["phase"] === null ? undefined : asString(obj["phase"], "EventSubagentSpawn.phase")),
  };
}

export function validateEventToolInputView(raw: ValidatorInput): EventToolInputView {
  const obj = asObject(raw, "EventToolInputView");
  return {
    kind: (asString(obj["kind"], "EventToolInputView.kind") as EventToolInputKind),
    files: (obj["files"] === undefined || obj["files"] === null ? undefined : validateArray(obj["files"], "EventToolInputView.files", validateEventFileChange) as EventFileChange[]),
    subagents: (obj["subagents"] === undefined || obj["subagents"] === null ? undefined : validateArray(obj["subagents"], "EventToolInputView.subagents", validateEventSubagentSpawn) as EventSubagentSpawn[]),
  };
}

export function validateEventToolUse(raw: ValidatorInput): EventToolUse {
  const obj = asObject(raw, "EventToolUse");
  return {
    toolUseID: asString(obj["toolUseID"], "EventToolUse.toolUseID"),
    name: asString(obj["name"], "EventToolUse.name"),
    input: obj["input"],
    detail: (obj["detail"] === undefined || obj["detail"] === null ? undefined : asString(obj["detail"], "EventToolUse.detail")),
    inputView: (obj["inputView"] === undefined || obj["inputView"] === null ? undefined : validateEventToolInputView(obj["inputView"])),
    planContent: (obj["planContent"] === undefined || obj["planContent"] === null ? undefined : asString(obj["planContent"], "EventToolUse.planContent")),
    inputTruncated: (obj["inputTruncated"] === undefined || obj["inputTruncated"] === null ? undefined : asBoolean(obj["inputTruncated"], "EventToolUse.inputTruncated")),
    background: (obj["background"] === undefined || obj["background"] === null ? undefined : asBoolean(obj["background"], "EventToolUse.background")),
  };
}

export function validateEventToolResult(raw: ValidatorInput): EventToolResult {
  const obj = asObject(raw, "EventToolResult");
  return {
    toolUseID: asString(obj["toolUseID"], "EventToolResult.toolUseID"),
    duration: asNumber(obj["duration"], "EventToolResult.duration"),
    error: (obj["error"] === undefined || obj["error"] === null ? undefined : asString(obj["error"], "EventToolResult.error")),
  };
}

export function validateAskOption(raw: ValidatorInput): AskOption {
  const obj = asObject(raw, "AskOption");
  return {
    label: asString(obj["label"], "AskOption.label"),
    description: (obj["description"] === undefined || obj["description"] === null ? undefined : asString(obj["description"], "AskOption.description")),
  };
}

export function validateAskQuestion(raw: ValidatorInput): AskQuestion {
  const obj = asObject(raw, "AskQuestion");
  return {
    question: asString(obj["question"], "AskQuestion.question"),
    header: (obj["header"] === undefined || obj["header"] === null ? undefined : asString(obj["header"], "AskQuestion.header")),
    options: validateArray(obj["options"], "AskQuestion.options", validateAskOption) as AskOption[],
    multiSelect: (obj["multiSelect"] === undefined || obj["multiSelect"] === null ? undefined : asBoolean(obj["multiSelect"], "AskQuestion.multiSelect")),
  };
}

export function validateEventAsk(raw: ValidatorInput): EventAsk {
  const obj = asObject(raw, "EventAsk");
  return {
    toolUseID: asString(obj["toolUseID"], "EventAsk.toolUseID"),
    questions: validateArray(obj["questions"], "EventAsk.questions", validateAskQuestion) as AskQuestion[],
  };
}

export function validateEventUsage(raw: ValidatorInput): EventUsage {
  const obj = asObject(raw, "EventUsage");
  return {
    inputTokens: asNumber(obj["inputTokens"], "EventUsage.inputTokens"),
    outputTokens: asNumber(obj["outputTokens"], "EventUsage.outputTokens"),
    cacheCreationInputTokens: asNumber(obj["cacheCreationInputTokens"], "EventUsage.cacheCreationInputTokens"),
    cacheReadInputTokens: asNumber(obj["cacheReadInputTokens"], "EventUsage.cacheReadInputTokens"),
    reasoningOutputTokens: (obj["reasoningOutputTokens"] === undefined || obj["reasoningOutputTokens"] === null ? undefined : asNumber(obj["reasoningOutputTokens"], "EventUsage.reasoningOutputTokens")),
    reportedModel: asString(obj["reportedModel"], "EventUsage.reportedModel"),
  };
}

export function validateDiffFileStat(raw: ValidatorInput): DiffFileStat {
  const obj = asObject(raw, "DiffFileStat");
  return {
    path: asString(obj["path"], "DiffFileStat.path"),
    linesAdded: asNumber(obj["linesAdded"], "DiffFileStat.linesAdded"),
    linesDeleted: asNumber(obj["linesDeleted"], "DiffFileStat.linesDeleted"),
    oldSize: asNumber(obj["oldSize"], "DiffFileStat.oldSize"),
    newSize: asNumber(obj["newSize"], "DiffFileStat.newSize"),
    diff: (obj["diff"] === undefined || obj["diff"] === null ? undefined : asString(obj["diff"], "DiffFileStat.diff")),
  };
}

export function validateEventResult(raw: ValidatorInput): EventResult {
  const obj = asObject(raw, "EventResult");
  return {
    subtype: asString(obj["subtype"], "EventResult.subtype"),
    isError: asBoolean(obj["isError"], "EventResult.isError"),
    result: asString(obj["result"], "EventResult.result"),
    diffStat: (obj["diffStat"] === undefined || obj["diffStat"] === null ? undefined : validateArray(obj["diffStat"], "EventResult.diffStat", validateDiffFileStat) as DiffFileStat[]),
    totalCostUSD: asNumber(obj["totalCostUSD"], "EventResult.totalCostUSD"),
    duration: asNumber(obj["duration"], "EventResult.duration"),
    durationAPI: asNumber(obj["durationAPI"], "EventResult.durationAPI"),
    numTurns: asNumber(obj["numTurns"], "EventResult.numTurns"),
    usage: validateEventUsage(obj["usage"]),
  };
}

export function validateEventSystem(raw: ValidatorInput): EventSystem {
  const obj = asObject(raw, "EventSystem");
  return {
    subtype: asString(obj["subtype"], "EventSystem.subtype"),
    detail: (obj["detail"] === undefined || obj["detail"] === null ? undefined : asString(obj["detail"], "EventSystem.detail")),
    contextTokensBefore: (obj["contextTokensBefore"] === undefined || obj["contextTokensBefore"] === null ? undefined : asNumber(obj["contextTokensBefore"], "EventSystem.contextTokensBefore")),
    contextTokensAfter: (obj["contextTokensAfter"] === undefined || obj["contextTokensAfter"] === null ? undefined : asNumber(obj["contextTokensAfter"], "EventSystem.contextTokensAfter")),
  };
}

export function validateImageData(raw: ValidatorInput): ImageData {
  const obj = asObject(raw, "ImageData");
  return {
    mediaType: asString(obj["mediaType"], "ImageData.mediaType"),
    data: asString(obj["data"], "ImageData.data"),
  };
}

export function validateEventUserInput(raw: ValidatorInput): EventUserInput {
  const obj = asObject(raw, "EventUserInput");
  return {
    text: asString(obj["text"], "EventUserInput.text"),
    images: (obj["images"] === undefined || obj["images"] === null ? undefined : validateArray(obj["images"], "EventUserInput.images", validateImageData) as ImageData[]),
  };
}

export function validateTodoItem(raw: ValidatorInput): TodoItem {
  const obj = asObject(raw, "TodoItem");
  return {
    content: asString(obj["content"], "TodoItem.content"),
    status: asString(obj["status"], "TodoItem.status"),
    activeForm: (obj["activeForm"] === undefined || obj["activeForm"] === null ? undefined : asString(obj["activeForm"], "TodoItem.activeForm")),
  };
}

export function validateEventTodo(raw: ValidatorInput): EventTodo {
  const obj = asObject(raw, "EventTodo");
  return {
    toolUseID: asString(obj["toolUseID"], "EventTodo.toolUseID"),
    todos: validateArray(obj["todos"], "EventTodo.todos", validateTodoItem) as TodoItem[],
  };
}

export function validateEventDiffStat(raw: ValidatorInput): EventDiffStat {
  const obj = asObject(raw, "EventDiffStat");
  return {
    diffStat: (obj["diffStat"] === undefined || obj["diffStat"] === null ? undefined : validateArray(obj["diffStat"], "EventDiffStat.diffStat", validateDiffFileStat) as DiffFileStat[]),
  };
}

export function validateEventError(raw: ValidatorInput): EventError {
  const obj = asObject(raw, "EventError");
  return {
    err: asString(obj["err"], "EventError.err"),
    line: asString(obj["line"], "EventError.line"),
  };
}

export function validateEventThinking(raw: ValidatorInput): EventThinking {
  const obj = asObject(raw, "EventThinking");
  return {
    text: asString(obj["text"], "EventThinking.text"),
  };
}

export function validateEventThinkingDelta(raw: ValidatorInput): EventThinkingDelta {
  const obj = asObject(raw, "EventThinkingDelta");
  return {
    text: asString(obj["text"], "EventThinkingDelta.text"),
  };
}

export function validateEventSubagentStart(raw: ValidatorInput): EventSubagentStart {
  const obj = asObject(raw, "EventSubagentStart");
  return {
    taskID: asString(obj["taskID"], "EventSubagentStart.taskID"),
    description: asString(obj["description"], "EventSubagentStart.description"),
  };
}

export function validateEventSubagentEnd(raw: ValidatorInput): EventSubagentEnd {
  const obj = asObject(raw, "EventSubagentEnd");
  return {
    taskID: asString(obj["taskID"], "EventSubagentEnd.taskID"),
    status: asString(obj["status"], "EventSubagentEnd.status"),
  };
}

export function validateEventNativeSubagent(raw: ValidatorInput): EventNativeSubagent {
  const obj = asObject(raw, "EventNativeSubagent");
  return {
    toolUseID: (obj["toolUseID"] === undefined || obj["toolUseID"] === null ? undefined : asString(obj["toolUseID"], "EventNativeSubagent.toolUseID")),
    scope: (obj["scope"] === undefined || obj["scope"] === null ? undefined : (asString(obj["scope"], "EventNativeSubagent.scope") as EventNativeSubagentScope)),
    id: asString(obj["id"], "EventNativeSubagent.id"),
    groupID: (obj["groupID"] === undefined || obj["groupID"] === null ? undefined : asString(obj["groupID"], "EventNativeSubagent.groupID")),
    label: (obj["label"] === undefined || obj["label"] === null ? undefined : asString(obj["label"], "EventNativeSubagent.label")),
    prompt: (obj["prompt"] === undefined || obj["prompt"] === null ? undefined : asString(obj["prompt"], "EventNativeSubagent.prompt")),
    status: (asString(obj["status"], "EventNativeSubagent.status") as EventNativeSubagentStatus),
    result: (obj["result"] === undefined || obj["result"] === null ? undefined : asString(obj["result"], "EventNativeSubagent.result")),
    background: (obj["background"] === undefined || obj["background"] === null ? undefined : asBoolean(obj["background"], "EventNativeSubagent.background")),
  };
}

export function validateEventBackgroundCommand(raw: ValidatorInput): EventBackgroundCommand {
  const obj = asObject(raw, "EventBackgroundCommand");
  return {
    id: asString(obj["id"], "EventBackgroundCommand.id"),
    label: (obj["label"] === undefined || obj["label"] === null ? undefined : asString(obj["label"], "EventBackgroundCommand.label")),
    status: asString(obj["status"], "EventBackgroundCommand.status"),
    result: (obj["result"] === undefined || obj["result"] === null ? undefined : asString(obj["result"], "EventBackgroundCommand.result")),
    exitCode: (obj["exitCode"] === undefined || obj["exitCode"] === null ? undefined : asNumber(obj["exitCode"], "EventBackgroundCommand.exitCode")),
    outputRef: (obj["outputRef"] === undefined || obj["outputRef"] === null ? undefined : asString(obj["outputRef"], "EventBackgroundCommand.outputRef")),
    toolUseID: (obj["toolUseID"] === undefined || obj["toolUseID"] === null ? undefined : asString(obj["toolUseID"], "EventBackgroundCommand.toolUseID")),
  };
}

export function validateEventLog(raw: ValidatorInput): EventLog {
  const obj = asObject(raw, "EventLog");
  return {
    line: asString(obj["line"], "EventLog.line"),
  };
}

export function validateEventToolOutputDelta(raw: ValidatorInput): EventToolOutputDelta {
  const obj = asObject(raw, "EventToolOutputDelta");
  return {
    toolUseID: asString(obj["toolUseID"], "EventToolOutputDelta.toolUseID"),
    delta: asString(obj["delta"], "EventToolOutputDelta.delta"),
    contentType: (obj["contentType"] === undefined || obj["contentType"] === null ? undefined : (asString(obj["contentType"], "EventToolOutputDelta.contentType") as ToolOutputContentType)),
    formatted: (obj["formatted"] === undefined || obj["formatted"] === null ? undefined : asString(obj["formatted"], "EventToolOutputDelta.formatted")),
  };
}

export function validateEventWidget(raw: ValidatorInput): EventWidget {
  const obj = asObject(raw, "EventWidget");
  return {
    toolUseID: asString(obj["toolUseID"], "EventWidget.toolUseID"),
    title: asString(obj["title"], "EventWidget.title"),
    html: asString(obj["html"], "EventWidget.html"),
  };
}

export function validateEventWidgetDelta(raw: ValidatorInput): EventWidgetDelta {
  const obj = asObject(raw, "EventWidgetDelta");
  return {
    toolUseID: asString(obj["toolUseID"], "EventWidgetDelta.toolUseID"),
    delta: asString(obj["delta"], "EventWidgetDelta.delta"),
  };
}

export function validateEventRateLimit(raw: ValidatorInput): EventRateLimit {
  const obj = asObject(raw, "EventRateLimit");
  return {
    status: (asString(obj["status"], "EventRateLimit.status") as EventRateLimitStatus),
    resetsAt: (obj["resetsAt"] === undefined || obj["resetsAt"] === null ? undefined : asString(obj["resetsAt"], "EventRateLimit.resetsAt") as ISOTimestamp),
    rateLimitType: asString(obj["rateLimitType"], "EventRateLimit.rateLimitType"),
    utilization: asNumber(obj["utilization"], "EventRateLimit.utilization"),
    isUsingOverage: (obj["isUsingOverage"] === undefined || obj["isUsingOverage"] === null ? undefined : asBoolean(obj["isUsingOverage"], "EventRateLimit.isUsingOverage")),
    overageResetsAt: (obj["overageResetsAt"] === undefined || obj["overageResetsAt"] === null ? undefined : asString(obj["overageResetsAt"], "EventRateLimit.overageResetsAt") as ISOTimestamp),
  };
}

export function validateEventStats(raw: ValidatorInput): EventStats {
  const obj = asObject(raw, "EventStats");
  return {
    ts: asNumber(obj["ts"], "EventStats.ts"),
    cpuPerc: asNumber(obj["cpuPerc"], "EventStats.cpuPerc"),
    memUsed: asNumber(obj["memUsed"], "EventStats.memUsed"),
    memLimit: asNumber(obj["memLimit"], "EventStats.memLimit"),
    memPerc: asNumber(obj["memPerc"], "EventStats.memPerc"),
    netRx: asNumber(obj["netRx"], "EventStats.netRx"),
    netTx: asNumber(obj["netTx"], "EventStats.netTx"),
    blockRead: asNumber(obj["blockRead"], "EventStats.blockRead"),
    blockWrite: asNumber(obj["blockWrite"], "EventStats.blockWrite"),
    diskUsed: asNumber(obj["diskUsed"], "EventStats.diskUsed"),
  };
}

export function validateEventRepositoryCommit(raw: ValidatorInput): EventRepositoryCommit {
  const obj = asObject(raw, "EventRepositoryCommit");
  return {
    repositoryPath: asString(obj["repositoryPath"], "EventRepositoryCommit.repositoryPath"),
    branchName: asString(obj["branchName"], "EventRepositoryCommit.branchName"),
    commitHash: asString(obj["commitHash"], "EventRepositoryCommit.commitHash"),
  };
}

export function validateEventChangeStat(raw: ValidatorInput): EventChangeStat {
  const obj = asObject(raw, "EventChangeStat");
  return {
    files: asNumber(obj["files"], "EventChangeStat.files"),
    linesAdded: asNumber(obj["linesAdded"], "EventChangeStat.linesAdded"),
    linesDeleted: asNumber(obj["linesDeleted"], "EventChangeStat.linesDeleted"),
    binaryFiles: asNumber(obj["binaryFiles"], "EventChangeStat.binaryFiles"),
  };
}

export function validateEventCommitSnapshot(raw: ValidatorInput): EventCommitSnapshot {
  const obj = asObject(raw, "EventCommitSnapshot");
  return {
    repositoryCommits: validateArray(obj["repositoryCommits"], "EventCommitSnapshot.repositoryCommits", validateEventRepositoryCommit) as EventRepositoryCommit[],
    baseline: (obj["baseline"] === undefined || obj["baseline"] === null ? undefined : asBoolean(obj["baseline"], "EventCommitSnapshot.baseline")),
    changeStat: (obj["changeStat"] === undefined || obj["changeStat"] === null ? undefined : validateEventChangeStat(obj["changeStat"])),
  };
}

export function validateEventMessage(raw: ValidatorInput): EventMessage {
  const obj = asObject(raw, "EventMessage");
  const result: EventMessage = {
    kind: (asString(obj["kind"], "EventMessage.kind") as EventKind),
    ts: asNumber(obj["ts"], "EventMessage.ts"),
  };
  switch (result.kind) {
    case "init":
      result.init = validateEventInit(obj["init"]);
      break;
    case "text":
      result.text = validateEventText(obj["text"]);
      break;
    case "textDelta":
      result.textDelta = validateEventTextDelta(obj["textDelta"]);
      break;
    case "toolUse":
      result.toolUse = validateEventToolUse(obj["toolUse"]);
      break;
    case "toolResult":
      result.toolResult = validateEventToolResult(obj["toolResult"]);
      break;
    case "ask":
      result.ask = validateEventAsk(obj["ask"]);
      break;
    case "usage":
      result.usage = validateEventUsage(obj["usage"]);
      break;
    case "result":
      result.result = validateEventResult(obj["result"]);
      break;
    case "system":
      result.system = validateEventSystem(obj["system"]);
      break;
    case "userInput":
      result.userInput = validateEventUserInput(obj["userInput"]);
      break;
    case "todo":
      result.todo = validateEventTodo(obj["todo"]);
      break;
    case "diffStat":
      result.diffStat = validateEventDiffStat(obj["diffStat"]);
      break;
    case "error":
      result.error = validateEventError(obj["error"]);
      break;
    case "thinking":
      result.thinking = validateEventThinking(obj["thinking"]);
      break;
    case "thinkingDelta":
      result.thinkingDelta = validateEventThinkingDelta(obj["thinkingDelta"]);
      break;
    case "subagentStart":
      result.subagentStart = validateEventSubagentStart(obj["subagentStart"]);
      break;
    case "subagentEnd":
      result.subagentEnd = validateEventSubagentEnd(obj["subagentEnd"]);
      break;
    case "nativeSubagent":
      result.nativeSubagent = validateEventNativeSubagent(obj["nativeSubagent"]);
      break;
    case "backgroundCommand":
      result.backgroundCommand = validateEventBackgroundCommand(obj["backgroundCommand"]);
      break;
    case "log":
      result.log = validateEventLog(obj["log"]);
      break;
    case "toolOutputDelta":
      result.toolOutputDelta = validateEventToolOutputDelta(obj["toolOutputDelta"]);
      break;
    case "widget":
      result.widget = validateEventWidget(obj["widget"]);
      break;
    case "widgetDelta":
      result.widgetDelta = validateEventWidgetDelta(obj["widgetDelta"]);
      break;
    case "rateLimit":
      result.rateLimit = validateEventRateLimit(obj["rateLimit"]);
      break;
    case "stats":
      result.stats = validateEventStats(obj["stats"]);
      break;
    case "commitSnapshot":
      result.commitSnapshot = validateEventCommitSnapshot(obj["commitSnapshot"]);
      break;
    // Unknown kinds pass through.
  }
  return result;
}

export function validateTaskHistoryStreamError(raw: ValidatorInput): TaskHistoryStreamError {
  const obj = asObject(raw, "TaskHistoryStreamError");
  return {
    message: asString(obj["message"], "TaskHistoryStreamError.message"),
  };
}

export function validateTaskRepo(raw: ValidatorInput): TaskRepo {
  const obj = asObject(raw, "TaskRepo");
  return {
    name: asString(obj["name"], "TaskRepo.name"),
    baseBranch: (obj["baseBranch"] === undefined || obj["baseBranch"] === null ? undefined : asString(obj["baseBranch"], "TaskRepo.baseBranch")),
    branch: asString(obj["branch"], "TaskRepo.branch"),
    remoteURL: (obj["remoteURL"] === undefined || obj["remoteURL"] === null ? undefined : asString(obj["remoteURL"], "TaskRepo.remoteURL")),
    forge: (obj["forge"] === undefined || obj["forge"] === null ? undefined : (asString(obj["forge"], "TaskRepo.forge") as Forge)),
  };
}

export function validateGitRepositoryState(raw: ValidatorInput): GitRepositoryState {
  const obj = asObject(raw, "GitRepositoryState");
  return {
    name: asString(obj["name"], "GitRepositoryState.name"),
    branch: asString(obj["branch"], "GitRepositoryState.branch"),
    ahead: asNumber(obj["ahead"], "GitRepositoryState.ahead"),
    behind: asNumber(obj["behind"], "GitRepositoryState.behind"),
    changedFiles: asNumber(obj["changedFiles"], "GitRepositoryState.changedFiles"),
    linesAdded: asNumber(obj["linesAdded"], "GitRepositoryState.linesAdded"),
    linesDeleted: asNumber(obj["linesDeleted"], "GitRepositoryState.linesDeleted"),
    uncommittedFiles: asNumber(obj["uncommittedFiles"], "GitRepositoryState.uncommittedFiles"),
    conflicts: asNumber(obj["conflicts"], "GitRepositoryState.conflicts"),
    operation: (obj["operation"] === undefined || obj["operation"] === null ? undefined : (asString(obj["operation"], "GitRepositoryState.operation") as GitOperation)),
  };
}

export function validateForgeCheck(raw: ValidatorInput): ForgeCheck {
  const obj = asObject(raw, "ForgeCheck");
  return {
    name: asString(obj["name"], "ForgeCheck.name"),
    owner: asString(obj["owner"], "ForgeCheck.owner"),
    repo: asString(obj["repo"], "ForgeCheck.repo"),
    runID: asNumber(obj["runID"], "ForgeCheck.runID"),
    jobID: asNumber(obj["jobID"], "ForgeCheck.jobID"),
    status: (asString(obj["status"], "ForgeCheck.status") as CheckStatus),
    conclusion: (asString(obj["conclusion"], "ForgeCheck.conclusion") as CheckConclusion),
    queuedAt: (obj["queuedAt"] === undefined || obj["queuedAt"] === null ? undefined : asString(obj["queuedAt"], "ForgeCheck.queuedAt") as ISOTimestamp),
    startedAt: (obj["startedAt"] === undefined || obj["startedAt"] === null ? undefined : asString(obj["startedAt"], "ForgeCheck.startedAt") as ISOTimestamp),
    completedAt: (obj["completedAt"] === undefined || obj["completedAt"] === null ? undefined : asString(obj["completedAt"], "ForgeCheck.completedAt") as ISOTimestamp),
  };
}

export function validateRuntimeInstance(raw: ValidatorInput): RuntimeInstance {
  const obj = asObject(raw, "RuntimeInstance");
  return {
    id: asString(obj["id"], "RuntimeInstance.id"),
    runtimeName: (obj["runtimeName"] === undefined || obj["runtimeName"] === null ? undefined : asString(obj["runtimeName"], "RuntimeInstance.runtimeName")),
    tailscale: (obj["tailscale"] === undefined || obj["tailscale"] === null ? undefined : asString(obj["tailscale"], "RuntimeInstance.tailscale")),
    usb: (obj["usb"] === undefined || obj["usb"] === null ? undefined : asBoolean(obj["usb"], "RuntimeInstance.usb")),
    display: (obj["display"] === undefined || obj["display"] === null ? undefined : asBoolean(obj["display"], "RuntimeInstance.display")),
    sudo: (obj["sudo"] === undefined || obj["sudo"] === null ? undefined : asBoolean(obj["sudo"], "RuntimeInstance.sudo")),
    sudoPassword: (obj["sudoPassword"] === undefined || obj["sudoPassword"] === null ? undefined : asString(obj["sudoPassword"], "RuntimeInstance.sudoPassword")),
    vncPort: (obj["vncPort"] === undefined || obj["vncPort"] === null ? undefined : asNumber(obj["vncPort"], "RuntimeInstance.vncPort")),
  };
}

export function validateTaskRateLimit(raw: ValidatorInput): TaskRateLimit {
  const obj = asObject(raw, "TaskRateLimit");
  return {
    blocked: asBoolean(obj["blocked"], "TaskRateLimit.blocked"),
    quotaGroup: (obj["quotaGroup"] === undefined || obj["quotaGroup"] === null ? undefined : (asString(obj["quotaGroup"], "TaskRateLimit.quotaGroup") as QuotaProvider)),
    window: (obj["window"] === undefined || obj["window"] === null ? undefined : asString(obj["window"], "TaskRateLimit.window")),
    resetsAt: (obj["resetsAt"] === undefined || obj["resetsAt"] === null ? undefined : asString(obj["resetsAt"], "TaskRateLimit.resetsAt") as ISOTimestamp),
  };
}

export function validateTask(raw: ValidatorInput): Task {
  const obj = asObject(raw, "Task");
  return {
    id: asString(obj["id"], "Task.id"),
    initialPrompt: asString(obj["initialPrompt"], "Task.initialPrompt"),
    title: asString(obj["title"], "Task.title"),
    repos: (obj["repos"] === undefined || obj["repos"] === null ? undefined : validateArray(obj["repos"], "Task.repos", validateTaskRepo) as TaskRepo[]),
    state: (asString(obj["state"], "Task.state") as TaskState),
    stateUpdatedAt: asString(obj["stateUpdatedAt"], "Task.stateUpdatedAt") as ISOTimestamp,
    diffStat: (obj["diffStat"] === undefined || obj["diffStat"] === null ? undefined : validateArray(obj["diffStat"], "Task.diffStat", validateDiffFileStat) as DiffFileStat[]),
    repoStates: (obj["repoStates"] === undefined || obj["repoStates"] === null ? undefined : validateArray(obj["repoStates"], "Task.repoStates", validateGitRepositoryState) as GitRepositoryState[]),
    costUSD: asNumber(obj["costUSD"], "Task.costUSD"),
    duration: asNumber(obj["duration"], "Task.duration"),
    numTurns: asNumber(obj["numTurns"], "Task.numTurns"),
    cumulativeInputTokens: asNumber(obj["cumulativeInputTokens"], "Task.cumulativeInputTokens"),
    cumulativeOutputTokens: asNumber(obj["cumulativeOutputTokens"], "Task.cumulativeOutputTokens"),
    cumulativeCacheCreationInputTokens: asNumber(obj["cumulativeCacheCreationInputTokens"], "Task.cumulativeCacheCreationInputTokens"),
    cumulativeCacheReadInputTokens: asNumber(obj["cumulativeCacheReadInputTokens"], "Task.cumulativeCacheReadInputTokens"),
    activeInputTokens: asNumber(obj["activeInputTokens"], "Task.activeInputTokens"),
    activeCacheReadTokens: asNumber(obj["activeCacheReadTokens"], "Task.activeCacheReadTokens"),
    cacheTTLSeconds: (obj["cacheTTLSeconds"] === undefined || obj["cacheTTLSeconds"] === null ? undefined : asNumber(obj["cacheTTLSeconds"], "Task.cacheTTLSeconds")),
    cacheExpiresAt: (obj["cacheExpiresAt"] === undefined || obj["cacheExpiresAt"] === null ? undefined : asString(obj["cacheExpiresAt"], "Task.cacheExpiresAt") as ISOTimestamp),
    stoppedDiskUsedBytes: asNumber(obj["stoppedDiskUsedBytes"], "Task.stoppedDiskUsedBytes"),
    contextWindowLimit: asNumber(obj["contextWindowLimit"], "Task.contextWindowLimit"),
    error: (obj["error"] === undefined || obj["error"] === null ? undefined : asString(obj["error"], "Task.error")),
    result: (obj["result"] === undefined || obj["result"] === null ? undefined : asString(obj["result"], "Task.result")),
    forgeOwner: (obj["forgeOwner"] === undefined || obj["forgeOwner"] === null ? undefined : asString(obj["forgeOwner"], "Task.forgeOwner")),
    forgeRepo: (obj["forgeRepo"] === undefined || obj["forgeRepo"] === null ? undefined : asString(obj["forgeRepo"], "Task.forgeRepo")),
    forgePR: (obj["forgePR"] === undefined || obj["forgePR"] === null ? undefined : asNumber(obj["forgePR"], "Task.forgePR")),
    forgePRState: (obj["forgePRState"] === undefined || obj["forgePRState"] === null ? undefined : (asString(obj["forgePRState"], "Task.forgePRState") as ForgePRState)),
    forgeIssue: (obj["forgeIssue"] === undefined || obj["forgeIssue"] === null ? undefined : asNumber(obj["forgeIssue"], "Task.forgeIssue")),
    ciStatus: (obj["ciStatus"] === undefined || obj["ciStatus"] === null ? undefined : (asString(obj["ciStatus"], "Task.ciStatus") as CIStatus)),
    ciChecks: (obj["ciChecks"] === undefined || obj["ciChecks"] === null ? undefined : validateArray(obj["ciChecks"], "Task.ciChecks", validateForgeCheck) as ForgeCheck[]),
    owner: (obj["owner"] === undefined || obj["owner"] === null ? undefined : asString(obj["owner"], "Task.owner")),
    forkedFromTaskID: (obj["forkedFromTaskID"] === undefined || obj["forkedFromTaskID"] === null ? undefined : asString(obj["forkedFromTaskID"], "Task.forkedFromTaskID")),
    parentTaskID: (obj["parentTaskID"] === undefined || obj["parentTaskID"] === null ? undefined : asString(obj["parentTaskID"], "Task.parentTaskID")),
    caicMCPEnabled: (obj["caicMCPEnabled"] === undefined || obj["caicMCPEnabled"] === null ? undefined : asBoolean(obj["caicMCPEnabled"], "Task.caicMCPEnabled")),
    harness: (asString(obj["harness"], "Task.harness") as Harness),
    requestedModel: (obj["requestedModel"] === undefined || obj["requestedModel"] === null ? undefined : asString(obj["requestedModel"], "Task.requestedModel")),
    requestedEffort: (obj["requestedEffort"] === undefined || obj["requestedEffort"] === null ? undefined : asString(obj["requestedEffort"], "Task.requestedEffort")),
    reportedModel: (obj["reportedModel"] === undefined || obj["reportedModel"] === null ? undefined : asString(obj["reportedModel"], "Task.reportedModel")),
    reportedEffort: (obj["reportedEffort"] === undefined || obj["reportedEffort"] === null ? undefined : asString(obj["reportedEffort"], "Task.reportedEffort")),
    agentVersion: (obj["agentVersion"] === undefined || obj["agentVersion"] === null ? undefined : asString(obj["agentVersion"], "Task.agentVersion")),
    sessionID: (obj["sessionID"] === undefined || obj["sessionID"] === null ? undefined : asString(obj["sessionID"], "Task.sessionID")),
    startedAt: (obj["startedAt"] === undefined || obj["startedAt"] === null ? undefined : asString(obj["startedAt"], "Task.startedAt") as ISOTimestamp),
    turnStartedAt: (obj["turnStartedAt"] === undefined || obj["turnStartedAt"] === null ? undefined : asString(obj["turnStartedAt"], "Task.turnStartedAt") as ISOTimestamp),
    inPlanMode: (obj["inPlanMode"] === undefined || obj["inPlanMode"] === null ? undefined : asBoolean(obj["inPlanMode"], "Task.inPlanMode")),
    planContent: (obj["planContent"] === undefined || obj["planContent"] === null ? undefined : asString(obj["planContent"], "Task.planContent")),
    runtime: validateRuntimeInstance(obj["runtime"]),
    rateLimit: (obj["rateLimit"] === undefined || obj["rateLimit"] === null ? undefined : validateTaskRateLimit(obj["rateLimit"])),
    gitHubToken: (obj["gitHubToken"] === undefined || obj["gitHubToken"] === null ? undefined : asBoolean(obj["gitHubToken"], "Task.gitHubToken")),
  };
}

export function validateBranchInfo(raw: ValidatorInput): BranchInfo {
  const obj = asObject(raw, "BranchInfo");
  return {
    name: asString(obj["name"], "BranchInfo.name"),
    remote: (obj["remote"] === undefined || obj["remote"] === null ? undefined : asString(obj["remote"], "BranchInfo.remote")),
    action: (obj["action"] === undefined || obj["action"] === null ? undefined : (asString(obj["action"], "BranchInfo.action") as BranchAction)),
  };
}

export function validateRepo(raw: ValidatorInput): Repo {
  const obj = asObject(raw, "Repo");
  return {
    path: asString(obj["path"], "Repo.path"),
    branch: asString(obj["branch"], "Repo.branch"),
    baseBranch: validateBranchInfo(obj["baseBranch"]),
    remoteURL: (obj["remoteURL"] === undefined || obj["remoteURL"] === null ? undefined : asString(obj["remoteURL"], "Repo.remoteURL")),
    forge: (obj["forge"] === undefined || obj["forge"] === null ? undefined : (asString(obj["forge"], "Repo.forge") as Forge)),
    ci: (obj["ci"] === undefined || obj["ci"] === null ? undefined : (asString(obj["ci"], "Repo.ci") as CIStatus)),
    ciChecks: (obj["ciChecks"] === undefined || obj["ciChecks"] === null ? undefined : validateArray(obj["ciChecks"], "Repo.ciChecks", validateForgeCheck) as ForgeCheck[]),
    checksDate: (obj["checksDate"] === undefined || obj["checksDate"] === null ? undefined : asString(obj["checksDate"], "Repo.checksDate") as ISOTimestamp),
  };
}

export function validateTaskListSettledStatus(raw: ValidatorInput): TaskListSettledStatus {
  const obj = asObject(raw, "TaskListSettledStatus");
  return {
    loading: asBoolean(obj["loading"], "TaskListSettledStatus.loading"),
    error: asString(obj["error"], "TaskListSettledStatus.error"),
  };
}

export function validateTaskListEvent(raw: ValidatorInput): TaskListEvent {
  const obj = asObject(raw, "TaskListEvent");
  const result: TaskListEvent = {
    kind: asString(obj["kind"], "TaskListEvent.kind"),
  };
  switch (result.kind) {
    case "snapshot":
      result.snapshot = validateArray(obj["snapshot"], "TaskListEvent.snapshot", validateTask) as Task[];
      break;
    case "upsert":
      result.upsert = validateTask(obj["upsert"]);
      break;
    case "patch":
      result.patch = validateRecord(obj["patch"], "TaskListEvent.patch", (v) => v) as { [key: string]: any /* json.RawMessage */ };
      break;
    case "delete":
      result.delete = asString(obj["delete"], "TaskListEvent.delete");
      break;
    case "repos":
      result.repos = validateArray(obj["repos"], "TaskListEvent.repos", validateRepo) as Repo[];
      break;
    case "warning":
      result.warning = asString(obj["warning"], "TaskListEvent.warning");
      break;
    case "status":
      result.status = validateTaskListSettledStatus(obj["status"]);
      break;
    // Unknown kinds pass through.
  }
  return result;
}

export function validateQuotaRateLimit(raw: ValidatorInput): QuotaRateLimit {
  const obj = asObject(raw, "QuotaRateLimit");
  return {
    window: asString(obj["window"], "QuotaRateLimit.window"),
    usedPct: asNumber(obj["usedPct"], "QuotaRateLimit.usedPct"),
    resetsAt: (obj["resetsAt"] === undefined || obj["resetsAt"] === null ? undefined : asString(obj["resetsAt"], "QuotaRateLimit.resetsAt") as ISOTimestamp),
  };
}

export function validateQuotaBalance(raw: ValidatorInput): QuotaBalance {
  const obj = asObject(raw, "QuotaBalance");
  return {
    currency: asString(obj["currency"], "QuotaBalance.currency"),
    total: asNumber(obj["total"], "QuotaBalance.total"),
    granted: (obj["granted"] === undefined || obj["granted"] === null ? undefined : asNumber(obj["granted"], "QuotaBalance.granted")),
    toppedUp: (obj["toppedUp"] === undefined || obj["toppedUp"] === null ? undefined : asNumber(obj["toppedUp"], "QuotaBalance.toppedUp")),
    extraEnabled: (obj["extraEnabled"] === undefined || obj["extraEnabled"] === null ? undefined : asBoolean(obj["extraEnabled"], "QuotaBalance.extraEnabled")),
    usedCredits: (obj["usedCredits"] === undefined || obj["usedCredits"] === null ? undefined : asNumber(obj["usedCredits"], "QuotaBalance.usedCredits")),
    monthlyLimit: (obj["monthlyLimit"] === undefined || obj["monthlyLimit"] === null ? undefined : asNumber(obj["monthlyLimit"], "QuotaBalance.monthlyLimit")),
    usedPct: (obj["usedPct"] === undefined || obj["usedPct"] === null ? undefined : asNumber(obj["usedPct"], "QuotaBalance.usedPct")),
  };
}

export function validateProviderQuota(raw: ValidatorInput): ProviderQuota {
  const obj = asObject(raw, "ProviderQuota");
  return {
    provider: (asString(obj["provider"], "ProviderQuota.provider") as QuotaProvider),
    label: asString(obj["label"], "ProviderQuota.label"),
    logoUrl: asString(obj["logoUrl"], "ProviderQuota.logoUrl"),
    authKind: (asString(obj["authKind"], "ProviderQuota.authKind") as ProviderAuthKind),
    usageUrl: asString(obj["usageUrl"], "ProviderQuota.usageUrl"),
    fetchStatus: (asString(obj["fetchStatus"], "ProviderQuota.fetchStatus") as ProviderFetchStatus),
    rateLimits: (obj["rateLimits"] === undefined || obj["rateLimits"] === null ? undefined : validateArray(obj["rateLimits"], "ProviderQuota.rateLimits", validateQuotaRateLimit) as QuotaRateLimit[]),
    balance: (obj["balance"] === undefined || obj["balance"] === null ? undefined : validateQuotaBalance(obj["balance"])),
    pricingPhase: (obj["pricingPhase"] === undefined || obj["pricingPhase"] === null ? undefined : asString(obj["pricingPhase"], "ProviderQuota.pricingPhase")),
    pricingTransitionAt: (obj["pricingTransitionAt"] === undefined || obj["pricingTransitionAt"] === null ? undefined : asString(obj["pricingTransitionAt"], "ProviderQuota.pricingTransitionAt") as ISOTimestamp),
  };
}

export function validateLocalWindow(raw: ValidatorInput): LocalWindow {
  const obj = asObject(raw, "LocalWindow");
  return {
    duration: asString(obj["duration"], "LocalWindow.duration"),
    costUSD: asNumber(obj["costUSD"], "LocalWindow.costUSD"),
    inputTokens: asNumber(obj["inputTokens"], "LocalWindow.inputTokens"),
    outputTokens: asNumber(obj["outputTokens"], "LocalWindow.outputTokens"),
  };
}

export function validateLocalUsage(raw: ValidatorInput): LocalUsage {
  const obj = asObject(raw, "LocalUsage");
  return {
    windows: validateArray(obj["windows"], "LocalUsage.windows", validateLocalWindow) as LocalWindow[],
  };
}

export function validateUsageResp(raw: ValidatorInput): UsageResp {
  const obj = asObject(raw, "UsageResp");
  return {
    providers: (obj["providers"] === undefined || obj["providers"] === null ? undefined : validateArray(obj["providers"], "UsageResp.providers", validateProviderQuota) as ProviderQuota[]),
    local: validateLocalUsage(obj["local"]),
  };
}

