// Code generated by gen-api-sdk. DO NOT EDIT.
@file:UseSerializers(InstantSerializer::class)

package com.caic.sdk.v1

import java.time.Instant
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

/** Serializes [Instant] as an ISO 8601 string. */
object InstantSerializer : KSerializer<Instant> {
    override val descriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

@Serializable(with = CIStatusSerializer::class)
sealed interface CIStatus {
    val value: String
    @Serializable
    data object Pending : CIStatus {
        override val value = "pending"
    }
    @Serializable
    data object Success : CIStatus {
        override val value = "success"
    }
    @Serializable
    data object Failure : CIStatus {
        override val value = "failure"
    }
    @Serializable
    data class Other(override val value: String) : CIStatus
}

object CIStatusSerializer : KSerializer<CIStatus> {
    override val descriptor = PrimitiveSerialDescriptor("CIStatus", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: CIStatus) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): CIStatus {
        val v = decoder.decodeString()
        return when (v) {
            "pending" -> CIStatus.Pending
            "success" -> CIStatus.Success
            "failure" -> CIStatus.Failure
            else -> CIStatus.Other(v)
        }
    }
}

@Serializable(with = CheckConclusionSerializer::class)
sealed interface CheckConclusion {
    val value: String
    @Serializable
    data object Success : CheckConclusion {
        override val value = "success"
    }
    @Serializable
    data object Failure : CheckConclusion {
        override val value = "failure"
    }
    @Serializable
    data object Neutral : CheckConclusion {
        override val value = "neutral"
    }
    @Serializable
    data object Skipped : CheckConclusion {
        override val value = "skipped"
    }
    @Serializable
    data object Cancelled : CheckConclusion {
        override val value = "cancelled"
    }
    @Serializable
    data object TimedOut : CheckConclusion {
        override val value = "timed_out"
    }
    @Serializable
    data object ActionRequired : CheckConclusion {
        override val value = "action_required"
    }
    @Serializable
    data object Stale : CheckConclusion {
        override val value = "stale"
    }
    @Serializable
    data class Other(override val value: String) : CheckConclusion
}

object CheckConclusionSerializer : KSerializer<CheckConclusion> {
    override val descriptor = PrimitiveSerialDescriptor("CheckConclusion", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: CheckConclusion) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): CheckConclusion {
        val v = decoder.decodeString()
        return when (v) {
            "success" -> CheckConclusion.Success
            "failure" -> CheckConclusion.Failure
            "neutral" -> CheckConclusion.Neutral
            "skipped" -> CheckConclusion.Skipped
            "cancelled" -> CheckConclusion.Cancelled
            "timed_out" -> CheckConclusion.TimedOut
            "action_required" -> CheckConclusion.ActionRequired
            "stale" -> CheckConclusion.Stale
            else -> CheckConclusion.Other(v)
        }
    }
}

@Serializable(with = CheckStatusSerializer::class)
sealed interface CheckStatus {
    val value: String
    @Serializable
    data object Queued : CheckStatus {
        override val value = "queued"
    }
    @Serializable
    data object InProgress : CheckStatus {
        override val value = "in_progress"
    }
    @Serializable
    data object Completed : CheckStatus {
        override val value = "completed"
    }
    @Serializable
    data class Other(override val value: String) : CheckStatus
}

object CheckStatusSerializer : KSerializer<CheckStatus> {
    override val descriptor = PrimitiveSerialDescriptor("CheckStatus", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: CheckStatus) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): CheckStatus {
        val v = decoder.decodeString()
        return when (v) {
            "queued" -> CheckStatus.Queued
            "in_progress" -> CheckStatus.InProgress
            "completed" -> CheckStatus.Completed
            else -> CheckStatus.Other(v)
        }
    }
}

@Serializable(with = EventKindSerializer::class)
sealed interface EventKind {
    val value: String
    @Serializable
    data object Init : EventKind {
        override val value = "init"
    }
    @Serializable
    data object Text : EventKind {
        override val value = "text"
    }
    @Serializable
    data object TextDelta : EventKind {
        override val value = "textDelta"
    }
    @Serializable
    data object ToolUse : EventKind {
        override val value = "toolUse"
    }
    @Serializable
    data object ToolResult : EventKind {
        override val value = "toolResult"
    }
    @Serializable
    data object Ask : EventKind {
        override val value = "ask"
    }
    @Serializable
    data object Usage : EventKind {
        override val value = "usage"
    }
    @Serializable
    data object Result : EventKind {
        override val value = "result"
    }
    @Serializable
    data object System : EventKind {
        override val value = "system"
    }
    @Serializable
    data object UserInput : EventKind {
        override val value = "userInput"
    }
    @Serializable
    data object Todo : EventKind {
        override val value = "todo"
    }
    @Serializable
    data object DiffStat : EventKind {
        override val value = "diffStat"
    }
    @Serializable
    data object Error : EventKind {
        override val value = "error"
    }
    @Serializable
    data object Thinking : EventKind {
        override val value = "thinking"
    }
    @Serializable
    data object ThinkingDelta : EventKind {
        override val value = "thinkingDelta"
    }
    @Serializable
    data object SubagentStart : EventKind {
        override val value = "subagentStart"
    }
    @Serializable
    data object SubagentEnd : EventKind {
        override val value = "subagentEnd"
    }
    @Serializable
    data object Log : EventKind {
        override val value = "log"
    }
    @Serializable
    data object ToolOutputDelta : EventKind {
        override val value = "toolOutputDelta"
    }
    @Serializable
    data object Widget : EventKind {
        override val value = "widget"
    }
    @Serializable
    data object WidgetDelta : EventKind {
        override val value = "widgetDelta"
    }
    @Serializable
    data object RateLimit : EventKind {
        override val value = "rateLimit"
    }
    @Serializable
    data object Stats : EventKind {
        override val value = "stats"
    }
    @Serializable
    data class Other(override val value: String) : EventKind
}

object EventKindSerializer : KSerializer<EventKind> {
    override val descriptor = PrimitiveSerialDescriptor("EventKind", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: EventKind) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): EventKind {
        val v = decoder.decodeString()
        return when (v) {
            "init" -> EventKind.Init
            "text" -> EventKind.Text
            "textDelta" -> EventKind.TextDelta
            "toolUse" -> EventKind.ToolUse
            "toolResult" -> EventKind.ToolResult
            "ask" -> EventKind.Ask
            "usage" -> EventKind.Usage
            "result" -> EventKind.Result
            "system" -> EventKind.System
            "userInput" -> EventKind.UserInput
            "todo" -> EventKind.Todo
            "diffStat" -> EventKind.DiffStat
            "error" -> EventKind.Error
            "thinking" -> EventKind.Thinking
            "thinkingDelta" -> EventKind.ThinkingDelta
            "subagentStart" -> EventKind.SubagentStart
            "subagentEnd" -> EventKind.SubagentEnd
            "log" -> EventKind.Log
            "toolOutputDelta" -> EventKind.ToolOutputDelta
            "widget" -> EventKind.Widget
            "widgetDelta" -> EventKind.WidgetDelta
            "rateLimit" -> EventKind.RateLimit
            "stats" -> EventKind.Stats
            else -> EventKind.Other(v)
        }
    }
}

@Serializable(with = ForgeSerializer::class)
sealed interface Forge {
    val value: String
    @Serializable
    data object GitHub : Forge {
        override val value = "github"
    }
    @Serializable
    data object GitLab : Forge {
        override val value = "gitlab"
    }
    @Serializable
    data class Other(override val value: String) : Forge
}

object ForgeSerializer : KSerializer<Forge> {
    override val descriptor = PrimitiveSerialDescriptor("Forge", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Forge) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Forge {
        val v = decoder.decodeString()
        return when (v) {
            "github" -> Forge.GitHub
            "gitlab" -> Forge.GitLab
            else -> Forge.Other(v)
        }
    }
}

@Serializable(with = ForgePRStateSerializer::class)
sealed interface ForgePRState {
    val value: String
    @Serializable
    data object Open : ForgePRState {
        override val value = "open"
    }
    @Serializable
    data object Closed : ForgePRState {
        override val value = "closed"
    }
    @Serializable
    data object Merged : ForgePRState {
        override val value = "merged"
    }
    @Serializable
    data class Other(override val value: String) : ForgePRState
}

object ForgePRStateSerializer : KSerializer<ForgePRState> {
    override val descriptor = PrimitiveSerialDescriptor("ForgePRState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ForgePRState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): ForgePRState {
        val v = decoder.decodeString()
        return when (v) {
            "open" -> ForgePRState.Open
            "closed" -> ForgePRState.Closed
            "merged" -> ForgePRState.Merged
            else -> ForgePRState.Other(v)
        }
    }
}

@Serializable(with = HarnessSerializer::class)
sealed interface Harness {
    val value: String
    @Serializable
    data object Claude : Harness {
        override val value = "claude"
    }
    @Serializable
    data object Codex : Harness {
        override val value = "codex"
    }
    @Serializable
    data object OpenCode : Harness {
        override val value = "opencode"
    }
    @Serializable
    data object Pi : Harness {
        override val value = "pi"
    }
    @Serializable
    data class Other(override val value: String) : Harness
}

object HarnessSerializer : KSerializer<Harness> {
    override val descriptor = PrimitiveSerialDescriptor("Harness", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Harness) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Harness {
        val v = decoder.decodeString()
        return when (v) {
            "claude" -> Harness.Claude
            "codex" -> Harness.Codex
            "opencode" -> Harness.OpenCode
            "pi" -> Harness.Pi
            else -> Harness.Other(v)
        }
    }
}

@Serializable(with = OAuthGrantStatusSerializer::class)
sealed interface OAuthGrantStatus {
    val value: String
    @Serializable
    data object Active : OAuthGrantStatus {
        override val value = "active"
    }
    @Serializable
    data object Expired : OAuthGrantStatus {
        override val value = "expired"
    }
    @Serializable
    data object Revoked : OAuthGrantStatus {
        override val value = "revoked"
    }
    @Serializable
    data class Other(override val value: String) : OAuthGrantStatus
}

object OAuthGrantStatusSerializer : KSerializer<OAuthGrantStatus> {
    override val descriptor = PrimitiveSerialDescriptor("OAuthGrantStatus", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: OAuthGrantStatus) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): OAuthGrantStatus {
        val v = decoder.decodeString()
        return when (v) {
            "active" -> OAuthGrantStatus.Active
            "expired" -> OAuthGrantStatus.Expired
            "revoked" -> OAuthGrantStatus.Revoked
            else -> OAuthGrantStatus.Other(v)
        }
    }
}

@Serializable(with = PlatformSerializer::class)
sealed interface Platform {
    val value: String
    @Serializable
    data object Default : Platform {
        override val value = ""
    }
    @Serializable
    data object LinuxARM64 : Platform {
        override val value = "linux/arm64"
    }
    @Serializable
    data object LinuxAMD64 : Platform {
        override val value = "linux/amd64"
    }
    @Serializable
    data class Other(override val value: String) : Platform
}

object PlatformSerializer : KSerializer<Platform> {
    override val descriptor = PrimitiveSerialDescriptor("Platform", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Platform) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Platform {
        val v = decoder.decodeString()
        return when (v) {
            "" -> Platform.Default
            "linux/arm64" -> Platform.LinuxARM64
            "linux/amd64" -> Platform.LinuxAMD64
            else -> Platform.Other(v)
        }
    }
}

@Serializable(with = SyncTargetSerializer::class)
sealed interface SyncTarget {
    val value: String
    @Serializable
    data object Branch : SyncTarget {
        override val value = "branch"
    }
    @Serializable
    data object Default : SyncTarget {
        override val value = "default"
    }
    @Serializable
    data class Other(override val value: String) : SyncTarget
}

object SyncTargetSerializer : KSerializer<SyncTarget> {
    override val descriptor = PrimitiveSerialDescriptor("SyncTarget", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: SyncTarget) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): SyncTarget {
        val v = decoder.decodeString()
        return when (v) {
            "branch" -> SyncTarget.Branch
            "default" -> SyncTarget.Default
            else -> SyncTarget.Other(v)
        }
    }
}

@Serializable(with = TaskStateSerializer::class)
sealed interface TaskState {
    val value: String
    @Serializable
    data object Pending : TaskState {
        override val value = "pending"
    }
    @Serializable
    data object Branching : TaskState {
        override val value = "branching"
    }
    @Serializable
    data object Provisioning : TaskState {
        override val value = "provisioning"
    }
    @Serializable
    data object Starting : TaskState {
        override val value = "starting"
    }
    @Serializable
    data object Running : TaskState {
        override val value = "running"
    }
    @Serializable
    data object Waiting : TaskState {
        override val value = "waiting"
    }
    @Serializable
    data object Asking : TaskState {
        override val value = "asking"
    }
    @Serializable
    data object HasPlan : TaskState {
        override val value = "has_plan"
    }
    @Serializable
    data object Pulling : TaskState {
        override val value = "pulling"
    }
    @Serializable
    data object Pushing : TaskState {
        override val value = "pushing"
    }
    @Serializable
    data object Stopping : TaskState {
        override val value = "stopping"
    }
    @Serializable
    data object Stopped : TaskState {
        override val value = "stopped"
    }
    @Serializable
    data object Purging : TaskState {
        override val value = "purging"
    }
    @Serializable
    data object Crashed : TaskState {
        override val value = "crashed"
    }
    @Serializable
    data object Failed : TaskState {
        override val value = "failed"
    }
    @Serializable
    data object Purged : TaskState {
        override val value = "purged"
    }
    @Serializable
    data class Other(override val value: String) : TaskState
}

object TaskStateSerializer : KSerializer<TaskState> {
    override val descriptor = PrimitiveSerialDescriptor("TaskState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: TaskState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): TaskState {
        val v = decoder.decodeString()
        return when (v) {
            "pending" -> TaskState.Pending
            "branching" -> TaskState.Branching
            "provisioning" -> TaskState.Provisioning
            "starting" -> TaskState.Starting
            "running" -> TaskState.Running
            "waiting" -> TaskState.Waiting
            "asking" -> TaskState.Asking
            "has_plan" -> TaskState.HasPlan
            "pulling" -> TaskState.Pulling
            "pushing" -> TaskState.Pushing
            "stopping" -> TaskState.Stopping
            "stopped" -> TaskState.Stopped
            "purging" -> TaskState.Purging
            "crashed" -> TaskState.Crashed
            "failed" -> TaskState.Failed
            "purged" -> TaskState.Purged
            else -> TaskState.Other(v)
        }
    }
}

@Serializable(with = ToolOutputContentTypeSerializer::class)
sealed interface ToolOutputContentType {
    val value: String
    @Serializable
    data object ToolOutputText : ToolOutputContentType {
        override val value = "text"
    }
    @Serializable
    data object ToolOutputJSON : ToolOutputContentType {
        override val value = "json"
    }
    @Serializable
    data object ToolOutputMarkdown : ToolOutputContentType {
        override val value = "markdown"
    }
    @Serializable
    data class Other(override val value: String) : ToolOutputContentType
}

object ToolOutputContentTypeSerializer : KSerializer<ToolOutputContentType> {
    override val descriptor = PrimitiveSerialDescriptor("ToolOutputContentType", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ToolOutputContentType) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): ToolOutputContentType {
        val v = decoder.decodeString()
        return when (v) {
            "text" -> ToolOutputContentType.ToolOutputText
            "json" -> ToolOutputContentType.ToolOutputJSON
            "markdown" -> ToolOutputContentType.ToolOutputMarkdown
            else -> ToolOutputContentType.Other(v)
        }
    }
}

@Serializable(with = VoiceGatewayModeSerializer::class)
sealed interface VoiceGatewayMode {
    val value: String
    @Serializable
    data object Disabled : VoiceGatewayMode {
        override val value = "disabled"
    }
    @Serializable
    data object Embedded : VoiceGatewayMode {
        override val value = "embedded"
    }
    @Serializable
    data object External : VoiceGatewayMode {
        override val value = "external"
    }
    @Serializable
    data class Other(override val value: String) : VoiceGatewayMode
}

object VoiceGatewayModeSerializer : KSerializer<VoiceGatewayMode> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceGatewayMode", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceGatewayMode) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceGatewayMode {
        val v = decoder.decodeString()
        return when (v) {
            "disabled" -> VoiceGatewayMode.Disabled
            "embedded" -> VoiceGatewayMode.Embedded
            "external" -> VoiceGatewayMode.External
            else -> VoiceGatewayMode.Other(v)
        }
    }
}

object ErrorCodes {
    const val BadRequest = "BAD_REQUEST"
    const val NotFound = "NOT_FOUND"
    const val Conflict = "CONFLICT"
    const val InternalError = "INTERNAL_ERROR"
}

typealias DiffStat = List<DiffFileStat>

/** VoiceGatewayMetadata reports structured voice gateway support. */
@Serializable
data class VoiceGatewayMetadata(
    val mode: VoiceGatewayMode,
    val url: String? = null,
    val authRequired: Boolean? = null,
    val capabilities: List<String>? = null,
)

/** Config reports server capabilities to the frontend. */
@Serializable
data class Config(
    val version: String? = null,
    val displayName: String,
    val tailscaleAvailable: Boolean,
    val usbAvailable: Boolean,
    val displayAvailable: Boolean,
    val sudoAvailable: Boolean,
    val gitHubTokenAvailable: Boolean,
    val voiceGateway: VoiceGatewayMetadata,
    val gitHubAppEnabled: Boolean? = null,
    /** e.g. ["github","gitlab"] */
    val authProviders: List<String>? = null,
)

/** VersionResp is the response for GET /api/caic/v1/server/version. */
@Serializable
data class VersionResp(
    val current: String,
    /** empty when check failed */
    val latest: String? = null,
    /** true when Latest > Current */
    val updateAvailable: Boolean,
    /** non-empty when the GitHub check failed */
    val checkError: String? = null,
    /** true when autoupdate schedule is configured */
    val autoUpdateEnabled: Boolean,
)

/** UpdateResp is the response for POST /api/caic/v1/server/update. */
@Serializable
data class UpdateResp(
    /** "started" or "already_up_to_date" */
    val status: String,
)

/** UserResp is returned by GET /auth/me. */
@Serializable
data class UserResp(
    val id: String,
    val provider: String,
    val username: String,
    @SerialName("avatarURL") val avatarURL: String? = null,
)

/** StatusResp is a common response for mutation endpoints. */
@Serializable
data class StatusResp(val status: String)

/** RepoPrefsResp holds per-repository preferences. */
@Serializable
data class RepoPrefsResp(
    val path: String,
    val baseBranch: String? = null,
    val harness: String? = null,
    val model: String? = null,
)

/** CacheMappingResp represents a directory mapping for cache/state sharing. */
@Serializable
data class CacheMappingResp(
    val hostPath: String,
    val containerPath: String,
    val enabled: Boolean,
)

/** MountMappingResp represents a general host-to-runtime directory mount. */
@Serializable
data class MountMappingResp(
    val hostPath: String,
    val containerPath: String,
    val enabled: Boolean,
    val readOnly: Boolean,
)

/** UserSettings holds user-configurable behavioral settings. */
@Serializable
data class UserSettings(
    /**
     * AutoFixOnCIFailure automatically starts a new task to fix CI when a
     * task's PR CI fails and the original task can no longer receive input.
     * Only effective when the GitHub App is configured.
     */
    @SerialName("autoFixOnCIFailure") val autoFixOnCIFailure: Boolean,
    /**
     * AutoFixOnPROpen automatically creates a task to review and fix a pull
     * request when it is opened or reopened via a forge webhook.
     */
    @SerialName("autoFixOnPROpen") val autoFixOnPROpen: Boolean,
    /**
     * BaseImage overrides the default runtime base image. Empty means use
     * the default.
     */
    val baseImage: String? = null,
    /**
     * ContainerPlatform selects the runtime CPU architecture. Empty means use
     * the host's native platform. Valid values are linux/amd64 and linux/arm64.
     */
    val containerPlatform: Platform? = null,
    /**
     * MaxCPUs limits the number of CPU cores the runtime instance may use.
     * Zero means use the system default (max(2, NumCPU-2)).
     */
    @SerialName("maxCPUs") val maxCPUs: Int? = null,
    /**
     * WellKnownCaches maps cache name to enabled state. Absent or false means
     * disabled, true means enabled. Caches are opt-in.
     */
    val wellKnownCaches: Map<String, Boolean>? = null,
    /** CacheMappings are custom host-to-runtime directory mappings. */
    val cacheMappings: List<CacheMappingResp>? = null,
    /** CustomMounts are custom non-cache host-to-runtime directory mappings. */
    val customMounts: List<MountMappingResp>? = null,
)

/** PreferencesResp is the response for GET /api/caic/v1/server/preferences. */
@Serializable
data class PreferencesResp(
    val repositories: List<RepoPrefsResp>,
    val harness: String? = null,
    val models: Map<String, String>? = null,
    val efforts: Map<String, Map<String, String>>? = null,
    val settings: UserSettings,
)

/** UpdatePreferencesReq is the request body for POST /api/caic/v1/server/preferences. */
@Serializable
data class UpdatePreferencesReq(val settings: UserSettings)

/** OAuthGrantResp describes one user-authorized remote MCP client grant. */
@Serializable
data class OAuthGrantResp(
    val id: String,
    @SerialName("clientID") val clientID: String,
    val clientName: String,
    val scopes: List<String>,
    val resource: String,
    val createdAt: Instant,
    val lastUsedAt: Instant? = null,
    val expiresAt: Instant,
    val revokedAt: Instant? = null,
    val status: OAuthGrantStatus,
)

/** OAuthGrantsResp is the response for GET /api/caic/v1/oauth/grants. */
@Serializable
data class OAuthGrantsResp(val grants: List<OAuthGrantResp>)

/** RevokeOAuthGrantReq is the request for POST /api/caic/v1/oauth/grants/{grantID}/revoke. */
@Serializable
class RevokeOAuthGrantReq

/** HarnessInfo is the JSON representation of an available harness. */
@Serializable
data class HarnessInfo(
    val name: String,
    val models: List<String>,
    val supportsImages: Boolean,
    val supportsCompact: Boolean,
)

/** WellKnownCache describes a single well-known cache. */
@Serializable
data class WellKnownCache(
    val name: String,
    val description: String,
    /** List of runtime mount paths */
    val mounts: List<String>,
)

/** WellKnownCachesResp is the response for GET /api/caic/v1/server/caches. */
@Serializable
data class WellKnownCachesResp(
    /** e.g. "~/.claude", "~/.codex" */
    val harnessMounts: List<String>,
    val wellKnown: List<WellKnownCache>,
)

/** CacheSize describes the most recent size snapshot for a well-known cache. */
@Serializable
data class CacheSize(
    val name: String,
    val sizeBytes: Long,
    val calculatedAt: Instant? = null,
    val error: String? = null,
)

/** CacheSizesResp is the response for GET /api/caic/v1/server/cache-sizes. */
@Serializable
data class CacheSizesResp(val wellKnown: List<CacheSize>)

/** BranchInfo describes a single branch with its origin. */
@Serializable
data class BranchInfo(val name: String, val remote: String? = null)

/** ForgeCheck describes a CI check run with its status, conclusion, and timing. */
@Serializable
data class ForgeCheck(
    val name: String,
    val owner: String,
    val repo: String,
    /** Pipeline/workflow run ID. */
    @SerialName("runID") val runID: Long,
    /** Check run / job ID. */
    @SerialName("jobID") val jobID: Long,
    /** queued, in_progress, completed. */
    val status: CheckStatus,
    /** Empty when not completed. */
    val conclusion: CheckConclusion,
    /** When the check was created/queued. */
    val queuedAt: Instant? = null,
    /** When execution began. */
    val startedAt: Instant? = null,
    /** When execution finished. */
    val completedAt: Instant? = null,
)

/** Repo is the JSON representation of a discovered repo. */
@Serializable
data class Repo(
    val path: String,
    val branch: String,
    val baseBranch: BranchInfo,
    @SerialName("remoteURL") val remoteURL: String? = null,
    /** "github", "gitlab", or empty if unknown. */
    val forge: Forge? = null,
    val ci: CIStatus? = null,
    val ciChecks: List<ForgeCheck>? = null,
    val checksDate: Instant? = null,
)

/** CloneRepoReq is the request body for POST /api/caic/v1/server/repos. */
@Serializable
data class CloneRepoReq(
    /** Git clone URL (HTTPS or SSH). */
    val url: String,
    /** Target subdirectory under rootDir; defaults to repo basename. */
    val path: String? = null,
    val depth: Int? = null,
)

/** RepoBranchesResp is the response for GET /api/caic/v1/server/repos/branches. */
@Serializable
data class RepoBranchesResp(val branches: List<BranchInfo>)

/**
 * BotFixCIReq is the request body for POST /api/caic/v1/bot/fix-ci.
 * The server fetches CI logs, builds a prompt, and creates a fix task.
 */
@Serializable
data class BotFixCIReq(val repo: String)

/** TaskRepo describes a repository associated with a task in the API response. */
@Serializable
data class TaskRepo(
    val name: String,
    val baseBranch: String? = null,
    val branch: String,
    @SerialName("remoteURL") val remoteURL: String? = null,
    /** "github", "gitlab", or empty if unknown. */
    val forge: Forge? = null,
)

/** DiffFileStat describes changes to a single file. */
@Serializable
data class DiffFileStat(
    val path: String,
    val added: Int,
    val deleted: Int,
    val binary: Boolean? = null,
)

/** RuntimeInstance holds per-task runtime metadata. */
@Serializable
data class RuntimeInstance(
    /** Runtime instance ID. */
    val id: String,
    /** Tailscale URL (https://fqdn) or "true" if enabled but FQDN unknown. */
    val tailscale: String? = null,
    val usb: Boolean? = null,
    val display: Boolean? = null,
    val sudo: Boolean? = null,
    /** SudoPassword is the random sudo password, only populated when Sudo is true. */
    val sudoPassword: String? = null,
    val vncPort: Int? = null,
)

/** Task is the JSON representation sent to the frontend. */
@Serializable
data class Task(
    val id: String,
    val initialPrompt: String,
    val title: String,
    val repos: List<TaskRepo>? = null,
    val state: TaskState,
    /** When the task state last changed. */
    val stateUpdatedAt: Instant,
    val diffStat: DiffStat? = null,
    @SerialName("costUSD") val costUSD: Double,
    /** Seconds. */
    val duration: Double,
    val numTurns: Int,
    val cumulativeInputTokens: Int,
    val cumulativeOutputTokens: Int,
    val cumulativeCacheCreationInputTokens: Int,
    val cumulativeCacheReadInputTokens: Int,
    /** Last turn's non-cached input tokens (including cache creation). */
    val activeInputTokens: Int,
    /** Last turn's cache-read input tokens. */
    val activeCacheReadTokens: Int,
    /** Effective cache TTL from last API call (seconds); 0 = unknown. */
    @SerialName("cacheTTLSeconds") val cacheTTLSeconds: Int? = null,
    /** When the prompt cache expires. */
    val cacheExpiresAt: Instant? = null,
    /** Model context window limit (tokens). */
    val contextWindowLimit: Int,
    val error: String? = null,
    val result: String? = null,
    val forgeOwner: String? = null,
    val forgeRepo: String? = null,
    @SerialName("forgePR") val forgePR: Int? = null,
    @SerialName("forgePRState") val forgePRState: ForgePRState? = null,
    val forgeIssue: Int? = null,
    val ciStatus: CIStatus? = null,
    val ciChecks: List<ForgeCheck>? = null,
    /** username of creator; omitted in no-auth mode */
    val owner: String? = null,
    /** Per-task harness/agent metadata. */
    val harness: Harness,
    val model: String? = null,
    /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty = default. */
    val effort: String? = null,
    val agentVersion: String? = null,
    @SerialName("sessionID") val sessionID: String? = null,
    /** When the task was created. */
    val startedAt: Instant? = null,
    /** When the current turn started; zero when not running. */
    val turnStartedAt: Instant? = null,
    val inPlanMode: Boolean? = null,
    val planContent: String? = null,
    val runtime: RuntimeInstance,
    /** Per-task feature flags. */
    val gitHubToken: Boolean? = null,
)

/**
 * BotFixPRReq is the request body for POST /api/caic/v1/bot/fix-pr.
 * The server fetches CI logs for the task's PR and injects a fix command.
 */
@Serializable
data class BotFixPRReq(val taskId: String)

/** ImageData carries a single base64-encoded image. */
@Serializable
data class ImageData(
    /** e.g. "image/png", "image/jpeg" */
    val mediaType: String,
    /** base64-encoded */
    val data: String,
)

/** Prompt bundles user text with optional images. */
@Serializable
data class Prompt(val text: String, val images: List<ImageData>? = null)

/** RepoSpec describes a repository to associate with a task at creation time. */
@Serializable
data class RepoSpec(val name: String, val baseBranch: String? = null)

/** CreateTaskReq is the request body for POST /api/caic/v1/tasks. */
@Serializable
data class CreateTaskReq(
    val initialPrompt: Prompt,
    val repos: List<RepoSpec>? = null,
    val model: String? = null,
    /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty = default. */
    val effort: String? = null,
    val harness: Harness,
    val tailscale: Boolean? = null,
    val usb: Boolean? = null,
    val display: Boolean? = null,
    val sudo: Boolean? = null,
    val gitHubToken: Boolean? = null,
)

/**
 * EventInit is emitted once at the start of a session. It includes a Harness
 * field so the client knows which backend produced the stream.
 */
@Serializable
data class EventInit(
    val model: String,
    /** Thinking effort (e.g. "low", "medium", "high", "max"). Empty when not supported. */
    val effort: String? = null,
    val agentVersion: String,
    @SerialName("sessionID") val sessionID: String,
    val tools: List<String>? = null,
    val cwd: String,
    val harness: String,
)

/** EventText is an assistant text block. */
@Serializable
data class EventText(val text: String)

/** EventTextDelta is a streaming text fragment from --include-partial-messages. */
@Serializable
data class EventTextDelta(val text: String)

/** EventToolUse is emitted when the assistant invokes a tool. */
@Serializable
data class EventToolUse(
    @SerialName("toolUseID") val toolUseID: String,
    val name: String,
    val input: JsonElement,
    /** Snapshot of plan content for ExitPlanMode events. */
    val planContent: String? = null,
    /** True when Input was omitted due to size; fetch via GET /api/caic/v1/tasks/{id}/tool/{toolUseID}. */
    val inputTruncated: Boolean? = null,
    /** True when the tool runs in the background (Bash/Agent run_in_background). */
    val background: Boolean? = null,
)

/** EventToolResult is emitted when a tool call completes. */
@Serializable
data class EventToolResult(
    @SerialName("toolUseID") val toolUseID: String,
    /** Seconds; server-computed; 0 if unknown. */
    val duration: Double,
    val error: String? = null,
)

/** AskOption is a single option in an AskUserQuestion. */
@Serializable
data class AskOption(val label: String, val description: String? = null)

/** AskQuestion is a single question from AskUserQuestion. */
@Serializable
data class AskQuestion(
    val question: String,
    val header: String? = null,
    val options: List<AskOption>,
    val multiSelect: Boolean? = null,
)

/** EventAsk is emitted when the agent asks the user a question. */
@Serializable
data class EventAsk(
    @SerialName("toolUseID") val toolUseID: String,
    val questions: List<AskQuestion>,
)

/**
 * EventUsage reports per-turn token usage.
 * ReasoningOutputTokens is a subset of OutputTokens for extended thinking (Claude)
 * or reasoning summaries (Codex). Zero when the harness does not report it.
 */
@Serializable
data class EventUsage(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheCreationInputTokens: Int,
    val cacheReadInputTokens: Int,
    val reasoningOutputTokens: Int? = null,
    val model: String,
)

/** EventResult is emitted when the task reaches a terminal state. */
@Serializable
data class EventResult(
    val subtype: String,
    val isError: Boolean,
    val result: String,
    val diffStat: DiffStat? = null,
    @SerialName("totalCostUSD") val totalCostUSD: Double,
    /** Seconds. */
    val duration: Double,
    /** Seconds. */
    @SerialName("durationAPI") val durationAPI: Double,
    val numTurns: Int,
    val usage: EventUsage,
)

/** EventSystem is a system event (status, compact_boundary, etc.). */
@Serializable
data class EventSystem(
    val subtype: String,
    /** Optional human-readable detail (e.g. model names for model_rerouted). */
    val detail: String? = null,
)

/** EventUserInput is emitted when a user sends a text message to the agent. */
@Serializable
data class EventUserInput(val text: String, val images: List<ImageData>? = null)

/** TodoItem is a single todo entry from a TodoWrite tool call. */
@Serializable
data class TodoItem(
    val content: String,
    /** "pending", "in_progress", "completed". */
    val status: String,
    val activeForm: String? = null,
)

/** EventTodo is emitted when the agent writes/updates its todo list. */
@Serializable
data class EventTodo(
    @SerialName("toolUseID") val toolUseID: String,
    val todos: List<TodoItem>,
)

/** EventDiffStat is emitted when the relay reports updated diff statistics. */
@Serializable
data class EventDiffStat(val diffStat: DiffStat? = null)

/** EventError is emitted when the backend fails to parse an agent output line. */
@Serializable
data class EventError(val err: String, val line: String)

/** EventThinking is an assistant thinking block. */
@Serializable
data class EventThinking(val text: String)

/** EventThinkingDelta is a streaming thinking fragment. */
@Serializable
data class EventThinkingDelta(val text: String)

/** EventSubagentStart is emitted when a subagent task begins. */
@Serializable
data class EventSubagentStart(
    @SerialName("taskID") val taskID: String,
    val description: String,
)

/** EventSubagentEnd is emitted when a subagent task completes, fails, or stops. */
@Serializable
data class EventSubagentEnd(
    @SerialName("taskID") val taskID: String,
    /** "completed", "failed", "stopped" */
    val status: String,
)

/** EventLog is a provisioning/startup log line from the runtime backend. */
@Serializable
data class EventLog(val line: String)

/**
 * EventToolOutputDelta is a streaming output fragment from a running tool.
 * Codex only: emitted for Bash stdout (item/commandExecution/outputDelta) and
 * MCP tool progress messages (item/mcpToolCall/progress).
 */
@Serializable
data class EventToolOutputDelta(
    @SerialName("toolUseID") val toolUseID: String,
    val delta: String,
    val contentType: ToolOutputContentType? = null,
    /** Pretty-printed JSON or other transformation. */
    val formatted: String? = null,
)

/** EventWidget is emitted when the agent produces a complete HTML widget. */
@Serializable
data class EventWidget(
    @SerialName("toolUseID") val toolUseID: String,
    val title: String,
    val html: String,
)

/** EventWidgetDelta is a streaming HTML fragment for progressive widget rendering. */
@Serializable
data class EventWidgetDelta(
    @SerialName("toolUseID") val toolUseID: String,
    val delta: String,
)

/** EventRateLimit is emitted when the agent's rate limit status changes. */
@Serializable
data class EventRateLimit(
    /** "allowed", "allowed_warning", "rejected". */
    val status: String,
    /** When the limit resets; zero if unknown. */
    val resetsAt: Instant? = null,
    /** "five_hour", "seven_day", etc. */
    val rateLimitType: String,
    /** 0.0–1.0. */
    val utilization: Double,
    /** True when extra/overage usage is active. */
    val isUsingOverage: Boolean? = null,
    /** When overage resets; zero if not using overage. */
    val overageResetsAt: Instant? = null,
)

/** EventStats is a runtime resource usage snapshot emitted periodically. */
@Serializable
data class EventStats(
    val ts: Long,
    val cpuPerc: Double,
    val memUsed: Long,
    val memLimit: Long,
    val memPerc: Double,
    val netRx: Long,
    val netTx: Long,
    val blockRead: Long,
    val blockWrite: Long,
    val diskUsed: Long,
)

// Backend-neutral event types

/**
 * EventMessage is a single SSE event in the backend-neutral stream
 * (/api/caic/v1/tasks/{id}/events). All backends produce these events.
 */
@Serializable
data class EventMessage(
    val kind: EventKind,
    val ts: Long,
    val init: EventInit? = null,
    val text: EventText? = null,
    val textDelta: EventTextDelta? = null,
    val toolUse: EventToolUse? = null,
    val toolResult: EventToolResult? = null,
    val ask: EventAsk? = null,
    val usage: EventUsage? = null,
    val result: EventResult? = null,
    val system: EventSystem? = null,
    val userInput: EventUserInput? = null,
    val todo: EventTodo? = null,
    val diffStat: EventDiffStat? = null,
    val error: EventError? = null,
    val thinking: EventThinking? = null,
    val thinkingDelta: EventThinkingDelta? = null,
    val subagentStart: EventSubagentStart? = null,
    val subagentEnd: EventSubagentEnd? = null,
    val log: EventLog? = null,
    val toolOutputDelta: EventToolOutputDelta? = null,
    val widget: EventWidget? = null,
    val widgetDelta: EventWidgetDelta? = null,
    val rateLimit: EventRateLimit? = null,
    val stats: EventStats? = null,
)

/** InputReq is the request body for POST /api/caic/v1/tasks/{id}/input. */
@Serializable
data class InputReq(val prompt: Prompt)

/** RestartReq is the request body for POST /api/caic/v1/tasks/{id}/restart. */
@Serializable
data class RestartReq(val prompt: Prompt)

/** CompactReq is the request body for POST /api/caic/v1/tasks/{id}/compact. */
@Serializable
data class CompactReq(val instructions: String? = null)

/**
 * CILogResp is the response for GET /api/caic/v1/tasks/{id}/ci-log.
 * It contains the name of the first failed CI step and its log tail.
 */
@Serializable
data class CILogResp(val stepName: String, val log: String)

/** SyncReq is the request body for POST /api/caic/v1/tasks/{id}/sync. */
@Serializable
data class SyncReq(val force: Boolean? = null, val target: SyncTarget? = null)

/** SafetyIssue describes a potential problem detected before pushing to origin. */
@Serializable
data class SafetyIssue(
    val file: String,
    /** "large_binary" or "secret" */
    val kind: String,
    /** Human-readable description. */
    val detail: String,
)

/** SyncResp is the response for POST /api/caic/v1/tasks/{id}/sync. */
@Serializable
data class SyncResp(
    /** "synced", "blocked", or "empty" */
    val status: String,
    val branch: String? = null,
    val diffStat: DiffStat? = null,
    val safetyIssues: List<SafetyIssue>? = null,
    /** non-zero if a PR/MR was created */
    val prNumber: Int? = null,
)

/** ForkTaskReq is the request body for POST /api/caic/v1/tasks/{id}/fork. */
@Serializable
data class ForkTaskReq(
    /** Initial prompt for the forked task. */
    val prompt: Prompt,
    /** Override harness; empty means inherit from source. */
    val harness: Harness? = null,
    /** Override model; empty means inherit from source. */
    val model: String? = null,
    /** Override thinking effort; empty means inherit from source. */
    val effort: String? = null,
    /** Additional repos to map into the fork. */
    val extraRepos: List<RepoSpec>? = null,
    /** Override Tailscale; nil means inherit from source. */
    val tailscale: Boolean? = null,
    /** Override USB; nil means inherit from source. */
    val usb: Boolean? = null,
    /** Override virtual display; nil means inherit from source. */
    val display: Boolean? = null,
    /** Override sudo; nil means inherit from source. */
    val sudo: Boolean? = null,
    /** Override gitHubToken; nil means inherit from source. */
    val gitHubToken: Boolean? = null,
)

/** DiffResp is the response for GET /api/caic/v1/tasks/{id}/diff. */
@Serializable
data class DiffResp(val diff: String)

/** ProcessInfo describes a single process running inside a task runtime instance. */
@Serializable
data class ProcessInfo(
    val pid: Int,
    val ppid: Int,
    val user: String,
    /** Single-character state: R, S, D, Z, T, etc. */
    val state: String,
    val cpu: Double,
    val mem: Double,
    /** Cumulative CPU time. */
    val time: String,
    /** Full command line. */
    val command: String,
)

/** ProcessListResp is the response for GET /api/caic/v1/tasks/{id}/processes. */
@Serializable
data class ProcessListResp(val processes: List<ProcessInfo>)

/** SignalProcessReq is the request body for POST /api/caic/v1/tasks/{id}/processes/{pid}/signal. */
@Serializable
data class SignalProcessReq(
    /** "SIGTERM" or "SIGKILL" */
    val signal: String,
)

/**
 * TaskToolInputResp is the response for GET /api/caic/v1/tasks/{id}/tool/{toolUseID}.
 * It returns the full (untruncated) input for a tool call.
 */
@Serializable
data class TaskToolInputResp(
    @SerialName("toolUseID") val toolUseID: String,
    val input: JsonElement,
)

/**
 * TaskListEvent is a discriminated-union event for the task list SSE stream.
 * kind=="snapshot": Tasks holds the full list on initial connect.
 * kind=="upsert":   Task holds a newly created task.
 * kind=="patch":    Patch holds only the changed fields (always includes "id") for an existing task.
 * kind=="delete":   ID holds the string ID of the removed task.
 * kind=="repos":    Repos holds the updated repo list (emitted when default-branch CI status changes).
 * kind=="warning":  Warning holds a transient server warning message for the user.
 */
@Serializable
data class TaskListEvent(
    val kind: String,
    val snapshot: List<Task>? = null,
    val upsert: Task? = null,
    val patch: Map<String, JsonElement>? = null,
    val delete: String? = null,
    val repos: List<Repo>? = null,
    val warning: String? = null,
)

/** QuotaRateLimit is a single rate-limit window snapshot from any provider. */
@Serializable
data class QuotaRateLimit(
    /** "5h", "7d", "primary", "secondary", "rpm", "tpd", … */
    val window: String,
    /** 0–100 */
    val usedPct: Double,
    /** zero when unknown */
    val resetsAt: Instant? = null,
)

/** QuotaBalance is a balance/credit snapshot from any provider. */
@Serializable
data class QuotaBalance(
    /** "USD", "CNY", "credits", … */
    val currency: String,
    /** total available balance */
    val total: Double,
    /** unexpired promotional/grant balance */
    val granted: Double? = null,
    /** self-funded recharge balance */
    val toppedUp: Double? = null,
)

/** QuotaExtraUsage is pay-as-you-go usage info (Anthropic-style extra credits). */
@Serializable
data class QuotaExtraUsage(
    /** "USD", "CNY", … */
    val currency: String,
    val isEnabled: Boolean,
    val usedCredits: Double,
    val monthlyLimit: Double,
    val usedPct: Double,
)

/** ProviderQuota is the quota data for one provider. */
@Serializable
data class ProviderQuota(
    /** "anthropic", "deepseek", "gemini", "openai", "codex", "openrouter", … */
    val provider: String,
    /** human-readable: "Anthropic", "DeepSeek", … */
    val label: String,
    /** absolute URL path to provider SVG, e.g. "/logos/anthropic.svg" */
    val logoUrl: String,
    /** "oauth" or "apikey" */
    val authKind: String,
    /** link to provider's usage/billing page */
    val usageUrl: String,
    val rateLimits: List<QuotaRateLimit>? = null,
    val balance: QuotaBalance? = null,
    val extraUsage: QuotaExtraUsage? = null,
)

/** LocalWindow is the aggregated local cost for a rolling time window. */
@Serializable
data class LocalWindow(
    /** "1h", "6h", "24h" */
    val duration: String,
    @SerialName("costUSD") val costUSD: Double,
    val inputTokens: Int,
    val outputTokens: Int,
)

/** LocalUsage is the aggregated cost across all tasks within recent time windows. */
@Serializable
data class LocalUsage(val windows: List<LocalWindow>)

/** UsageResp is the response for GET /api/caic/v1/usage. */
@Serializable
data class UsageResp(val providers: List<ProviderQuota>? = null, val local: LocalUsage)

/** WebFetchReq is the request body for POST /api/caic/v1/web/fetch. */
@Serializable
data class WebFetchReq(val url: String)

/** WebFetchResp is the response for POST /api/caic/v1/web/fetch. */
@Serializable
data class WebFetchResp(val title: String, val content: String)

@Serializable
data class ErrorDetails(val code: String, val message: String)

@Serializable
data class ErrorResponse(val error: ErrorDetails, val details: Map<String, JsonElement>? = null)

